/* Generated by Yosys 0.54+29 (git sha1 7b0c1fe49, g++ 9.4.0-1ubuntu1~20.04.2 -fPIC -O3) */

module s420(GND, VDD, CK, C_0, C_1, C_10, C_11, C_12, C_13, C_14, C_15, C_16, C_2, C_3, C_4, C_5, C_6, C_7, C_8, C_9, P_0
, Z);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  input CK;
  wire CK;
  input C_0;
  wire C_0;
  input C_1;
  wire C_1;
  input C_10;
  wire C_10;
  input C_11;
  wire C_11;
  input C_12;
  wire C_12;
  input C_13;
  wire C_13;
  input C_14;
  wire C_14;
  input C_15;
  wire C_15;
  input C_16;
  wire C_16;
  input C_2;
  wire C_2;
  input C_3;
  wire C_3;
  input C_4;
  wire C_4;
  input C_5;
  wire C_5;
  input C_6;
  wire C_6;
  input C_7;
  wire C_7;
  input C_8;
  wire C_8;
  input C_9;
  wire C_9;
  wire \DFF_0.CK ;
  wire \DFF_0.D ;
  wire \DFF_1.CK ;
  wire \DFF_1.D ;
  wire \DFF_10.CK ;
  wire \DFF_10.D ;
  wire \DFF_11.CK ;
  wire \DFF_11.D ;
  wire \DFF_12.CK ;
  wire \DFF_12.D ;
  wire \DFF_13.CK ;
  wire \DFF_13.D ;
  wire \DFF_14.CK ;
  wire \DFF_14.D ;
  wire \DFF_15.CK ;
  wire \DFF_15.D ;
  wire \DFF_2.CK ;
  wire \DFF_2.D ;
  wire \DFF_3.CK ;
  wire \DFF_3.D ;
  wire \DFF_4.CK ;
  wire \DFF_4.D ;
  wire \DFF_5.CK ;
  wire \DFF_5.D ;
  wire \DFF_6.CK ;
  wire \DFF_6.D ;
  wire \DFF_7.CK ;
  wire \DFF_7.D ;
  wire \DFF_8.CK ;
  wire \DFF_8.D ;
  wire \DFF_9.CK ;
  wire \DFF_9.D ;
  input GND;
  wire GND;
  wire I110;
  wire I111;
  wire I112;
  wire I113;
  wire I12;
  wire I13;
  wire I14;
  wire I15;
  wire I208;
  wire I209;
  wire I210;
  wire I211;
  wire I306;
  wire I307;
  wire I308;
  wire I309;
  input P_0;
  wire P_0;
  input VDD;
  wire VDD;
  output Z;
  wire Z;
  INVx1_ASAP7_75t_L _063_ (
    .A(P_0),
    .Y(_031_)
  );
  INVx1_ASAP7_75t_L _064_ (
    .A(_000_),
    .Y(_032_)
  );
  INVx1_ASAP7_75t_L _065_ (
    .A(C_6),
    .Y(_033_)
  );
  INVx1_ASAP7_75t_L _066_ (
    .A(C_4),
    .Y(_034_)
  );
  INVx1_ASAP7_75t_L _067_ (
    .A(C_10),
    .Y(_035_)
  );
  INVx1_ASAP7_75t_L _068_ (
    .A(C_8),
    .Y(_036_)
  );
  INVx1_ASAP7_75t_L _069_ (
    .A(C_12),
    .Y(_037_)
  );
  INVx1_ASAP7_75t_L _070_ (
    .A(C_16),
    .Y(_038_)
  );
  INVx1_ASAP7_75t_L _071_ (
    .A(_010_),
    .Y(_039_)
  );
  NAND2xp33_ASAP7_75t_L _072_ (
    .A(P_0),
    .B(_039_),
    .Y(_040_)
  );
  NOR2xp33_ASAP7_75t_L _073_ (
    .A(_001_),
    .B(_040_),
    .Y(_041_)
  );
  OR5x1_ASAP7_75t_L _074_ (
    .A(_031_),
    .B(_002_),
    .C(_003_),
    .D(_001_),
    .E(_010_),
    .Y(_042_)
  );
  OAI31xp33_ASAP7_75t_L _075_ (
    .A1(_003_),
    .A2(_001_),
    .A3(_040_),
    .B(_002_),
    .Y(_043_)
  );
  AND2x2_ASAP7_75t_L _076_ (
    .A(_042_),
    .B(_043_),
    .Y(\DFF_0.D )
  );
  OR2x2_ASAP7_75t_L _077_ (
    .A(_012_),
    .B(_042_),
    .Y(_044_)
  );
  NOR2xp33_ASAP7_75t_L _078_ (
    .A(_011_),
    .B(_044_),
    .Y(_045_)
  );
  OR5x1_ASAP7_75t_L _079_ (
    .A(_004_),
    .B(_006_),
    .C(_011_),
    .D(_012_),
    .E(_042_),
    .Y(_046_)
  );
  OAI31xp33_ASAP7_75t_L _080_ (
    .A1(_004_),
    .A2(_011_),
    .A3(_044_),
    .B(_006_),
    .Y(_047_)
  );
  AND2x2_ASAP7_75t_L _081_ (
    .A(_046_),
    .B(_047_),
    .Y(\DFF_4.D )
  );
  OR2x2_ASAP7_75t_L _082_ (
    .A(_013_),
    .B(_046_),
    .Y(_048_)
  );
  NOR2xp33_ASAP7_75t_L _083_ (
    .A(_014_),
    .B(_048_),
    .Y(_049_)
  );
  OR5x1_ASAP7_75t_L _084_ (
    .A(_005_),
    .B(_007_),
    .C(_013_),
    .D(_014_),
    .E(_046_),
    .Y(_050_)
  );
  OAI31xp33_ASAP7_75t_L _085_ (
    .A1(_007_),
    .A2(_014_),
    .A3(_048_),
    .B(_005_),
    .Y(_051_)
  );
  AND2x2_ASAP7_75t_L _086_ (
    .A(_050_),
    .B(_051_),
    .Y(\DFF_8.D )
  );
  NOR3xp33_ASAP7_75t_L _087_ (
    .A(_009_),
    .B(_008_),
    .C(_050_),
    .Y(_052_)
  );
  NOR4xp25_ASAP7_75t_L _088_ (
    .A(_009_),
    .B(_008_),
    .C(_000_),
    .D(_050_),
    .Y(_053_)
  );
  XNOR2xp5_ASAP7_75t_L _089_ (
    .A(_015_),
    .B(_053_),
    .Y(\DFF_12.D )
  );
  XNOR2xp5_ASAP7_75t_L _090_ (
    .A(_000_),
    .B(_052_),
    .Y(\DFF_13.D )
  );
  XOR2xp5_ASAP7_75t_L _091_ (
    .A(_001_),
    .B(_040_),
    .Y(\DFF_2.D )
  );
  XOR2xp5_ASAP7_75t_L _092_ (
    .A(_011_),
    .B(_044_),
    .Y(\DFF_6.D )
  );
  XOR2xp5_ASAP7_75t_L _093_ (
    .A(_014_),
    .B(_048_),
    .Y(\DFF_10.D )
  );
  OA21x2_ASAP7_75t_L _094_ (
    .A1(_009_),
    .A2(_050_),
    .B(_008_),
    .Y(_054_)
  );
  NOR2xp33_ASAP7_75t_L _095_ (
    .A(_052_),
    .B(_054_),
    .Y(\DFF_14.D )
  );
  XNOR2xp5_ASAP7_75t_L _096_ (
    .A(_003_),
    .B(_041_),
    .Y(\DFF_1.D )
  );
  XNOR2xp5_ASAP7_75t_L _097_ (
    .A(P_0),
    .B(_010_),
    .Y(\DFF_3.D )
  );
  XNOR2xp5_ASAP7_75t_L _098_ (
    .A(_004_),
    .B(_045_),
    .Y(\DFF_5.D )
  );
  XOR2xp5_ASAP7_75t_L _099_ (
    .A(_012_),
    .B(_042_),
    .Y(\DFF_7.D )
  );
  XNOR2xp5_ASAP7_75t_L _100_ (
    .A(_007_),
    .B(_049_),
    .Y(\DFF_9.D )
  );
  XOR2xp5_ASAP7_75t_L _101_ (
    .A(_013_),
    .B(_046_),
    .Y(\DFF_11.D )
  );
  XOR2xp5_ASAP7_75t_L _102_ (
    .A(_009_),
    .B(_050_),
    .Y(\DFF_15.D )
  );
  OAI21xp33_ASAP7_75t_L _103_ (
    .A1(_035_),
    .A2(_014_),
    .B(_013_),
    .Y(_055_)
  );
  OR2x2_ASAP7_75t_L _104_ (
    .A(_008_),
    .B(C_14),
    .Y(_056_)
  );
  OAI31xp33_ASAP7_75t_L _105_ (
    .A1(_032_),
    .A2(_038_),
    .A3(_015_),
    .B(_008_),
    .Y(_057_)
  );
  A2O1A1Ixp33_ASAP7_75t_L _106_ (
    .A1(_032_),
    .A2(C_15),
    .B(_057_),
    .C(_056_),
    .Y(_058_)
  );
  OAI21xp33_ASAP7_75t_L _107_ (
    .A1(_007_),
    .A2(C_11),
    .B(_014_),
    .Y(_059_)
  );
  O2A1O1Ixp33_ASAP7_75t_L _108_ (
    .A1(_005_),
    .A2(_037_),
    .B(_007_),
    .C(_059_),
    .Y(_060_)
  );
  NOR2xp33_ASAP7_75t_L _109_ (
    .A(_055_),
    .B(_060_),
    .Y(_061_)
  );
  AND3x1_ASAP7_75t_L _110_ (
    .A(_005_),
    .B(_007_),
    .C(_014_),
    .Y(_062_)
  );
  OAI21xp33_ASAP7_75t_L _111_ (
    .A1(_009_),
    .A2(C_13),
    .B(_062_),
    .Y(_016_)
  );
  A2O1A1Ixp33_ASAP7_75t_L _112_ (
    .A1(_009_),
    .A2(_058_),
    .B(_016_),
    .C(_061_),
    .Y(_017_)
  );
  AND4x1_ASAP7_75t_L _113_ (
    .A(_004_),
    .B(_006_),
    .C(_011_),
    .D(_012_),
    .Y(_018_)
  );
  OA21x2_ASAP7_75t_L _114_ (
    .A1(C_9),
    .A2(_013_),
    .B(_018_),
    .Y(_019_)
  );
  OR2x2_ASAP7_75t_L _115_ (
    .A(C_5),
    .B(_012_),
    .Y(_020_)
  );
  OAI21xp33_ASAP7_75t_L _116_ (
    .A1(_006_),
    .A2(_036_),
    .B(_004_),
    .Y(_021_)
  );
  OAI211xp5_ASAP7_75t_L _117_ (
    .A1(_004_),
    .A2(C_7),
    .B(_011_),
    .C(_021_),
    .Y(_022_)
  );
  OAI211xp5_ASAP7_75t_L _118_ (
    .A1(_033_),
    .A2(_011_),
    .B(_012_),
    .C(_022_),
    .Y(_023_)
  );
  AOI22xp33_ASAP7_75t_L _119_ (
    .A1(_017_),
    .A2(_019_),
    .B1(_020_),
    .B2(_023_),
    .Y(_024_)
  );
  NAND5xp2_ASAP7_75t_L _120_ (
    .A(P_0),
    .B(_002_),
    .C(_003_),
    .D(_001_),
    .E(_010_),
    .Y(_025_)
  );
  OAI21xp33_ASAP7_75t_L _121_ (
    .A1(_002_),
    .A2(_034_),
    .B(_003_),
    .Y(_026_)
  );
  OAI21xp33_ASAP7_75t_L _122_ (
    .A1(_003_),
    .A2(C_3),
    .B(_026_),
    .Y(_027_)
  );
  OAI211xp5_ASAP7_75t_L _123_ (
    .A1(_001_),
    .A2(C_2),
    .B(_010_),
    .C(P_0),
    .Y(_028_)
  );
  AOI21xp33_ASAP7_75t_L _124_ (
    .A1(_001_),
    .A2(_027_),
    .B(_028_),
    .Y(_029_)
  );
  A2O1A1O1Ixp25_ASAP7_75t_L _125_ (
    .A1(C_1),
    .A2(_039_),
    .B(C_0),
    .C(P_0),
    .D(_029_),
    .Y(_030_)
  );
  OAI21xp33_ASAP7_75t_L _126_ (
    .A1(_024_),
    .A2(_025_),
    .B(_030_),
    .Y(Z)
  );
  DFFHQNx1_ASAP7_75t_R _127_ (
    .CLK(CK),
    .D(\DFF_4.D ),
    .QN(_006_)
  );
  DFFHQNx1_ASAP7_75t_R _128_ (
    .CLK(CK),
    .D(\DFF_3.D ),
    .QN(_010_)
  );
  DFFHQNx1_ASAP7_75t_R _129_ (
    .CLK(CK),
    .D(\DFF_5.D ),
    .QN(_004_)
  );
  DFFHQNx1_ASAP7_75t_R _130_ (
    .CLK(CK),
    .D(\DFF_2.D ),
    .QN(_001_)
  );
  DFFHQNx1_ASAP7_75t_R _131_ (
    .CLK(CK),
    .D(\DFF_6.D ),
    .QN(_011_)
  );
  DFFHQNx1_ASAP7_75t_R _132_ (
    .CLK(CK),
    .D(\DFF_9.D ),
    .QN(_007_)
  );
  DFFHQNx1_ASAP7_75t_R _133_ (
    .CLK(CK),
    .D(\DFF_7.D ),
    .QN(_012_)
  );
  DFFHQNx1_ASAP7_75t_R _134_ (
    .CLK(CK),
    .D(\DFF_8.D ),
    .QN(_005_)
  );
  DFFHQNx1_ASAP7_75t_R _135_ (
    .CLK(CK),
    .D(\DFF_11.D ),
    .QN(_013_)
  );
  DFFHQNx1_ASAP7_75t_R _136_ (
    .CLK(CK),
    .D(\DFF_10.D ),
    .QN(_014_)
  );
  DFFHQNx1_ASAP7_75t_R _137_ (
    .CLK(CK),
    .D(\DFF_12.D ),
    .QN(_015_)
  );
  DFFHQNx1_ASAP7_75t_R _138_ (
    .CLK(CK),
    .D(\DFF_13.D ),
    .QN(_000_)
  );
  DFFHQNx1_ASAP7_75t_R _139_ (
    .CLK(CK),
    .D(\DFF_15.D ),
    .QN(_009_)
  );
  DFFHQNx1_ASAP7_75t_R _140_ (
    .CLK(CK),
    .D(\DFF_14.D ),
    .QN(_008_)
  );
  DFFHQNx1_ASAP7_75t_R _141_ (
    .CLK(CK),
    .D(\DFF_1.D ),
    .QN(_003_)
  );
  DFFHQNx1_ASAP7_75t_R _142_ (
    .CLK(CK),
    .D(\DFF_0.D ),
    .QN(_002_)
  );
  assign \DFF_0.CK  = CK;
  assign \DFF_1.CK  = CK;
  assign \DFF_10.CK  = CK;
  assign \DFF_11.CK  = CK;
  assign \DFF_12.CK  = CK;
  assign \DFF_13.CK  = CK;
  assign \DFF_14.CK  = CK;
  assign \DFF_15.CK  = CK;
  assign \DFF_2.CK  = CK;
  assign \DFF_3.CK  = CK;
  assign \DFF_4.CK  = CK;
  assign \DFF_5.CK  = CK;
  assign \DFF_6.CK  = CK;
  assign \DFF_7.CK  = CK;
  assign \DFF_8.CK  = CK;
  assign \DFF_9.CK  = CK;
  assign I110 = \DFF_4.D ;
  assign I111 = \DFF_5.D ;
  assign I112 = \DFF_6.D ;
  assign I113 = \DFF_7.D ;
  assign I12 = \DFF_0.D ;
  assign I13 = \DFF_1.D ;
  assign I14 = \DFF_2.D ;
  assign I15 = \DFF_3.D ;
  assign I208 = \DFF_8.D ;
  assign I209 = \DFF_9.D ;
  assign I210 = \DFF_10.D ;
  assign I211 = \DFF_11.D ;
  assign I306 = \DFF_12.D ;
  assign I307 = \DFF_13.D ;
  assign I308 = \DFF_14.D ;
  assign I309 = \DFF_15.D ;
endmodule
