/* Generated by Yosys 0.54+29 (git sha1 7b0c1fe49, g++ 9.4.0-1ubuntu1~20.04.2 -fPIC -O3) */

module s820(GND, VDD, CK, G0, G1, G10, G11, G12, G13, G14, G15, G16, G18, G2, G288, G290, G292, G296, G298, G3, G300
, G302, G310, G312, G315, G322, G325, G327, G4, G43, G45, G47, G49, G5, G53, G55, G6, G7, G8, G9);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  input CK;
  wire CK;
  wire \DFF_0.CK ;
  wire \DFF_0.D ;
  wire \DFF_1.CK ;
  wire \DFF_1.D ;
  wire \DFF_2.CK ;
  wire \DFF_2.D ;
  wire \DFF_3.CK ;
  wire \DFF_3.D ;
  wire \DFF_4.CK ;
  wire \DFF_4.D ;
  input G0;
  wire G0;
  input G1;
  wire G1;
  input G10;
  wire G10;
  wire G102;
  input G11;
  wire G11;
  input G12;
  wire G12;
  input G13;
  wire G13;
  input G14;
  wire G14;
  input G15;
  wire G15;
  input G16;
  wire G16;
  input G18;
  wire G18;
  input G2;
  wire G2;
  wire G229;
  output G288;
  wire G288;
  output G290;
  wire G290;
  output G292;
  wire G292;
  output G296;
  wire G296;
  output G298;
  wire G298;
  input G3;
  wire G3;
  output G300;
  wire G300;
  output G302;
  wire G302;
  output G310;
  wire G310;
  output G312;
  wire G312;
  output G315;
  wire G315;
  output G322;
  wire G322;
  output G325;
  wire G325;
  output G327;
  wire G327;
  input G4;
  wire G4;
  output G43;
  wire G43;
  output G45;
  wire G45;
  output G47;
  wire G47;
  output G49;
  wire G49;
  input G5;
  wire G5;
  output G53;
  wire G53;
  output G55;
  wire G55;
  input G6;
  wire G6;
  input G7;
  wire G7;
  input G8;
  wire G8;
  input G9;
  wire G9;
  wire G90;
  wire G93;
  wire G96;
  wire G99;
  input GND;
  wire GND;
  input VDD;
  wire VDD;
  INVx1_ASAP7_75t_L _122_ (
    .A(_000_),
    .Y(_084_)
  );
  INVx1_ASAP7_75t_L _123_ (
    .A(_001_),
    .Y(_085_)
  );
  INVx1_ASAP7_75t_L _124_ (
    .A(_003_),
    .Y(_086_)
  );
  INVx1_ASAP7_75t_L _125_ (
    .A(_002_),
    .Y(_087_)
  );
  INVx1_ASAP7_75t_L _126_ (
    .A(_004_),
    .Y(_088_)
  );
  INVx1_ASAP7_75t_L _127_ (
    .A(G16),
    .Y(_089_)
  );
  INVx1_ASAP7_75t_L _128_ (
    .A(G4),
    .Y(_090_)
  );
  INVx1_ASAP7_75t_L _129_ (
    .A(G15),
    .Y(_091_)
  );
  INVx1_ASAP7_75t_L _130_ (
    .A(G3),
    .Y(_092_)
  );
  INVx1_ASAP7_75t_L _131_ (
    .A(G14),
    .Y(_093_)
  );
  NAND2xp33_ASAP7_75t_L _132_ (
    .A(_000_),
    .B(_001_),
    .Y(_094_)
  );
  NAND2xp33_ASAP7_75t_L _133_ (
    .A(_002_),
    .B(_004_),
    .Y(_095_)
  );
  NAND2xp33_ASAP7_75t_L _134_ (
    .A(_001_),
    .B(_004_),
    .Y(_096_)
  );
  NAND2xp33_ASAP7_75t_L _135_ (
    .A(_003_),
    .B(_004_),
    .Y(_097_)
  );
  NAND3xp33_ASAP7_75t_L _136_ (
    .A(_001_),
    .B(_003_),
    .C(_004_),
    .Y(_098_)
  );
  OR3x1_ASAP7_75t_L _137_ (
    .A(_084_),
    .B(_087_),
    .C(_098_),
    .Y(_099_)
  );
  NOR2xp33_ASAP7_75t_L _138_ (
    .A(_001_),
    .B(_004_),
    .Y(_100_)
  );
  NAND2xp33_ASAP7_75t_L _139_ (
    .A(_000_),
    .B(_100_),
    .Y(_101_)
  );
  NOR2xp33_ASAP7_75t_L _140_ (
    .A(_003_),
    .B(_002_),
    .Y(_102_)
  );
  OAI31xp33_ASAP7_75t_L _141_ (
    .A1(_003_),
    .A2(_002_),
    .A3(_101_),
    .B(_099_),
    .Y(G315)
  );
  NAND2xp33_ASAP7_75t_L _142_ (
    .A(_085_),
    .B(_004_),
    .Y(_103_)
  );
  NAND2xp33_ASAP7_75t_L _143_ (
    .A(_003_),
    .B(_002_),
    .Y(_104_)
  );
  AOI31xp33_ASAP7_75t_L _144_ (
    .A1(_084_),
    .A2(_003_),
    .A3(_002_),
    .B(_004_),
    .Y(_105_)
  );
  NOR2xp33_ASAP7_75t_L _145_ (
    .A(_003_),
    .B(_004_),
    .Y(_106_)
  );
  NOR3xp33_ASAP7_75t_L _146_ (
    .A(_003_),
    .B(_002_),
    .C(_004_),
    .Y(_107_)
  );
  OAI21xp33_ASAP7_75t_L _147_ (
    .A1(_003_),
    .A2(_002_),
    .B(_004_),
    .Y(_108_)
  );
  OAI211xp5_ASAP7_75t_L _148_ (
    .A1(_000_),
    .A2(_107_),
    .B(_108_),
    .C(_001_),
    .Y(_109_)
  );
  OAI21xp33_ASAP7_75t_L _149_ (
    .A1(_001_),
    .A2(_105_),
    .B(_109_),
    .Y(G49)
  );
  NOR2xp33_ASAP7_75t_L _150_ (
    .A(_089_),
    .B(G4),
    .Y(_110_)
  );
  NAND2xp33_ASAP7_75t_L _151_ (
    .A(G16),
    .B(_090_),
    .Y(_111_)
  );
  NOR3xp33_ASAP7_75t_L _152_ (
    .A(_001_),
    .B(_090_),
    .C(_105_),
    .Y(_112_)
  );
  NOR3xp33_ASAP7_75t_L _153_ (
    .A(G16),
    .B(_102_),
    .C(_103_),
    .Y(_113_)
  );
  NAND2xp33_ASAP7_75t_L _154_ (
    .A(_004_),
    .B(G16),
    .Y(_114_)
  );
  NOR4xp25_ASAP7_75t_L _155_ (
    .A(G1),
    .B(_094_),
    .C(_104_),
    .D(_114_),
    .Y(_115_)
  );
  NOR3xp33_ASAP7_75t_L _156_ (
    .A(_112_),
    .B(_113_),
    .C(_115_),
    .Y(_116_)
  );
  OAI21xp33_ASAP7_75t_L _157_ (
    .A1(_109_),
    .A2(_110_),
    .B(_116_),
    .Y(G302)
  );
  NOR4xp25_ASAP7_75t_L _158_ (
    .A(_001_),
    .B(_087_),
    .C(_091_),
    .D(_097_),
    .Y(G290)
  );
  NOR4xp25_ASAP7_75t_L _159_ (
    .A(_001_),
    .B(_002_),
    .C(_091_),
    .D(_097_),
    .Y(G327)
  );
  NOR2xp33_ASAP7_75t_L _160_ (
    .A(_101_),
    .B(_104_),
    .Y(G288)
  );
  NOR3xp33_ASAP7_75t_L _161_ (
    .A(G5),
    .B(_101_),
    .C(_104_),
    .Y(G47)
  );
  NAND3xp33_ASAP7_75t_L _162_ (
    .A(_003_),
    .B(_002_),
    .C(G5),
    .Y(_117_)
  );
  NOR2xp33_ASAP7_75t_L _163_ (
    .A(_101_),
    .B(_117_),
    .Y(G55)
  );
  NOR3xp33_ASAP7_75t_L _164_ (
    .A(_003_),
    .B(_087_),
    .C(_101_),
    .Y(G296)
  );
  NAND2xp33_ASAP7_75t_L _165_ (
    .A(_003_),
    .B(_087_),
    .Y(_118_)
  );
  NOR2xp33_ASAP7_75t_L _166_ (
    .A(_101_),
    .B(_118_),
    .Y(G310)
  );
  NOR4xp25_ASAP7_75t_L _167_ (
    .A(_003_),
    .B(_002_),
    .C(_089_),
    .D(_101_),
    .Y(G312)
  );
  NOR4xp25_ASAP7_75t_L _168_ (
    .A(G16),
    .B(G1),
    .C(_092_),
    .D(_099_),
    .Y(G300)
  );
  NOR3xp33_ASAP7_75t_L _169_ (
    .A(_003_),
    .B(_094_),
    .C(_095_),
    .Y(G53)
  );
  NOR4xp25_ASAP7_75t_L _170_ (
    .A(_003_),
    .B(_091_),
    .C(_094_),
    .D(_095_),
    .Y(G43)
  );
  AND2x2_ASAP7_75t_L _171_ (
    .A(G14),
    .B(G43),
    .Y(G298)
  );
  NOR3xp33_ASAP7_75t_L _172_ (
    .A(_001_),
    .B(_002_),
    .C(_004_),
    .Y(_119_)
  );
  NAND2xp33_ASAP7_75t_L _173_ (
    .A(_087_),
    .B(_100_),
    .Y(_120_)
  );
  NAND3xp33_ASAP7_75t_L _174_ (
    .A(_000_),
    .B(_003_),
    .C(G1),
    .Y(_121_)
  );
  O2A1O1Ixp33_ASAP7_75t_L _175_ (
    .A1(_087_),
    .A2(_096_),
    .B(_120_),
    .C(_121_),
    .Y(G322)
  );
  NOR2xp33_ASAP7_75t_L _176_ (
    .A(G12),
    .B(G11),
    .Y(_005_)
  );
  AOI21xp33_ASAP7_75t_L _177_ (
    .A1(G12),
    .A2(G10),
    .B(G11),
    .Y(_006_)
  );
  NAND5xp2_ASAP7_75t_L _178_ (
    .A(_000_),
    .B(_001_),
    .C(_002_),
    .D(G15),
    .E(_106_),
    .Y(_007_)
  );
  NOR2xp33_ASAP7_75t_L _179_ (
    .A(G12),
    .B(G10),
    .Y(_008_)
  );
  NOR4xp25_ASAP7_75t_L _180_ (
    .A(_111_),
    .B(_006_),
    .C(_007_),
    .D(_008_),
    .Y(G45)
  );
  AND4x1_ASAP7_75t_L _181_ (
    .A(G8),
    .B(G7),
    .C(G6),
    .D(G9),
    .Y(_009_)
  );
  NAND3xp33_ASAP7_75t_L _182_ (
    .A(_084_),
    .B(G15),
    .C(_009_),
    .Y(_010_)
  );
  NAND2xp33_ASAP7_75t_L _183_ (
    .A(G16),
    .B(_010_),
    .Y(_011_)
  );
  NOR2xp33_ASAP7_75t_L _184_ (
    .A(G4),
    .B(_103_),
    .Y(_012_)
  );
  NAND3xp33_ASAP7_75t_L _185_ (
    .A(_102_),
    .B(_011_),
    .C(_012_),
    .Y(_013_)
  );
  INVx1_ASAP7_75t_L _186_ (
    .A(_013_),
    .Y(G292)
  );
  O2A1O1Ixp33_ASAP7_75t_L _187_ (
    .A1(_003_),
    .A2(_004_),
    .B(_085_),
    .C(_107_),
    .Y(_014_)
  );
  OAI32xp33_ASAP7_75t_L _188_ (
    .A1(_000_),
    .A2(_119_),
    .A3(_014_),
    .B1(_007_),
    .B2(_006_),
    .Y(_015_)
  );
  NAND2xp33_ASAP7_75t_L _189_ (
    .A(_110_),
    .B(_015_),
    .Y(_016_)
  );
  NOR2xp33_ASAP7_75t_L _190_ (
    .A(_000_),
    .B(G0),
    .Y(_017_)
  );
  AOI21xp33_ASAP7_75t_L _191_ (
    .A1(_003_),
    .A2(G1),
    .B(_017_),
    .Y(_018_)
  );
  AOI211xp5_ASAP7_75t_L _192_ (
    .A1(_084_),
    .A2(_003_),
    .B(_120_),
    .C(_018_),
    .Y(_019_)
  );
  OAI21xp33_ASAP7_75t_L _193_ (
    .A1(G16),
    .A2(G1),
    .B(_002_),
    .Y(_020_)
  );
  A2O1A1Ixp33_ASAP7_75t_L _194_ (
    .A1(_087_),
    .A2(_089_),
    .B(_000_),
    .C(_020_),
    .Y(_021_)
  );
  AOI31xp33_ASAP7_75t_L _195_ (
    .A1(_084_),
    .A2(_002_),
    .A3(G0),
    .B(_098_),
    .Y(_022_)
  );
  AOI21xp33_ASAP7_75t_L _196_ (
    .A1(_021_),
    .A2(_022_),
    .B(_019_),
    .Y(_023_)
  );
  AOI21xp33_ASAP7_75t_L _197_ (
    .A1(_016_),
    .A2(_023_),
    .B(G18),
    .Y(\DFF_0.D )
  );
  NAND3xp33_ASAP7_75t_L _198_ (
    .A(_084_),
    .B(_003_),
    .C(_090_),
    .Y(_024_)
  );
  OAI31xp33_ASAP7_75t_L _199_ (
    .A1(_000_),
    .A2(_002_),
    .A3(G0),
    .B(_024_),
    .Y(_025_)
  );
  NOR2xp33_ASAP7_75t_L _200_ (
    .A(G1),
    .B(G3),
    .Y(_026_)
  );
  OAI21xp33_ASAP7_75t_L _201_ (
    .A1(_002_),
    .A2(_026_),
    .B(_117_),
    .Y(_027_)
  );
  NOR3xp33_ASAP7_75t_L _202_ (
    .A(_084_),
    .B(_102_),
    .C(_027_),
    .Y(_028_)
  );
  A2O1A1Ixp33_ASAP7_75t_L _203_ (
    .A1(_118_),
    .A2(_025_),
    .B(_028_),
    .C(_100_),
    .Y(_029_)
  );
  NAND5xp2_ASAP7_75t_L _204_ (
    .A(_001_),
    .B(G16),
    .C(_090_),
    .D(G15),
    .E(_106_),
    .Y(_030_)
  );
  A2O1A1Ixp33_ASAP7_75t_L _205_ (
    .A1(G10),
    .A2(_005_),
    .B(_084_),
    .C(_002_),
    .Y(_031_)
  );
  AOI31xp33_ASAP7_75t_L _206_ (
    .A1(_002_),
    .A2(G11),
    .A3(_008_),
    .B(_030_),
    .Y(_032_)
  );
  OAI21xp33_ASAP7_75t_L _207_ (
    .A1(G16),
    .A2(_102_),
    .B(_012_),
    .Y(_033_)
  );
  NAND3xp33_ASAP7_75t_L _208_ (
    .A(_089_),
    .B(G2),
    .C(_026_),
    .Y(_034_)
  );
  NOR2xp33_ASAP7_75t_L _209_ (
    .A(_099_),
    .B(_034_),
    .Y(_035_)
  );
  AOI21xp33_ASAP7_75t_L _210_ (
    .A1(_031_),
    .A2(_032_),
    .B(_035_),
    .Y(_036_)
  );
  AOI31xp33_ASAP7_75t_L _211_ (
    .A1(_029_),
    .A2(_033_),
    .A3(_036_),
    .B(G18),
    .Y(\DFF_1.D )
  );
  OAI21xp33_ASAP7_75t_L _212_ (
    .A1(G11),
    .A2(G10),
    .B(_002_),
    .Y(_037_)
  );
  NAND3xp33_ASAP7_75t_L _213_ (
    .A(G15),
    .B(_106_),
    .C(_037_),
    .Y(_038_)
  );
  NOR2xp33_ASAP7_75t_L _214_ (
    .A(_002_),
    .B(_091_),
    .Y(_039_)
  );
  OAI31xp33_ASAP7_75t_L _215_ (
    .A1(_003_),
    .A2(_002_),
    .A3(_091_),
    .B(_004_),
    .Y(_040_)
  );
  AND4x1_ASAP7_75t_L _216_ (
    .A(_001_),
    .B(_110_),
    .C(_038_),
    .D(_040_),
    .Y(_041_)
  );
  AND3x1_ASAP7_75t_L _217_ (
    .A(G15),
    .B(_093_),
    .C(G53),
    .Y(_042_)
  );
  OAI32xp33_ASAP7_75t_L _218_ (
    .A1(_035_),
    .A2(_041_),
    .A3(_042_),
    .B1(_107_),
    .B2(_000_),
    .Y(_043_)
  );
  AOI31xp33_ASAP7_75t_L _219_ (
    .A1(_013_),
    .A2(_029_),
    .A3(_043_),
    .B(G18),
    .Y(\DFF_2.D )
  );
  AOI211xp5_ASAP7_75t_L _220_ (
    .A1(G15),
    .A2(_093_),
    .B(_095_),
    .C(_003_),
    .Y(_044_)
  );
  NAND4xp25_ASAP7_75t_L _221_ (
    .A(_003_),
    .B(_087_),
    .C(_088_),
    .D(G15),
    .Y(_045_)
  );
  AOI22xp33_ASAP7_75t_L _222_ (
    .A1(_002_),
    .A2(_004_),
    .B1(G16),
    .B2(_045_),
    .Y(_046_)
  );
  NAND2xp33_ASAP7_75t_L _223_ (
    .A(G4),
    .B(_108_),
    .Y(_047_)
  );
  AOI21xp33_ASAP7_75t_L _224_ (
    .A1(G4),
    .A2(_108_),
    .B(_085_),
    .Y(_048_)
  );
  OAI21xp33_ASAP7_75t_L _225_ (
    .A1(_002_),
    .A2(_089_),
    .B(_088_),
    .Y(_049_)
  );
  O2A1O1Ixp33_ASAP7_75t_L _226_ (
    .A1(_003_),
    .A2(G4),
    .B(_001_),
    .C(_049_),
    .Y(_050_)
  );
  A2O1A1Ixp33_ASAP7_75t_L _227_ (
    .A1(_002_),
    .A2(G5),
    .B(_086_),
    .C(_050_),
    .Y(_051_)
  );
  NAND3xp33_ASAP7_75t_L _228_ (
    .A(_003_),
    .B(G2),
    .C(_026_),
    .Y(_052_)
  );
  O2A1O1Ixp33_ASAP7_75t_L _229_ (
    .A1(G16),
    .A2(_096_),
    .B(_120_),
    .C(_052_),
    .Y(_053_)
  );
  O2A1O1Ixp33_ASAP7_75t_L _230_ (
    .A1(_044_),
    .A2(_046_),
    .B(_048_),
    .C(_053_),
    .Y(_054_)
  );
  NAND3xp33_ASAP7_75t_L _231_ (
    .A(G16),
    .B(G15),
    .C(G13),
    .Y(_055_)
  );
  NAND3xp33_ASAP7_75t_L _232_ (
    .A(_001_),
    .B(_090_),
    .C(_055_),
    .Y(_056_)
  );
  OAI31xp33_ASAP7_75t_L _233_ (
    .A1(_000_),
    .A2(_001_),
    .A3(G0),
    .B(_056_),
    .Y(_057_)
  );
  OAI21xp33_ASAP7_75t_L _234_ (
    .A1(_084_),
    .A2(G15),
    .B(_001_),
    .Y(_058_)
  );
  NOR3xp33_ASAP7_75t_L _235_ (
    .A(_003_),
    .B(G4),
    .C(_114_),
    .Y(_059_)
  );
  AND3x1_ASAP7_75t_L _236_ (
    .A(_010_),
    .B(_058_),
    .C(_059_),
    .Y(_060_)
  );
  AOI21xp33_ASAP7_75t_L _237_ (
    .A1(G15),
    .A2(_104_),
    .B(_089_),
    .Y(_061_)
  );
  NOR4xp25_ASAP7_75t_L _238_ (
    .A(G4),
    .B(_102_),
    .C(_103_),
    .D(_061_),
    .Y(_062_)
  );
  AOI211xp5_ASAP7_75t_L _239_ (
    .A1(_107_),
    .A2(_057_),
    .B(_060_),
    .C(_062_),
    .Y(_063_)
  );
  A2O1A1O1Ixp25_ASAP7_75t_L _240_ (
    .A1(_051_),
    .A2(_054_),
    .B(_084_),
    .C(_063_),
    .D(G18),
    .Y(\DFF_3.D )
  );
  NOR2xp33_ASAP7_75t_L _241_ (
    .A(G8),
    .B(G7),
    .Y(_064_)
  );
  NAND5xp2_ASAP7_75t_L _242_ (
    .A(_088_),
    .B(G15),
    .C(G6),
    .D(G9),
    .E(_064_),
    .Y(_065_)
  );
  AOI21xp33_ASAP7_75t_L _243_ (
    .A1(G15),
    .A2(G13),
    .B(_002_),
    .Y(_066_)
  );
  AOI311xp33_ASAP7_75t_L _244_ (
    .A1(_000_),
    .A2(_002_),
    .A3(G15),
    .B(_066_),
    .C(_085_),
    .Y(_067_)
  );
  NAND3xp33_ASAP7_75t_L _245_ (
    .A(_084_),
    .B(_004_),
    .C(_009_),
    .Y(_068_)
  );
  NAND4xp25_ASAP7_75t_L _246_ (
    .A(_085_),
    .B(_086_),
    .C(_004_),
    .D(G15),
    .Y(_069_)
  );
  OAI21xp33_ASAP7_75t_L _247_ (
    .A1(_000_),
    .A2(_001_),
    .B(_106_),
    .Y(_070_)
  );
  AOI21xp33_ASAP7_75t_L _248_ (
    .A1(_069_),
    .A2(_070_),
    .B(_067_),
    .Y(_071_)
  );
  NOR2xp33_ASAP7_75t_L _249_ (
    .A(G1),
    .B(_097_),
    .Y(_072_)
  );
  AOI21xp33_ASAP7_75t_L _250_ (
    .A1(_002_),
    .A2(_065_),
    .B(_039_),
    .Y(_073_)
  );
  OAI211xp5_ASAP7_75t_L _251_ (
    .A1(_072_),
    .A2(_073_),
    .B(_000_),
    .C(_001_),
    .Y(_074_)
  );
  XOR2xp5_ASAP7_75t_L _252_ (
    .A(_002_),
    .B(G15),
    .Y(_075_)
  );
  OAI22xp33_ASAP7_75t_L _253_ (
    .A1(_002_),
    .A2(_098_),
    .B1(_103_),
    .B2(_075_),
    .Y(_076_)
  );
  AOI21xp33_ASAP7_75t_L _254_ (
    .A1(_068_),
    .A2(_071_),
    .B(_076_),
    .Y(_077_)
  );
  AO21x1_ASAP7_75t_L _255_ (
    .A1(_085_),
    .A2(G0),
    .B(_000_),
    .Y(_078_)
  );
  OAI21xp33_ASAP7_75t_L _256_ (
    .A1(_085_),
    .A2(G4),
    .B(_107_),
    .Y(_079_)
  );
  OAI22xp33_ASAP7_75t_L _257_ (
    .A1(_094_),
    .A2(_047_),
    .B1(_078_),
    .B2(_079_),
    .Y(_080_)
  );
  OA21x2_ASAP7_75t_L _258_ (
    .A1(_086_),
    .A2(G2),
    .B(_087_),
    .Y(_081_)
  );
  NOR3xp33_ASAP7_75t_L _259_ (
    .A(_101_),
    .B(_027_),
    .C(_081_),
    .Y(_082_)
  );
  NOR4xp25_ASAP7_75t_L _260_ (
    .A(_112_),
    .B(G298),
    .C(_080_),
    .D(_082_),
    .Y(_083_)
  );
  A2O1A1O1Ixp25_ASAP7_75t_L _261_ (
    .A1(_074_),
    .A2(_077_),
    .B(_089_),
    .C(_083_),
    .D(G18),
    .Y(\DFF_4.D )
  );
  DFFHQNx1_ASAP7_75t_R _262_ (
    .CLK(CK),
    .D(\DFF_1.D ),
    .QN(_001_)
  );
  DFFHQNx1_ASAP7_75t_R _263_ (
    .CLK(CK),
    .D(\DFF_3.D ),
    .QN(_003_)
  );
  DFFHQNx1_ASAP7_75t_R _264_ (
    .CLK(CK),
    .D(\DFF_2.D ),
    .QN(_004_)
  );
  DFFHQNx1_ASAP7_75t_R _265_ (
    .CLK(CK),
    .D(\DFF_0.D ),
    .QN(_000_)
  );
  DFFHQNx1_ASAP7_75t_R _266_ (
    .CLK(CK),
    .D(\DFF_4.D ),
    .QN(_002_)
  );
  assign \DFF_0.CK  = CK;
  assign \DFF_1.CK  = CK;
  assign \DFF_2.CK  = CK;
  assign \DFF_3.CK  = CK;
  assign \DFF_4.CK  = CK;
  assign G102 = \DFF_4.D ;
  assign G229 = G15;
  assign G325 = G310;
  assign G90 = \DFF_0.D ;
  assign G93 = \DFF_1.D ;
  assign G96 = \DFF_2.D ;
  assign G99 = \DFF_3.D ;
endmodule
