/* Generated by Yosys 0.54+29 (git sha1 7b0c1fe49, g++ 9.4.0-1ubuntu1~20.04.2 -fPIC -O3) */

module c17(G1, G16, G17, G2, G3, G4, G5);
  wire _0_;
  input G1;
  wire G1;
  output G16;
  wire G16;
  output G17;
  wire G17;
  input G2;
  wire G2;
  input G3;
  wire G3;
  input G4;
  wire G4;
  input G5;
  wire G5;
  NAND2xp33_ASAP7_75t_L _1_ (
    .A(G3),
    .B(G4),
    .Y(_0_)
  );
  AO22x1_ASAP7_75t_L _2_ (
    .A1(G3),
    .A2(G1),
    .B1(G2),
    .B2(_0_),
    .Y(G16)
  );
  OA21x2_ASAP7_75t_L _3_ (
    .A1(G2),
    .A2(G5),
    .B(_0_),
    .Y(G17)
  );
endmodule
