/* Generated by Yosys 0.54+29 (git sha1 7b0c1fe49, g++ 9.4.0-1ubuntu1~20.04.2 -fPIC -O3) */

module s298(GND, VDD, CK, G0, G1, G117, G118, G132, G133, G2, G66, G67);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  input CK;
  wire CK;
  wire \DFF_0.CK ;
  wire \DFF_0.D ;
  wire \DFF_1.CK ;
  wire \DFF_1.D ;
  wire \DFF_10.CK ;
  wire \DFF_10.D ;
  wire \DFF_10.Q ;
  wire \DFF_11.CK ;
  wire \DFF_11.D ;
  wire \DFF_11.Q ;
  wire \DFF_12.CK ;
  wire \DFF_12.D ;
  wire \DFF_13.CK ;
  wire \DFF_13.D ;
  wire \DFF_2.CK ;
  wire \DFF_2.D ;
  wire \DFF_3.CK ;
  wire \DFF_3.D ;
  wire \DFF_4.CK ;
  wire \DFF_4.D ;
  wire \DFF_5.CK ;
  wire \DFF_5.D ;
  wire \DFF_6.CK ;
  wire \DFF_6.D ;
  wire \DFF_6.Q ;
  wire \DFF_7.CK ;
  wire \DFF_7.D ;
  wire \DFF_7.Q ;
  wire \DFF_8.CK ;
  wire \DFF_8.D ;
  wire \DFF_8.Q ;
  wire \DFF_9.CK ;
  wire \DFF_9.D ;
  wire \DFF_9.Q ;
  input G0;
  wire G0;
  input G1;
  wire G1;
  wire G102;
  wire G107;
  wire G113;
  output G117;
  wire G117;
  output G118;
  wire G118;
  wire G119;
  wire G124;
  wire G125;
  wire G130;
  wire G131;
  output G132;
  wire G132;
  output G133;
  wire G133;
  wire G16;
  wire G17;
  wire G18;
  wire G19;
  input G2;
  wire G2;
  wire G20;
  wire G21;
  wire G29;
  wire G30;
  wire G34;
  wire G39;
  wire G44;
  wire G56;
  output G66;
  wire G66;
  output G67;
  wire G67;
  wire G86;
  wire G92;
  wire G98;
  input GND;
  wire GND;
  input VDD;
  wire VDD;
  INVx1_ASAP7_75t_L _048_ (
    .A(G0),
    .Y(_014_)
  );
  INVx1_ASAP7_75t_L _049_ (
    .A(_001_),
    .Y(_015_)
  );
  INVx1_ASAP7_75t_L _050_ (
    .A(_002_),
    .Y(_016_)
  );
  INVx1_ASAP7_75t_L _051_ (
    .A(_003_),
    .Y(_017_)
  );
  INVx1_ASAP7_75t_L _052_ (
    .A(G2),
    .Y(_018_)
  );
  INVx1_ASAP7_75t_L _053_ (
    .A(G1),
    .Y(_019_)
  );
  INVx1_ASAP7_75t_L _054_ (
    .A(_004_),
    .Y(_020_)
  );
  INVx1_ASAP7_75t_L _055_ (
    .A(_005_),
    .Y(G117)
  );
  INVx1_ASAP7_75t_L _056_ (
    .A(_006_),
    .Y(G66)
  );
  INVx1_ASAP7_75t_L _057_ (
    .A(_007_),
    .Y(G67)
  );
  INVx1_ASAP7_75t_L _058_ (
    .A(_008_),
    .Y(_021_)
  );
  INVx1_ASAP7_75t_L _059_ (
    .A(_009_),
    .Y(G132)
  );
  INVx1_ASAP7_75t_L _060_ (
    .A(_010_),
    .Y(G118)
  );
  INVx1_ASAP7_75t_L _061_ (
    .A(_011_),
    .Y(G133)
  );
  NOR2xp33_ASAP7_75t_L _062_ (
    .A(G0),
    .B(_016_),
    .Y(\DFF_0.D )
  );
  NAND2xp33_ASAP7_75t_L _063_ (
    .A(_001_),
    .B(_004_),
    .Y(_022_)
  );
  OAI211xp5_ASAP7_75t_L _064_ (
    .A1(_000_),
    .A2(_015_),
    .B(_016_),
    .C(_004_),
    .Y(_023_)
  );
  O2A1O1Ixp33_ASAP7_75t_L _065_ (
    .A1(_016_),
    .A2(_004_),
    .B(_023_),
    .C(G0),
    .Y(\DFF_1.D )
  );
  NOR3xp33_ASAP7_75t_L _066_ (
    .A(_001_),
    .B(_002_),
    .C(_004_),
    .Y(_024_)
  );
  AOI21xp33_ASAP7_75t_L _067_ (
    .A1(_016_),
    .A2(_020_),
    .B(_015_),
    .Y(_025_)
  );
  NOR3xp33_ASAP7_75t_L _068_ (
    .A(G0),
    .B(_024_),
    .C(_025_),
    .Y(\DFF_2.D )
  );
  XOR2xp5_ASAP7_75t_L _069_ (
    .A(_000_),
    .B(_024_),
    .Y(_026_)
  );
  AOI311xp33_ASAP7_75t_L _070_ (
    .A1(_001_),
    .A2(_016_),
    .A3(_004_),
    .B(_026_),
    .C(G0),
    .Y(\DFF_3.D )
  );
  OAI31xp33_ASAP7_75t_L _071_ (
    .A1(_000_),
    .A2(_002_),
    .A3(_022_),
    .B(_012_),
    .Y(_027_)
  );
  AOI21xp33_ASAP7_75t_L _072_ (
    .A1(_017_),
    .A2(_027_),
    .B(G0),
    .Y(_028_)
  );
  OA21x2_ASAP7_75t_L _073_ (
    .A1(_017_),
    .A2(_027_),
    .B(_028_),
    .Y(\DFF_4.D )
  );
  NOR2xp33_ASAP7_75t_L _074_ (
    .A(_000_),
    .B(_017_),
    .Y(_029_)
  );
  OR4x1_ASAP7_75t_L _075_ (
    .A(_000_),
    .B(_017_),
    .C(_013_),
    .D(_022_),
    .Y(_030_)
  );
  NOR2xp33_ASAP7_75t_L _076_ (
    .A(_015_),
    .B(_004_),
    .Y(_031_)
  );
  AO32x1_ASAP7_75t_L _077_ (
    .A1(_013_),
    .A2(_029_),
    .A3(_031_),
    .B1(_030_),
    .B2(_008_),
    .Y(_032_)
  );
  NOR2xp33_ASAP7_75t_L _078_ (
    .A(G0),
    .B(_032_),
    .Y(\DFF_5.D )
  );
  OAI21xp33_ASAP7_75t_L _079_ (
    .A1(_001_),
    .A2(_003_),
    .B(_000_),
    .Y(_033_)
  );
  OA211x2_ASAP7_75t_L _080_ (
    .A1(_003_),
    .A2(G66),
    .B(_032_),
    .C(_033_),
    .Y(\DFF_6.D )
  );
  OAI21xp33_ASAP7_75t_L _081_ (
    .A1(_003_),
    .A2(_022_),
    .B(_000_),
    .Y(_034_)
  );
  OAI21xp33_ASAP7_75t_L _082_ (
    .A1(_000_),
    .A2(_003_),
    .B(_034_),
    .Y(_035_)
  );
  AOI32xp33_ASAP7_75t_L _083_ (
    .A1(_015_),
    .A2(_003_),
    .A3(_020_),
    .B1(_007_),
    .B2(_033_),
    .Y(_036_)
  );
  AND3x1_ASAP7_75t_L _084_ (
    .A(_032_),
    .B(_035_),
    .C(_036_),
    .Y(\DFF_7.D )
  );
  NAND2xp33_ASAP7_75t_L _085_ (
    .A(_005_),
    .B(_033_),
    .Y(_037_)
  );
  AND3x1_ASAP7_75t_L _086_ (
    .A(_032_),
    .B(_035_),
    .C(_037_),
    .Y(\DFF_8.D )
  );
  AOI31xp33_ASAP7_75t_L _087_ (
    .A1(_015_),
    .A2(_017_),
    .A3(G118),
    .B(_034_),
    .Y(_038_)
  );
  AOI321xp33_ASAP7_75t_L _088_ (
    .A1(_013_),
    .A2(_029_),
    .A3(_031_),
    .B1(_030_),
    .B2(_008_),
    .C(_002_),
    .Y(_039_)
  );
  NOR4xp25_ASAP7_75t_L _089_ (
    .A(_000_),
    .B(_003_),
    .C(_021_),
    .D(G118),
    .Y(_040_)
  );
  AOI211xp5_ASAP7_75t_L _090_ (
    .A1(_032_),
    .A2(_038_),
    .B(_039_),
    .C(_040_),
    .Y(\DFF_9.D )
  );
  NAND2xp33_ASAP7_75t_L _091_ (
    .A(_000_),
    .B(_001_),
    .Y(_041_)
  );
  NAND2xp33_ASAP7_75t_L _092_ (
    .A(_009_),
    .B(_041_),
    .Y(_042_)
  );
  OAI21xp33_ASAP7_75t_L _093_ (
    .A1(_004_),
    .A2(_041_),
    .B(_042_),
    .Y(_043_)
  );
  O2A1O1Ixp33_ASAP7_75t_L _094_ (
    .A1(_003_),
    .A2(_043_),
    .B(_032_),
    .C(_039_),
    .Y(\DFF_10.D )
  );
  NOR2xp33_ASAP7_75t_L _095_ (
    .A(_003_),
    .B(_011_),
    .Y(_044_)
  );
  A2O1A1Ixp33_ASAP7_75t_L _096_ (
    .A1(_003_),
    .A2(_020_),
    .B(_044_),
    .C(_041_),
    .Y(_045_)
  );
  NOR3xp33_ASAP7_75t_L _097_ (
    .A(_021_),
    .B(_029_),
    .C(_045_),
    .Y(\DFF_11.D )
  );
  OAI21xp33_ASAP7_75t_L _098_ (
    .A1(_018_),
    .A2(_013_),
    .B(_014_),
    .Y(_046_)
  );
  AOI21xp33_ASAP7_75t_L _099_ (
    .A1(_018_),
    .A2(_013_),
    .B(_046_),
    .Y(\DFF_12.D )
  );
  OAI21xp33_ASAP7_75t_L _100_ (
    .A1(_019_),
    .A2(_012_),
    .B(_014_),
    .Y(_047_)
  );
  AOI21xp33_ASAP7_75t_L _101_ (
    .A1(_019_),
    .A2(_012_),
    .B(_047_),
    .Y(\DFF_13.D )
  );
  DFFHQNx1_ASAP7_75t_R _102_ (
    .CLK(CK),
    .D(\DFF_2.D ),
    .QN(_001_)
  );
  DFFHQNx1_ASAP7_75t_R _103_ (
    .CLK(CK),
    .D(\DFF_4.D ),
    .QN(_003_)
  );
  DFFHQNx1_ASAP7_75t_R _104_ (
    .CLK(CK),
    .D(\DFF_1.D ),
    .QN(_004_)
  );
  DFFHQNx1_ASAP7_75t_R _105_ (
    .CLK(CK),
    .D(\DFF_3.D ),
    .QN(_000_)
  );
  DFFHQNx1_ASAP7_75t_R _106_ (
    .CLK(CK),
    .D(\DFF_8.D ),
    .QN(_005_)
  );
  DFFHQNx1_ASAP7_75t_R _107_ (
    .CLK(CK),
    .D(\DFF_6.D ),
    .QN(_006_)
  );
  DFFHQNx1_ASAP7_75t_R _108_ (
    .CLK(CK),
    .D(\DFF_7.D ),
    .QN(_007_)
  );
  DFFHQNx1_ASAP7_75t_R _109_ (
    .CLK(CK),
    .D(\DFF_5.D ),
    .QN(_008_)
  );
  DFFHQNx1_ASAP7_75t_R _110_ (
    .CLK(CK),
    .D(\DFF_10.D ),
    .QN(_009_)
  );
  DFFHQNx1_ASAP7_75t_R _111_ (
    .CLK(CK),
    .D(\DFF_9.D ),
    .QN(_010_)
  );
  DFFHQNx1_ASAP7_75t_R _112_ (
    .CLK(CK),
    .D(\DFF_11.D ),
    .QN(_011_)
  );
  DFFHQNx1_ASAP7_75t_R _113_ (
    .CLK(CK),
    .D(\DFF_13.D ),
    .QN(_012_)
  );
  DFFHQNx1_ASAP7_75t_R _114_ (
    .CLK(CK),
    .D(\DFF_12.D ),
    .QN(_013_)
  );
  DFFHQNx1_ASAP7_75t_R _115_ (
    .CLK(CK),
    .D(\DFF_0.D ),
    .QN(_002_)
  );
  assign \DFF_0.CK  = CK;
  assign \DFF_1.CK  = CK;
  assign \DFF_10.CK  = CK;
  assign \DFF_10.Q  = G132;
  assign \DFF_11.CK  = CK;
  assign \DFF_11.Q  = G133;
  assign \DFF_12.CK  = CK;
  assign \DFF_13.CK  = CK;
  assign \DFF_2.CK  = CK;
  assign \DFF_3.CK  = CK;
  assign \DFF_4.CK  = CK;
  assign \DFF_5.CK  = CK;
  assign \DFF_6.CK  = CK;
  assign \DFF_6.Q  = G66;
  assign \DFF_7.CK  = CK;
  assign \DFF_7.Q  = G67;
  assign \DFF_8.CK  = CK;
  assign \DFF_8.Q  = G117;
  assign \DFF_9.CK  = CK;
  assign \DFF_9.Q  = G118;
  assign G102 = \DFF_9.D ;
  assign G107 = \DFF_10.D ;
  assign G113 = \DFF_11.D ;
  assign G119 = \DFF_12.D ;
  assign G124 = G2;
  assign G125 = \DFF_13.D ;
  assign G130 = G0;
  assign G131 = G1;
  assign G16 = G66;
  assign G17 = G67;
  assign G18 = G117;
  assign G19 = G118;
  assign G20 = G132;
  assign G21 = G133;
  assign G29 = \DFF_0.D ;
  assign G30 = \DFF_1.D ;
  assign G34 = \DFF_2.D ;
  assign G39 = \DFF_3.D ;
  assign G44 = \DFF_4.D ;
  assign G56 = \DFF_5.D ;
  assign G86 = \DFF_6.D ;
  assign G92 = \DFF_7.D ;
  assign G98 = \DFF_8.D ;
endmodule
