UCLA scl 1.0

NumRows : 82

CoreRow Horizontal
  Coordinate   : 95
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : 0
  Sitesymmetry : 1
  SubrowOrigin : 93  NumSites : 415
End
CoreRow Horizontal
  Coordinate   : 100
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : MX
  Sitesymmetry : 1
  SubrowOrigin : 93  NumSites : 415
End
CoreRow Horizontal
  Coordinate   : 105
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : 0
  Sitesymmetry : 1
  SubrowOrigin : 93  NumSites : 415
End
CoreRow Horizontal
  Coordinate   : 110
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : MX
  Sitesymmetry : 1
  SubrowOrigin : 93  NumSites : 415
End
CoreRow Horizontal
  Coordinate   : 115
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : 0
  Sitesymmetry : 1
  SubrowOrigin : 93  NumSites : 415
End
CoreRow Horizontal
  Coordinate   : 120
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : MX
  Sitesymmetry : 1
  SubrowOrigin : 93  NumSites : 415
End
CoreRow Horizontal
  Coordinate   : 125
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : 0
  Sitesymmetry : 1
  SubrowOrigin : 93  NumSites : 415
End
CoreRow Horizontal
  Coordinate   : 130
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : MX
  Sitesymmetry : 1
  SubrowOrigin : 93  NumSites : 415
End
CoreRow Horizontal
  Coordinate   : 135
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : 0
  Sitesymmetry : 1
  SubrowOrigin : 93  NumSites : 415
End
CoreRow Horizontal
  Coordinate   : 140
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : MX
  Sitesymmetry : 1
  SubrowOrigin : 93  NumSites : 415
End
CoreRow Horizontal
  Coordinate   : 145
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : 0
  Sitesymmetry : 1
  SubrowOrigin : 93  NumSites : 415
End
CoreRow Horizontal
  Coordinate   : 150
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : MX
  Sitesymmetry : 1
  SubrowOrigin : 93  NumSites : 415
End
CoreRow Horizontal
  Coordinate   : 155
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : 0
  Sitesymmetry : 1
  SubrowOrigin : 93  NumSites : 415
End
CoreRow Horizontal
  Coordinate   : 160
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : MX
  Sitesymmetry : 1
  SubrowOrigin : 93  NumSites : 415
End
CoreRow Horizontal
  Coordinate   : 165
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : 0
  Sitesymmetry : 1
  SubrowOrigin : 93  NumSites : 415
End
CoreRow Horizontal
  Coordinate   : 170
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : MX
  Sitesymmetry : 1
  SubrowOrigin : 93  NumSites : 415
End
CoreRow Horizontal
  Coordinate   : 175
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : 0
  Sitesymmetry : 1
  SubrowOrigin : 93  NumSites : 415
End
CoreRow Horizontal
  Coordinate   : 180
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : MX
  Sitesymmetry : 1
  SubrowOrigin : 93  NumSites : 415
End
CoreRow Horizontal
  Coordinate   : 185
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : 0
  Sitesymmetry : 1
  SubrowOrigin : 93  NumSites : 415
End
CoreRow Horizontal
  Coordinate   : 190
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : MX
  Sitesymmetry : 1
  SubrowOrigin : 93  NumSites : 415
End
CoreRow Horizontal
  Coordinate   : 195
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : 0
  Sitesymmetry : 1
  SubrowOrigin : 93  NumSites : 415
End
CoreRow Horizontal
  Coordinate   : 200
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : MX
  Sitesymmetry : 1
  SubrowOrigin : 93  NumSites : 415
End
CoreRow Horizontal
  Coordinate   : 205
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : 0
  Sitesymmetry : 1
  SubrowOrigin : 93  NumSites : 415
End
CoreRow Horizontal
  Coordinate   : 210
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : MX
  Sitesymmetry : 1
  SubrowOrigin : 93  NumSites : 415
End
CoreRow Horizontal
  Coordinate   : 215
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : 0
  Sitesymmetry : 1
  SubrowOrigin : 93  NumSites : 415
End
CoreRow Horizontal
  Coordinate   : 220
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : MX
  Sitesymmetry : 1
  SubrowOrigin : 93  NumSites : 415
End
CoreRow Horizontal
  Coordinate   : 225
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : 0
  Sitesymmetry : 1
  SubrowOrigin : 93  NumSites : 415
End
CoreRow Horizontal
  Coordinate   : 230
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : MX
  Sitesymmetry : 1
  SubrowOrigin : 93  NumSites : 415
End
CoreRow Horizontal
  Coordinate   : 235
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : 0
  Sitesymmetry : 1
  SubrowOrigin : 93  NumSites : 415
End
CoreRow Horizontal
  Coordinate   : 240
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : MX
  Sitesymmetry : 1
  SubrowOrigin : 93  NumSites : 415
End
CoreRow Horizontal
  Coordinate   : 245
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : 0
  Sitesymmetry : 1
  SubrowOrigin : 93  NumSites : 415
End
CoreRow Horizontal
  Coordinate   : 250
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : MX
  Sitesymmetry : 1
  SubrowOrigin : 93  NumSites : 415
End
CoreRow Horizontal
  Coordinate   : 255
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : 0
  Sitesymmetry : 1
  SubrowOrigin : 93  NumSites : 415
End
CoreRow Horizontal
  Coordinate   : 260
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : MX
  Sitesymmetry : 1
  SubrowOrigin : 93  NumSites : 415
End
CoreRow Horizontal
  Coordinate   : 265
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : 0
  Sitesymmetry : 1
  SubrowOrigin : 93  NumSites : 415
End
CoreRow Horizontal
  Coordinate   : 270
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : MX
  Sitesymmetry : 1
  SubrowOrigin : 93  NumSites : 415
End
CoreRow Horizontal
  Coordinate   : 275
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : 0
  Sitesymmetry : 1
  SubrowOrigin : 93  NumSites : 415
End
CoreRow Horizontal
  Coordinate   : 280
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : MX
  Sitesymmetry : 1
  SubrowOrigin : 93  NumSites : 415
End
CoreRow Horizontal
  Coordinate   : 285
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : 0
  Sitesymmetry : 1
  SubrowOrigin : 93  NumSites : 415
End
CoreRow Horizontal
  Coordinate   : 290
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : MX
  Sitesymmetry : 1
  SubrowOrigin : 93  NumSites : 415
End
CoreRow Horizontal
  Coordinate   : 295
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : 0
  Sitesymmetry : 1
  SubrowOrigin : 93  NumSites : 415
End
CoreRow Horizontal
  Coordinate   : 300
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : MX
  Sitesymmetry : 1
  SubrowOrigin : 93  NumSites : 415
End
CoreRow Horizontal
  Coordinate   : 305
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : 0
  Sitesymmetry : 1
  SubrowOrigin : 93  NumSites : 415
End
CoreRow Horizontal
  Coordinate   : 310
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : MX
  Sitesymmetry : 1
  SubrowOrigin : 93  NumSites : 415
End
CoreRow Horizontal
  Coordinate   : 315
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : 0
  Sitesymmetry : 1
  SubrowOrigin : 93  NumSites : 415
End
CoreRow Horizontal
  Coordinate   : 320
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : MX
  Sitesymmetry : 1
  SubrowOrigin : 93  NumSites : 415
End
CoreRow Horizontal
  Coordinate   : 325
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : 0
  Sitesymmetry : 1
  SubrowOrigin : 93  NumSites : 415
End
CoreRow Horizontal
  Coordinate   : 330
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : MX
  Sitesymmetry : 1
  SubrowOrigin : 93  NumSites : 415
End
CoreRow Horizontal
  Coordinate   : 335
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : 0
  Sitesymmetry : 1
  SubrowOrigin : 93  NumSites : 415
End
CoreRow Horizontal
  Coordinate   : 340
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : MX
  Sitesymmetry : 1
  SubrowOrigin : 93  NumSites : 415
End
CoreRow Horizontal
  Coordinate   : 345
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : 0
  Sitesymmetry : 1
  SubrowOrigin : 93  NumSites : 415
End
CoreRow Horizontal
  Coordinate   : 350
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : MX
  Sitesymmetry : 1
  SubrowOrigin : 93  NumSites : 415
End
CoreRow Horizontal
  Coordinate   : 355
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : 0
  Sitesymmetry : 1
  SubrowOrigin : 93  NumSites : 415
End
CoreRow Horizontal
  Coordinate   : 360
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : MX
  Sitesymmetry : 1
  SubrowOrigin : 93  NumSites : 415
End
CoreRow Horizontal
  Coordinate   : 365
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : 0
  Sitesymmetry : 1
  SubrowOrigin : 93  NumSites : 415
End
CoreRow Horizontal
  Coordinate   : 370
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : MX
  Sitesymmetry : 1
  SubrowOrigin : 93  NumSites : 415
End
CoreRow Horizontal
  Coordinate   : 375
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : 0
  Sitesymmetry : 1
  SubrowOrigin : 93  NumSites : 415
End
CoreRow Horizontal
  Coordinate   : 380
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : MX
  Sitesymmetry : 1
  SubrowOrigin : 93  NumSites : 415
End
CoreRow Horizontal
  Coordinate   : 385
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : 0
  Sitesymmetry : 1
  SubrowOrigin : 93  NumSites : 415
End
CoreRow Horizontal
  Coordinate   : 390
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : MX
  Sitesymmetry : 1
  SubrowOrigin : 93  NumSites : 415
End
CoreRow Horizontal
  Coordinate   : 395
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : 0
  Sitesymmetry : 1
  SubrowOrigin : 93  NumSites : 415
End
CoreRow Horizontal
  Coordinate   : 400
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : MX
  Sitesymmetry : 1
  SubrowOrigin : 93  NumSites : 415
End
CoreRow Horizontal
  Coordinate   : 405
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : 0
  Sitesymmetry : 1
  SubrowOrigin : 93  NumSites : 415
End
CoreRow Horizontal
  Coordinate   : 410
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : MX
  Sitesymmetry : 1
  SubrowOrigin : 93  NumSites : 415
End
CoreRow Horizontal
  Coordinate   : 415
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : 0
  Sitesymmetry : 1
  SubrowOrigin : 93  NumSites : 415
End
CoreRow Horizontal
  Coordinate   : 420
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : MX
  Sitesymmetry : 1
  SubrowOrigin : 93  NumSites : 415
End
CoreRow Horizontal
  Coordinate   : 425
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : 0
  Sitesymmetry : 1
  SubrowOrigin : 93  NumSites : 415
End
CoreRow Horizontal
  Coordinate   : 430
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : MX
  Sitesymmetry : 1
  SubrowOrigin : 93  NumSites : 415
End
CoreRow Horizontal
  Coordinate   : 435
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : 0
  Sitesymmetry : 1
  SubrowOrigin : 93  NumSites : 415
End
CoreRow Horizontal
  Coordinate   : 440
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : MX
  Sitesymmetry : 1
  SubrowOrigin : 93  NumSites : 415
End
CoreRow Horizontal
  Coordinate   : 445
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : 0
  Sitesymmetry : 1
  SubrowOrigin : 93  NumSites : 415
End
CoreRow Horizontal
  Coordinate   : 450
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : MX
  Sitesymmetry : 1
  SubrowOrigin : 93  NumSites : 415
End
CoreRow Horizontal
  Coordinate   : 455
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : 0
  Sitesymmetry : 1
  SubrowOrigin : 93  NumSites : 415
End
CoreRow Horizontal
  Coordinate   : 460
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : MX
  Sitesymmetry : 1
  SubrowOrigin : 93  NumSites : 415
End
CoreRow Horizontal
  Coordinate   : 465
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : 0
  Sitesymmetry : 1
  SubrowOrigin : 93  NumSites : 415
End
CoreRow Horizontal
  Coordinate   : 470
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : MX
  Sitesymmetry : 1
  SubrowOrigin : 93  NumSites : 415
End
CoreRow Horizontal
  Coordinate   : 475
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : 0
  Sitesymmetry : 1
  SubrowOrigin : 93  NumSites : 415
End
CoreRow Horizontal
  Coordinate   : 480
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : MX
  Sitesymmetry : 1
  SubrowOrigin : 93  NumSites : 415
End
CoreRow Horizontal
  Coordinate   : 485
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : 0
  Sitesymmetry : 1
  SubrowOrigin : 93  NumSites : 415
End
CoreRow Horizontal
  Coordinate   : 490
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : MX
  Sitesymmetry : 1
  SubrowOrigin : 93  NumSites : 415
End
CoreRow Horizontal
  Coordinate   : 495
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : 0
  Sitesymmetry : 1
  SubrowOrigin : 93  NumSites : 415
End
CoreRow Horizontal
  Coordinate   : 500
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : MX
  Sitesymmetry : 1
  SubrowOrigin : 93  NumSites : 415
End
