/* Generated by Yosys 0.54+29 (git sha1 7b0c1fe49, g++ 9.4.0-1ubuntu1~20.04.2 -fPIC -O3) */

module c880(G1, G10, G11, G12, G13, G14, G15, G16, G17, G18, G19, G2, G20, G21, G22, G23, G24, G25, G26, G27, G28
, G29, G3, G30, G31, G32, G33, G34, G35, G36, G37, G38, G39, G4, G40, G41, G42, G43, G44, G45, G46, G47
, G48, G49, G5, G50, G51, G52, G53, G54, G55, G56, G57, G58, G59, G6, G60, G7, G8, G855, G856, G857, G858
, G859, G860, G861, G862, G863, G864, G865, G866, G867, G868, G869, G870, G871, G872, G873, G874, G875, G876, G877, G878, G879
, G880, G9);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  input G1;
  wire G1;
  input G10;
  wire G10;
  input G11;
  wire G11;
  input G12;
  wire G12;
  input G13;
  wire G13;
  input G14;
  wire G14;
  input G15;
  wire G15;
  input G16;
  wire G16;
  input G17;
  wire G17;
  input G18;
  wire G18;
  input G19;
  wire G19;
  input G2;
  wire G2;
  input G20;
  wire G20;
  input G21;
  wire G21;
  input G22;
  wire G22;
  input G23;
  wire G23;
  input G24;
  wire G24;
  input G25;
  wire G25;
  input G26;
  wire G26;
  input G27;
  wire G27;
  input G28;
  wire G28;
  input G29;
  wire G29;
  wire G293;
  wire G295;
  wire G296;
  input G3;
  wire G3;
  input G30;
  wire G30;
  input G31;
  wire G31;
  input G32;
  wire G32;
  input G33;
  wire G33;
  input G34;
  wire G34;
  wire G343;
  wire G349;
  input G35;
  wire G35;
  wire G350;
  input G36;
  wire G36;
  wire G369;
  input G37;
  wire G37;
  input G38;
  wire G38;
  input G39;
  wire G39;
  input G4;
  wire G4;
  input G40;
  wire G40;
  input G41;
  wire G41;
  input G42;
  wire G42;
  input G43;
  wire G43;
  input G44;
  wire G44;
  input G45;
  wire G45;
  input G46;
  wire G46;
  input G47;
  wire G47;
  input G48;
  wire G48;
  input G49;
  wire G49;
  input G5;
  wire G5;
  input G50;
  wire G50;
  input G51;
  wire G51;
  input G52;
  wire G52;
  input G53;
  wire G53;
  input G54;
  wire G54;
  input G55;
  wire G55;
  input G56;
  wire G56;
  input G57;
  wire G57;
  input G58;
  wire G58;
  input G59;
  wire G59;
  input G6;
  wire G6;
  input G60;
  wire G60;
  input G7;
  wire G7;
  input G8;
  wire G8;
  wire G812;
  wire G829;
  wire G830;
  wire G831;
  wire G832;
  wire G844;
  wire G849;
  wire G850;
  wire G851;
  output G855;
  wire G855;
  output G856;
  wire G856;
  output G857;
  wire G857;
  output G858;
  wire G858;
  output G859;
  wire G859;
  output G860;
  wire G860;
  output G861;
  wire G861;
  output G862;
  wire G862;
  output G863;
  wire G863;
  output G864;
  wire G864;
  output G865;
  wire G865;
  output G866;
  wire G866;
  output G867;
  wire G867;
  output G868;
  wire G868;
  output G869;
  wire G869;
  output G870;
  wire G870;
  output G871;
  wire G871;
  output G872;
  wire G872;
  output G873;
  wire G873;
  output G874;
  wire G874;
  output G875;
  wire G875;
  output G876;
  wire G876;
  output G877;
  wire G877;
  output G878;
  wire G878;
  output G879;
  wire G879;
  output G880;
  wire G880;
  input G9;
  wire G9;
  INVx1_ASAP7_75t_L _116_ (
    .A(G4),
    .Y(_108_)
  );
  INVx1_ASAP7_75t_L _117_ (
    .A(G10),
    .Y(_109_)
  );
  INVx1_ASAP7_75t_L _118_ (
    .A(G48),
    .Y(_110_)
  );
  INVx1_ASAP7_75t_L _119_ (
    .A(G47),
    .Y(_111_)
  );
  INVx1_ASAP7_75t_L _120_ (
    .A(G58),
    .Y(_112_)
  );
  INVx1_ASAP7_75t_L _121_ (
    .A(G51),
    .Y(_113_)
  );
  INVx1_ASAP7_75t_L _122_ (
    .A(G52),
    .Y(_114_)
  );
  INVx1_ASAP7_75t_L _123_ (
    .A(G53),
    .Y(_115_)
  );
  NAND3xp33_ASAP7_75t_L _124_ (
    .A(G8),
    .B(G7),
    .C(G6),
    .Y(G857)
  );
  NAND3xp33_ASAP7_75t_L _125_ (
    .A(G8),
    .B(G6),
    .C(G16),
    .Y(G855)
  );
  NAND3xp33_ASAP7_75t_L _126_ (
    .A(G7),
    .B(G6),
    .C(G17),
    .Y(G856)
  );
  NAND2xp33_ASAP7_75t_L _127_ (
    .A(G19),
    .B(G18),
    .Y(G858)
  );
  NAND4xp25_ASAP7_75t_L _128_ (
    .A(G4),
    .B(G3),
    .C(G2),
    .D(G1),
    .Y(G859)
  );
  NAND4xp25_ASAP7_75t_L _129_ (
    .A(G4),
    .B(G3),
    .C(G1),
    .D(G5),
    .Y(_000_)
  );
  AOI31xp33_ASAP7_75t_L _130_ (
    .A1(G8),
    .A2(G7),
    .A3(G6),
    .B(_000_),
    .Y(G860)
  );
  OAI21xp33_ASAP7_75t_L _131_ (
    .A1(G21),
    .A2(G20),
    .B(G23),
    .Y(G864)
  );
  NOR2xp33_ASAP7_75t_L _132_ (
    .A(G857),
    .B(_000_),
    .Y(G865)
  );
  NAND3xp33_ASAP7_75t_L _133_ (
    .A(G1),
    .B(G5),
    .C(G9),
    .Y(G866)
  );
  OAI21xp33_ASAP7_75t_L _134_ (
    .A1(G21),
    .A2(G20),
    .B(G22),
    .Y(G869)
  );
  AND3x1_ASAP7_75t_L _135_ (
    .A(G16),
    .B(G17),
    .C(G11),
    .Y(G861)
  );
  AND3x1_ASAP7_75t_L _136_ (
    .A(G7),
    .B(G17),
    .C(G11),
    .Y(G862)
  );
  AND3x1_ASAP7_75t_L _137_ (
    .A(G8),
    .B(G7),
    .C(G11),
    .Y(G863)
  );
  AND4x1_ASAP7_75t_L _138_ (
    .A(G3),
    .B(G2),
    .C(G1),
    .D(G10),
    .Y(_001_)
  );
  NAND3xp33_ASAP7_75t_L _139_ (
    .A(G6),
    .B(G12),
    .C(_001_),
    .Y(G867)
  );
  NAND4xp25_ASAP7_75t_L _140_ (
    .A(G11),
    .B(G12),
    .C(G15),
    .D(_001_),
    .Y(G868)
  );
  XOR2xp5_ASAP7_75t_L _141_ (
    .A(G27),
    .B(G26),
    .Y(_002_)
  );
  XNOR2xp5_ASAP7_75t_L _142_ (
    .A(G32),
    .B(_002_),
    .Y(_003_)
  );
  XNOR2xp5_ASAP7_75t_L _143_ (
    .A(G25),
    .B(G24),
    .Y(_004_)
  );
  XNOR2xp5_ASAP7_75t_L _144_ (
    .A(G29),
    .B(G28),
    .Y(_005_)
  );
  XNOR2xp5_ASAP7_75t_L _145_ (
    .A(_004_),
    .B(_005_),
    .Y(_006_)
  );
  XOR2xp5_ASAP7_75t_L _146_ (
    .A(G30),
    .B(G33),
    .Y(_007_)
  );
  XNOR2xp5_ASAP7_75t_L _147_ (
    .A(G31),
    .B(_007_),
    .Y(_008_)
  );
  XNOR2xp5_ASAP7_75t_L _148_ (
    .A(_006_),
    .B(_008_),
    .Y(_009_)
  );
  XNOR2xp5_ASAP7_75t_L _149_ (
    .A(_003_),
    .B(_009_),
    .Y(G870)
  );
  XOR2xp5_ASAP7_75t_L _150_ (
    .A(G44),
    .B(G43),
    .Y(_010_)
  );
  XNOR2xp5_ASAP7_75t_L _151_ (
    .A(G32),
    .B(_010_),
    .Y(_011_)
  );
  XNOR2xp5_ASAP7_75t_L _152_ (
    .A(G42),
    .B(G41),
    .Y(_012_)
  );
  XNOR2xp5_ASAP7_75t_L _153_ (
    .A(G46),
    .B(G45),
    .Y(_013_)
  );
  XNOR2xp5_ASAP7_75t_L _154_ (
    .A(_012_),
    .B(_013_),
    .Y(_014_)
  );
  XOR2xp5_ASAP7_75t_L _155_ (
    .A(G47),
    .B(G49),
    .Y(_015_)
  );
  XNOR2xp5_ASAP7_75t_L _156_ (
    .A(G48),
    .B(_015_),
    .Y(_016_)
  );
  XNOR2xp5_ASAP7_75t_L _157_ (
    .A(_014_),
    .B(_016_),
    .Y(_017_)
  );
  XNOR2xp5_ASAP7_75t_L _158_ (
    .A(_011_),
    .B(_017_),
    .Y(G871)
  );
  NAND4xp25_ASAP7_75t_L _159_ (
    .A(G4),
    .B(G2),
    .C(G1),
    .D(G9),
    .Y(_018_)
  );
  AOI31xp33_ASAP7_75t_L _160_ (
    .A1(G8),
    .A2(G16),
    .A3(G11),
    .B(_018_),
    .Y(_019_)
  );
  AND2x2_ASAP7_75t_L _161_ (
    .A(G11),
    .B(G40),
    .Y(_020_)
  );
  OAI211xp5_ASAP7_75t_L _162_ (
    .A1(G8),
    .A2(G4),
    .B(G11),
    .C(G40),
    .Y(_021_)
  );
  AOI211xp5_ASAP7_75t_L _163_ (
    .A1(G8),
    .A2(G4),
    .B(G866),
    .C(_021_),
    .Y(_022_)
  );
  OR2x2_ASAP7_75t_L _164_ (
    .A(_019_),
    .B(_022_),
    .Y(_023_)
  );
  OAI21xp33_ASAP7_75t_L _165_ (
    .A1(_019_),
    .A2(_022_),
    .B(G31),
    .Y(_024_)
  );
  OAI31xp33_ASAP7_75t_L _166_ (
    .A1(_108_),
    .A2(G866),
    .A3(_020_),
    .B(G1),
    .Y(_025_)
  );
  NAND3xp33_ASAP7_75t_L _167_ (
    .A(G6),
    .B(G16),
    .C(G17),
    .Y(_026_)
  );
  NOR4xp25_ASAP7_75t_L _168_ (
    .A(_109_),
    .B(G60),
    .C(G866),
    .D(_026_),
    .Y(_027_)
  );
  AOI21xp33_ASAP7_75t_L _169_ (
    .A1(G39),
    .A2(_025_),
    .B(_027_),
    .Y(_028_)
  );
  NAND2xp33_ASAP7_75t_L _170_ (
    .A(_024_),
    .B(_028_),
    .Y(_029_)
  );
  NAND3xp33_ASAP7_75t_L _171_ (
    .A(_110_),
    .B(_024_),
    .C(_028_),
    .Y(_030_)
  );
  XNOR2xp5_ASAP7_75t_L _172_ (
    .A(_110_),
    .B(_029_),
    .Y(_031_)
  );
  AOI21xp33_ASAP7_75t_L _173_ (
    .A1(G58),
    .A2(_031_),
    .B(_113_),
    .Y(_032_)
  );
  NAND2xp33_ASAP7_75t_L _174_ (
    .A(G52),
    .B(_031_),
    .Y(_033_)
  );
  AND4x1_ASAP7_75t_L _175_ (
    .A(G8),
    .B(G11),
    .C(G12),
    .D(G14),
    .Y(_034_)
  );
  AND3x1_ASAP7_75t_L _176_ (
    .A(G13),
    .B(_001_),
    .C(_034_),
    .Y(_035_)
  );
  AO222x2_ASAP7_75t_L _177_ (
    .A1(G30),
    .A2(G50),
    .B1(G59),
    .B2(G55),
    .C1(_035_),
    .C2(G48),
    .Y(_036_)
  );
  A2O1A1O1Ixp25_ASAP7_75t_L _178_ (
    .A1(G48),
    .A2(G53),
    .B(G54),
    .C(_029_),
    .D(_036_),
    .Y(_037_)
  );
  NAND2xp33_ASAP7_75t_L _179_ (
    .A(_033_),
    .B(_037_),
    .Y(_038_)
  );
  O2A1O1Ixp33_ASAP7_75t_L _180_ (
    .A1(G58),
    .A2(_031_),
    .B(_032_),
    .C(_038_),
    .Y(G872)
  );
  AO221x1_ASAP7_75t_L _181_ (
    .A1(G28),
    .A2(_023_),
    .B1(_025_),
    .B2(G35),
    .C(_027_),
    .Y(_039_)
  );
  NAND2xp33_ASAP7_75t_L _182_ (
    .A(G45),
    .B(_039_),
    .Y(_040_)
  );
  NOR2xp33_ASAP7_75t_L _183_ (
    .A(G45),
    .B(_039_),
    .Y(_041_)
  );
  XOR2xp5_ASAP7_75t_L _184_ (
    .A(G45),
    .B(_039_),
    .Y(_042_)
  );
  AO221x1_ASAP7_75t_L _185_ (
    .A1(G29),
    .A2(_023_),
    .B1(_025_),
    .B2(G36),
    .C(_027_),
    .Y(_043_)
  );
  NAND2xp33_ASAP7_75t_L _186_ (
    .A(G46),
    .B(_043_),
    .Y(_044_)
  );
  NOR2xp33_ASAP7_75t_L _187_ (
    .A(G46),
    .B(_043_),
    .Y(_045_)
  );
  NAND2xp33_ASAP7_75t_L _188_ (
    .A(G37),
    .B(_025_),
    .Y(_046_)
  );
  O2A1O1Ixp33_ASAP7_75t_L _189_ (
    .A1(_019_),
    .A2(_022_),
    .B(G30),
    .C(_027_),
    .Y(_047_)
  );
  NAND2xp33_ASAP7_75t_L _190_ (
    .A(_046_),
    .B(_047_),
    .Y(_048_)
  );
  AOI21xp33_ASAP7_75t_L _191_ (
    .A1(_046_),
    .A2(_047_),
    .B(_111_),
    .Y(_049_)
  );
  NOR2xp33_ASAP7_75t_L _192_ (
    .A(G47),
    .B(_048_),
    .Y(_050_)
  );
  NAND3xp33_ASAP7_75t_L _193_ (
    .A(_111_),
    .B(_046_),
    .C(_047_),
    .Y(_051_)
  );
  A2O1A1Ixp33_ASAP7_75t_L _194_ (
    .A1(_024_),
    .A2(_028_),
    .B(_110_),
    .C(_112_),
    .Y(_052_)
  );
  AND2x2_ASAP7_75t_L _195_ (
    .A(_030_),
    .B(_052_),
    .Y(_053_)
  );
  A2O1A1Ixp33_ASAP7_75t_L _196_ (
    .A1(_030_),
    .A2(_052_),
    .B(_049_),
    .C(_051_),
    .Y(_054_)
  );
  AOI21xp33_ASAP7_75t_L _197_ (
    .A1(_044_),
    .A2(_054_),
    .B(_045_),
    .Y(_055_)
  );
  XOR2xp5_ASAP7_75t_L _198_ (
    .A(_042_),
    .B(_055_),
    .Y(_056_)
  );
  NAND2xp33_ASAP7_75t_L _199_ (
    .A(G52),
    .B(_042_),
    .Y(_057_)
  );
  AOI222xp33_ASAP7_75t_L _200_ (
    .A1(G27),
    .A2(G50),
    .B1(G54),
    .B2(_039_),
    .C1(_035_),
    .C2(G45),
    .Y(_058_)
  );
  OAI211xp5_ASAP7_75t_L _201_ (
    .A1(_115_),
    .A2(_040_),
    .B(_057_),
    .C(_058_),
    .Y(_059_)
  );
  AOI21xp33_ASAP7_75t_L _202_ (
    .A1(G51),
    .A2(_056_),
    .B(_059_),
    .Y(G873)
  );
  XOR2xp5_ASAP7_75t_L _203_ (
    .A(G46),
    .B(_043_),
    .Y(_060_)
  );
  XNOR2xp5_ASAP7_75t_L _204_ (
    .A(_054_),
    .B(_060_),
    .Y(_061_)
  );
  NAND2xp33_ASAP7_75t_L _205_ (
    .A(G52),
    .B(_060_),
    .Y(_062_)
  );
  AOI222xp33_ASAP7_75t_L _206_ (
    .A1(G55),
    .A2(G56),
    .B1(_043_),
    .B2(G54),
    .C1(_035_),
    .C2(G46),
    .Y(_063_)
  );
  OAI211xp5_ASAP7_75t_L _207_ (
    .A1(_115_),
    .A2(_044_),
    .B(_062_),
    .C(_063_),
    .Y(_064_)
  );
  AOI221xp5_ASAP7_75t_L _208_ (
    .A1(G28),
    .A2(G50),
    .B1(G51),
    .B2(_061_),
    .C(_064_),
    .Y(G874)
  );
  NOR2xp33_ASAP7_75t_L _209_ (
    .A(_049_),
    .B(_050_),
    .Y(_065_)
  );
  AOI21xp33_ASAP7_75t_L _210_ (
    .A1(_053_),
    .A2(_065_),
    .B(_113_),
    .Y(_066_)
  );
  NAND2xp33_ASAP7_75t_L _211_ (
    .A(G52),
    .B(_065_),
    .Y(_067_)
  );
  AO222x2_ASAP7_75t_L _212_ (
    .A1(G29),
    .A2(G50),
    .B1(G55),
    .B2(G57),
    .C1(_035_),
    .C2(G47),
    .Y(_068_)
  );
  AOI221xp5_ASAP7_75t_L _213_ (
    .A1(G54),
    .A2(_048_),
    .B1(_049_),
    .B2(G53),
    .C(_068_),
    .Y(_069_)
  );
  NAND2xp33_ASAP7_75t_L _214_ (
    .A(_067_),
    .B(_069_),
    .Y(_070_)
  );
  O2A1O1Ixp33_ASAP7_75t_L _215_ (
    .A1(_053_),
    .A2(_065_),
    .B(_066_),
    .C(_070_),
    .Y(G875)
  );
  NOR3xp33_ASAP7_75t_L _216_ (
    .A(_109_),
    .B(G866),
    .C(_020_),
    .Y(_071_)
  );
  OR4x1_ASAP7_75t_L _217_ (
    .A(_108_),
    .B(G60),
    .C(G866),
    .D(_026_),
    .Y(_072_)
  );
  AOI222xp33_ASAP7_75t_L _218_ (
    .A1(G2),
    .A2(G34),
    .B1(_023_),
    .B2(G24),
    .C1(_071_),
    .C2(G35),
    .Y(_073_)
  );
  NAND2xp33_ASAP7_75t_L _219_ (
    .A(_072_),
    .B(_073_),
    .Y(_074_)
  );
  AOI222xp33_ASAP7_75t_L _220_ (
    .A1(G9),
    .A2(G34),
    .B1(_023_),
    .B2(G25),
    .C1(_071_),
    .C2(G36),
    .Y(_075_)
  );
  NAND2xp33_ASAP7_75t_L _221_ (
    .A(_072_),
    .B(_075_),
    .Y(_076_)
  );
  NAND2xp33_ASAP7_75t_L _222_ (
    .A(G42),
    .B(_076_),
    .Y(_077_)
  );
  NOR2xp33_ASAP7_75t_L _223_ (
    .A(G42),
    .B(_076_),
    .Y(_078_)
  );
  AOI222xp33_ASAP7_75t_L _224_ (
    .A1(G4),
    .A2(G34),
    .B1(_023_),
    .B2(G26),
    .C1(_071_),
    .C2(G37),
    .Y(_079_)
  );
  NAND2xp33_ASAP7_75t_L _225_ (
    .A(_072_),
    .B(_079_),
    .Y(_080_)
  );
  NAND2xp33_ASAP7_75t_L _226_ (
    .A(G43),
    .B(_080_),
    .Y(_081_)
  );
  NOR2xp33_ASAP7_75t_L _227_ (
    .A(G43),
    .B(_080_),
    .Y(_082_)
  );
  AOI222xp33_ASAP7_75t_L _228_ (
    .A1(G27),
    .A2(_023_),
    .B1(_071_),
    .B2(G39),
    .C1(G34),
    .C2(G38),
    .Y(_083_)
  );
  NAND2xp33_ASAP7_75t_L _229_ (
    .A(_072_),
    .B(_083_),
    .Y(_084_)
  );
  A2O1A1O1Ixp25_ASAP7_75t_L _230_ (
    .A1(_044_),
    .A2(_054_),
    .B(_045_),
    .C(_040_),
    .D(_041_),
    .Y(_085_)
  );
  MAJIxp5_ASAP7_75t_L _231_ (
    .A(G44),
    .B(_084_),
    .C(_085_),
    .Y(_086_)
  );
  AOI21xp33_ASAP7_75t_L _232_ (
    .A1(_081_),
    .A2(_086_),
    .B(_082_),
    .Y(_087_)
  );
  A2O1A1O1Ixp25_ASAP7_75t_L _233_ (
    .A1(_081_),
    .A2(_086_),
    .B(_082_),
    .C(_077_),
    .D(_078_),
    .Y(_088_)
  );
  MAJIxp5_ASAP7_75t_L _234_ (
    .A(G41),
    .B(_074_),
    .C(_088_),
    .Y(G876)
  );
  XOR2xp5_ASAP7_75t_L _235_ (
    .A(G44),
    .B(_084_),
    .Y(_089_)
  );
  XNOR2xp5_ASAP7_75t_L _236_ (
    .A(_085_),
    .B(_089_),
    .Y(_090_)
  );
  NAND3xp33_ASAP7_75t_L _237_ (
    .A(G44),
    .B(G53),
    .C(_084_),
    .Y(_091_)
  );
  AO22x1_ASAP7_75t_L _238_ (
    .A1(G26),
    .A2(G50),
    .B1(_035_),
    .B2(G44),
    .Y(_092_)
  );
  AOI221xp5_ASAP7_75t_L _239_ (
    .A1(G54),
    .A2(_084_),
    .B1(_089_),
    .B2(G52),
    .C(_092_),
    .Y(_093_)
  );
  OA211x2_ASAP7_75t_L _240_ (
    .A1(_113_),
    .A2(_090_),
    .B(_091_),
    .C(_093_),
    .Y(G877)
  );
  XOR2xp5_ASAP7_75t_L _241_ (
    .A(G41),
    .B(_074_),
    .Y(_094_)
  );
  XNOR2xp5_ASAP7_75t_L _242_ (
    .A(_088_),
    .B(_094_),
    .Y(_095_)
  );
  NAND2xp33_ASAP7_75t_L _243_ (
    .A(G52),
    .B(_094_),
    .Y(_096_)
  );
  AO22x1_ASAP7_75t_L _244_ (
    .A1(G50),
    .A2(G60),
    .B1(_035_),
    .B2(G41),
    .Y(_097_)
  );
  A2O1A1O1Ixp25_ASAP7_75t_L _245_ (
    .A1(G41),
    .A2(G53),
    .B(G54),
    .C(_074_),
    .D(_097_),
    .Y(_098_)
  );
  OA211x2_ASAP7_75t_L _246_ (
    .A1(_113_),
    .A2(_095_),
    .B(_096_),
    .C(_098_),
    .Y(G878)
  );
  XOR2xp5_ASAP7_75t_L _247_ (
    .A(G42),
    .B(_076_),
    .Y(_099_)
  );
  XNOR2xp5_ASAP7_75t_L _248_ (
    .A(_087_),
    .B(_099_),
    .Y(_100_)
  );
  NAND2xp33_ASAP7_75t_L _249_ (
    .A(G52),
    .B(_099_),
    .Y(_101_)
  );
  AOI222xp33_ASAP7_75t_L _250_ (
    .A1(G24),
    .A2(G50),
    .B1(G54),
    .B2(_076_),
    .C1(_035_),
    .C2(G42),
    .Y(_102_)
  );
  OA21x2_ASAP7_75t_L _251_ (
    .A1(_115_),
    .A2(_077_),
    .B(_102_),
    .Y(_103_)
  );
  OA211x2_ASAP7_75t_L _252_ (
    .A1(_113_),
    .A2(_100_),
    .B(_101_),
    .C(_103_),
    .Y(G879)
  );
  XNOR2xp5_ASAP7_75t_L _253_ (
    .A(G43),
    .B(_080_),
    .Y(_104_)
  );
  XOR2xp5_ASAP7_75t_L _254_ (
    .A(_086_),
    .B(_104_),
    .Y(_105_)
  );
  AOI222xp33_ASAP7_75t_L _255_ (
    .A1(G25),
    .A2(G50),
    .B1(G54),
    .B2(_080_),
    .C1(_035_),
    .C2(G43),
    .Y(_106_)
  );
  OAI221xp5_ASAP7_75t_L _256_ (
    .A1(_115_),
    .A2(_081_),
    .B1(_104_),
    .B2(_114_),
    .C(_106_),
    .Y(_107_)
  );
  AOI21xp33_ASAP7_75t_L _257_ (
    .A1(G51),
    .A2(_105_),
    .B(_107_),
    .Y(G880)
  );
  assign G293 = G861;
  assign G295 = G862;
  assign G296 = G863;
  assign G343 = G857;
  assign G349 = G867;
  assign G350 = G868;
  assign G369 = G60;
  assign G812 = G872;
  assign G829 = G873;
  assign G830 = G874;
  assign G831 = G875;
  assign G832 = G876;
  assign G844 = G877;
  assign G849 = G878;
  assign G850 = G879;
  assign G851 = G880;
endmodule
