/* Generated by Yosys 0.54+29 (git sha1 7b0c1fe49, g++ 9.4.0-1ubuntu1~20.04.2 -fPIC -O3) */

module s344(GND, VDD, CK, A0, A1, A2, A3, B0, B1, B2, B3, CNTVCO2, CNTVCON2, P0, P1, P2, P3, P4, P5, P6, P7
, READY, START);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  input A0;
  wire A0;
  input A1;
  wire A1;
  input A2;
  wire A2;
  input A3;
  wire A3;
  wire ACVG1VD1;
  wire ACVG2VD1;
  wire ACVG3VD1;
  wire ACVG4VD1;
  wire AM0;
  wire AM1;
  wire AM2;
  wire AM3;
  input B0;
  wire B0;
  input B1;
  wire B1;
  input B2;
  wire B2;
  input B3;
  wire B3;
  wire BMVS0N;
  input CK;
  wire CK;
  output CNTVCO2;
  wire CNTVCO2;
  output CNTVCON2;
  wire CNTVCON2;
  wire CNTVG1VD;
  wire CNTVG2VD;
  wire CNTVG3VD;
  wire \DFF_0.CK ;
  wire \DFF_0.D ;
  wire \DFF_1.CK ;
  wire \DFF_1.D ;
  wire \DFF_10.CK ;
  wire \DFF_10.D ;
  wire \DFF_11.CK ;
  wire \DFF_11.D ;
  wire \DFF_12.CK ;
  wire \DFF_12.D ;
  wire \DFF_13.CK ;
  wire \DFF_13.D ;
  wire \DFF_14.CK ;
  wire \DFF_14.D ;
  wire \DFF_2.CK ;
  wire \DFF_2.D ;
  wire \DFF_3.CK ;
  wire \DFF_3.D ;
  wire \DFF_4.CK ;
  wire \DFF_4.D ;
  wire \DFF_5.CK ;
  wire \DFF_5.D ;
  wire \DFF_6.CK ;
  wire \DFF_6.D ;
  wire \DFF_7.CK ;
  wire \DFF_7.D ;
  wire \DFF_8.CK ;
  wire \DFF_8.D ;
  wire \DFF_9.CK ;
  wire \DFF_9.D ;
  input GND;
  wire GND;
  wire MRVG1VD;
  wire MRVG2VD;
  wire MRVG3VD;
  wire MRVG4VD;
  output P0;
  wire P0;
  output P1;
  wire P1;
  output P2;
  wire P2;
  output P3;
  wire P3;
  output P4;
  wire P4;
  output P5;
  wire P5;
  output P6;
  wire P6;
  output P7;
  wire P7;
  output READY;
  wire READY;
  input START;
  wire START;
  input VDD;
  wire VDD;
  INVx1_ASAP7_75t_L _049_ (
    .A(START),
    .Y(_008_)
  );
  INVx1_ASAP7_75t_L _050_ (
    .A(_001_),
    .Y(_009_)
  );
  INVx1_ASAP7_75t_L _051_ (
    .A(_002_),
    .Y(_010_)
  );
  INVx1_ASAP7_75t_L _052_ (
    .A(_003_),
    .Y(_011_)
  );
  INVx1_ASAP7_75t_L _053_ (
    .A(_004_),
    .Y(_012_)
  );
  INVx1_ASAP7_75t_L _054_ (
    .A(_005_),
    .Y(_013_)
  );
  INVx1_ASAP7_75t_L _055_ (
    .A(_006_),
    .Y(_014_)
  );
  NOR3xp33_ASAP7_75t_L _056_ (
    .A(_000_),
    .B(_005_),
    .C(_006_),
    .Y(CNTVCO2)
  );
  INVx1_ASAP7_75t_L _057_ (
    .A(CNTVCO2),
    .Y(CNTVCON2)
  );
  OR3x1_ASAP7_75t_L _058_ (
    .A(_000_),
    .B(_005_),
    .C(_014_),
    .Y(_015_)
  );
  INVx1_ASAP7_75t_L _059_ (
    .A(_015_),
    .Y(READY)
  );
  NAND3xp33_ASAP7_75t_L _060_ (
    .A(_000_),
    .B(_005_),
    .C(_006_),
    .Y(_016_)
  );
  AND2x2_ASAP7_75t_L _061_ (
    .A(_015_),
    .B(_016_),
    .Y(_017_)
  );
  NAND2xp33_ASAP7_75t_L _062_ (
    .A(_015_),
    .B(_016_),
    .Y(_018_)
  );
  AND3x1_ASAP7_75t_L _063_ (
    .A(P4),
    .B(P0),
    .C(_011_),
    .Y(_019_)
  );
  AOI21xp33_ASAP7_75t_L _064_ (
    .A1(P0),
    .A2(_012_),
    .B(P5),
    .Y(_020_)
  );
  AO21x1_ASAP7_75t_L _065_ (
    .A1(P0),
    .A2(_012_),
    .B(P5),
    .Y(_021_)
  );
  AND3x1_ASAP7_75t_L _066_ (
    .A(P5),
    .B(P0),
    .C(_012_),
    .Y(_022_)
  );
  AOI21xp33_ASAP7_75t_L _067_ (
    .A1(_019_),
    .A2(_021_),
    .B(_022_),
    .Y(_023_)
  );
  OA21x2_ASAP7_75t_L _068_ (
    .A1(_020_),
    .A2(_022_),
    .B(_019_),
    .Y(_024_)
  );
  OAI31xp33_ASAP7_75t_L _069_ (
    .A1(_019_),
    .A2(_020_),
    .A3(_022_),
    .B(_017_),
    .Y(_025_)
  );
  OAI221xp5_ASAP7_75t_L _070_ (
    .A1(P4),
    .A2(_017_),
    .B1(_024_),
    .B2(_025_),
    .C(_008_),
    .Y(\DFF_6.D )
  );
  AOI21xp33_ASAP7_75t_L _071_ (
    .A1(_009_),
    .A2(P0),
    .B(P6),
    .Y(_026_)
  );
  AO21x1_ASAP7_75t_L _072_ (
    .A1(_009_),
    .A2(P0),
    .B(P6),
    .Y(_027_)
  );
  AND3x1_ASAP7_75t_L _073_ (
    .A(P6),
    .B(_009_),
    .C(P0),
    .Y(_028_)
  );
  NOR2xp33_ASAP7_75t_L _074_ (
    .A(_026_),
    .B(_028_),
    .Y(_029_)
  );
  AOI21xp33_ASAP7_75t_L _075_ (
    .A1(_023_),
    .A2(_029_),
    .B(_018_),
    .Y(_030_)
  );
  O2A1O1Ixp33_ASAP7_75t_L _076_ (
    .A1(_023_),
    .A2(_029_),
    .B(_030_),
    .C(START),
    .Y(_031_)
  );
  OAI21xp33_ASAP7_75t_L _077_ (
    .A1(P5),
    .A2(_017_),
    .B(_031_),
    .Y(\DFF_5.D )
  );
  NAND2xp33_ASAP7_75t_L _078_ (
    .A(P0),
    .B(_010_),
    .Y(_032_)
  );
  A2O1A1O1Ixp25_ASAP7_75t_L _079_ (
    .A1(_019_),
    .A2(_021_),
    .B(_022_),
    .C(_027_),
    .D(_028_),
    .Y(_033_)
  );
  NAND3xp33_ASAP7_75t_L _080_ (
    .A(_017_),
    .B(_032_),
    .C(_033_),
    .Y(_034_)
  );
  NOR3xp33_ASAP7_75t_L _081_ (
    .A(_018_),
    .B(_032_),
    .C(_033_),
    .Y(_035_)
  );
  A2O1A1Ixp33_ASAP7_75t_L _082_ (
    .A1(P7),
    .A2(_034_),
    .B(_035_),
    .C(_008_),
    .Y(\DFF_3.D )
  );
  XNOR2xp5_ASAP7_75t_L _083_ (
    .A(_032_),
    .B(_033_),
    .Y(_036_)
  );
  NOR2xp33_ASAP7_75t_L _084_ (
    .A(P7),
    .B(_036_),
    .Y(_037_)
  );
  AO21x1_ASAP7_75t_L _085_ (
    .A1(P7),
    .A2(_036_),
    .B(_018_),
    .Y(_038_)
  );
  OAI221xp5_ASAP7_75t_L _086_ (
    .A1(P6),
    .A2(_017_),
    .B1(_037_),
    .B2(_038_),
    .C(_008_),
    .Y(\DFF_4.D )
  );
  OAI21xp33_ASAP7_75t_L _087_ (
    .A1(_005_),
    .A2(_006_),
    .B(_000_),
    .Y(_039_)
  );
  AND3x1_ASAP7_75t_L _088_ (
    .A(_008_),
    .B(CNTVCON2),
    .C(_039_),
    .Y(\DFF_0.D )
  );
  A2O1A1Ixp33_ASAP7_75t_L _089_ (
    .A1(_000_),
    .A2(_013_),
    .B(_014_),
    .C(_008_),
    .Y(_040_)
  );
  AOI21xp33_ASAP7_75t_L _090_ (
    .A1(_013_),
    .A2(_014_),
    .B(_040_),
    .Y(\DFF_1.D )
  );
  AOI21xp33_ASAP7_75t_L _091_ (
    .A1(_013_),
    .A2(_015_),
    .B(START),
    .Y(\DFF_2.D )
  );
  AOI21xp33_ASAP7_75t_L _092_ (
    .A1(P0),
    .A2(_011_),
    .B(P4),
    .Y(_041_)
  );
  OAI21xp33_ASAP7_75t_L _093_ (
    .A1(_019_),
    .A2(_041_),
    .B(_017_),
    .Y(_042_)
  );
  OAI221xp5_ASAP7_75t_L _094_ (
    .A1(P3),
    .A2(_015_),
    .B1(_016_),
    .B2(B3),
    .C(_042_),
    .Y(\DFF_7.D )
  );
  OR2x2_ASAP7_75t_L _095_ (
    .A(P2),
    .B(_015_),
    .Y(_043_)
  );
  OAI221xp5_ASAP7_75t_L _096_ (
    .A1(B2),
    .A2(_016_),
    .B1(_018_),
    .B2(P3),
    .C(_043_),
    .Y(\DFF_8.D )
  );
  OR2x2_ASAP7_75t_L _097_ (
    .A(P1),
    .B(_015_),
    .Y(_044_)
  );
  OAI221xp5_ASAP7_75t_L _098_ (
    .A1(B1),
    .A2(_016_),
    .B1(_018_),
    .B2(P2),
    .C(_044_),
    .Y(\DFF_9.D )
  );
  OR2x2_ASAP7_75t_L _099_ (
    .A(P0),
    .B(_015_),
    .Y(_045_)
  );
  OAI221xp5_ASAP7_75t_L _100_ (
    .A1(B0),
    .A2(_016_),
    .B1(_018_),
    .B2(P1),
    .C(_045_),
    .Y(\DFF_10.D )
  );
  NOR2xp33_ASAP7_75t_L _101_ (
    .A(A3),
    .B(_016_),
    .Y(_046_)
  );
  AOI21xp33_ASAP7_75t_L _102_ (
    .A1(_002_),
    .A2(_016_),
    .B(_046_),
    .Y(\DFF_11.D )
  );
  NOR2xp33_ASAP7_75t_L _103_ (
    .A(A2),
    .B(_016_),
    .Y(_047_)
  );
  AOI21xp33_ASAP7_75t_L _104_ (
    .A1(_001_),
    .A2(_016_),
    .B(_047_),
    .Y(\DFF_12.D )
  );
  NOR2xp33_ASAP7_75t_L _105_ (
    .A(A1),
    .B(_016_),
    .Y(_048_)
  );
  AOI21xp33_ASAP7_75t_L _106_ (
    .A1(_004_),
    .A2(_016_),
    .B(_048_),
    .Y(\DFF_13.D )
  );
  NOR2xp33_ASAP7_75t_L _107_ (
    .A(A0),
    .B(_016_),
    .Y(_007_)
  );
  AOI21xp33_ASAP7_75t_L _108_ (
    .A1(_003_),
    .A2(_016_),
    .B(_007_),
    .Y(\DFF_14.D )
  );
  DFFHQNx1_ASAP7_75t_R _109_ (
    .CLK(CK),
    .D(\DFF_8.D ),
    .QN(P2)
  );
  DFFHQNx1_ASAP7_75t_R _110_ (
    .CLK(CK),
    .D(\DFF_6.D ),
    .QN(P4)
  );
  DFFHQNx1_ASAP7_75t_R _111_ (
    .CLK(CK),
    .D(\DFF_7.D ),
    .QN(P3)
  );
  DFFHQNx1_ASAP7_75t_R _112_ (
    .CLK(CK),
    .D(\DFF_5.D ),
    .QN(P5)
  );
  DFFHQNx1_ASAP7_75t_R _113_ (
    .CLK(CK),
    .D(\DFF_12.D ),
    .QN(_001_)
  );
  DFFHQNx1_ASAP7_75t_R _114_ (
    .CLK(CK),
    .D(\DFF_10.D ),
    .QN(P0)
  );
  DFFHQNx1_ASAP7_75t_R _115_ (
    .CLK(CK),
    .D(\DFF_11.D ),
    .QN(_002_)
  );
  DFFHQNx1_ASAP7_75t_R _116_ (
    .CLK(CK),
    .D(\DFF_9.D ),
    .QN(P1)
  );
  DFFHQNx1_ASAP7_75t_R _117_ (
    .CLK(CK),
    .D(\DFF_14.D ),
    .QN(_003_)
  );
  DFFHQNx1_ASAP7_75t_R _118_ (
    .CLK(CK),
    .D(\DFF_13.D ),
    .QN(_004_)
  );
  DFFHQNx1_ASAP7_75t_R _119_ (
    .CLK(CK),
    .D(\DFF_4.D ),
    .QN(P6)
  );
  DFFHQNx1_ASAP7_75t_R _120_ (
    .CLK(CK),
    .D(\DFF_3.D ),
    .QN(P7)
  );
  DFFHQNx1_ASAP7_75t_R _121_ (
    .CLK(CK),
    .D(\DFF_2.D ),
    .QN(_005_)
  );
  DFFHQNx1_ASAP7_75t_R _122_ (
    .CLK(CK),
    .D(\DFF_1.D ),
    .QN(_006_)
  );
  DFFHQNx1_ASAP7_75t_R _123_ (
    .CLK(CK),
    .D(\DFF_0.D ),
    .QN(_000_)
  );
  assign ACVG1VD1 = \DFF_6.D ;
  assign ACVG2VD1 = \DFF_5.D ;
  assign ACVG3VD1 = \DFF_4.D ;
  assign ACVG4VD1 = \DFF_3.D ;
  assign AM0 = \DFF_14.D ;
  assign AM1 = \DFF_13.D ;
  assign AM2 = \DFF_12.D ;
  assign AM3 = \DFF_11.D ;
  assign BMVS0N = READY;
  assign CNTVG1VD = \DFF_2.D ;
  assign CNTVG2VD = \DFF_1.D ;
  assign CNTVG3VD = \DFF_0.D ;
  assign \DFF_0.CK  = CK;
  assign \DFF_1.CK  = CK;
  assign \DFF_10.CK  = CK;
  assign \DFF_11.CK  = CK;
  assign \DFF_12.CK  = CK;
  assign \DFF_13.CK  = CK;
  assign \DFF_14.CK  = CK;
  assign \DFF_2.CK  = CK;
  assign \DFF_3.CK  = CK;
  assign \DFF_4.CK  = CK;
  assign \DFF_5.CK  = CK;
  assign \DFF_6.CK  = CK;
  assign \DFF_7.CK  = CK;
  assign \DFF_8.CK  = CK;
  assign \DFF_9.CK  = CK;
  assign MRVG1VD = \DFF_10.D ;
  assign MRVG2VD = \DFF_9.D ;
  assign MRVG3VD = \DFF_8.D ;
  assign MRVG4VD = \DFF_7.D ;
endmodule
