UCLA scl 1.0

NumRows : 36

CoreRow Horizontal
  Coordinate   : 95
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : 0
  Sitesymmetry : 1
  SubrowOrigin : 93  NumSites : 182
End
CoreRow Horizontal
  Coordinate   : 100
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : MX
  Sitesymmetry : 1
  SubrowOrigin : 93  NumSites : 182
End
CoreRow Horizontal
  Coordinate   : 105
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : 0
  Sitesymmetry : 1
  SubrowOrigin : 93  NumSites : 182
End
CoreRow Horizontal
  Coordinate   : 110
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : MX
  Sitesymmetry : 1
  SubrowOrigin : 93  NumSites : 182
End
CoreRow Horizontal
  Coordinate   : 115
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : 0
  Sitesymmetry : 1
  SubrowOrigin : 93  NumSites : 182
End
CoreRow Horizontal
  Coordinate   : 120
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : MX
  Sitesymmetry : 1
  SubrowOrigin : 93  NumSites : 182
End
CoreRow Horizontal
  Coordinate   : 125
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : 0
  Sitesymmetry : 1
  SubrowOrigin : 93  NumSites : 182
End
CoreRow Horizontal
  Coordinate   : 130
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : MX
  Sitesymmetry : 1
  SubrowOrigin : 93  NumSites : 182
End
CoreRow Horizontal
  Coordinate   : 135
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : 0
  Sitesymmetry : 1
  SubrowOrigin : 93  NumSites : 182
End
CoreRow Horizontal
  Coordinate   : 140
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : MX
  Sitesymmetry : 1
  SubrowOrigin : 93  NumSites : 182
End
CoreRow Horizontal
  Coordinate   : 145
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : 0
  Sitesymmetry : 1
  SubrowOrigin : 93  NumSites : 182
End
CoreRow Horizontal
  Coordinate   : 150
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : MX
  Sitesymmetry : 1
  SubrowOrigin : 93  NumSites : 182
End
CoreRow Horizontal
  Coordinate   : 155
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : 0
  Sitesymmetry : 1
  SubrowOrigin : 93  NumSites : 182
End
CoreRow Horizontal
  Coordinate   : 160
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : MX
  Sitesymmetry : 1
  SubrowOrigin : 93  NumSites : 182
End
CoreRow Horizontal
  Coordinate   : 165
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : 0
  Sitesymmetry : 1
  SubrowOrigin : 93  NumSites : 182
End
CoreRow Horizontal
  Coordinate   : 170
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : MX
  Sitesymmetry : 1
  SubrowOrigin : 93  NumSites : 182
End
CoreRow Horizontal
  Coordinate   : 175
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : 0
  Sitesymmetry : 1
  SubrowOrigin : 93  NumSites : 182
End
CoreRow Horizontal
  Coordinate   : 180
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : MX
  Sitesymmetry : 1
  SubrowOrigin : 93  NumSites : 182
End
CoreRow Horizontal
  Coordinate   : 185
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : 0
  Sitesymmetry : 1
  SubrowOrigin : 93  NumSites : 182
End
CoreRow Horizontal
  Coordinate   : 190
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : MX
  Sitesymmetry : 1
  SubrowOrigin : 93  NumSites : 182
End
CoreRow Horizontal
  Coordinate   : 195
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : 0
  Sitesymmetry : 1
  SubrowOrigin : 93  NumSites : 182
End
CoreRow Horizontal
  Coordinate   : 200
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : MX
  Sitesymmetry : 1
  SubrowOrigin : 93  NumSites : 182
End
CoreRow Horizontal
  Coordinate   : 205
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : 0
  Sitesymmetry : 1
  SubrowOrigin : 93  NumSites : 182
End
CoreRow Horizontal
  Coordinate   : 210
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : MX
  Sitesymmetry : 1
  SubrowOrigin : 93  NumSites : 182
End
CoreRow Horizontal
  Coordinate   : 215
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : 0
  Sitesymmetry : 1
  SubrowOrigin : 93  NumSites : 182
End
CoreRow Horizontal
  Coordinate   : 220
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : MX
  Sitesymmetry : 1
  SubrowOrigin : 93  NumSites : 182
End
CoreRow Horizontal
  Coordinate   : 225
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : 0
  Sitesymmetry : 1
  SubrowOrigin : 93  NumSites : 182
End
CoreRow Horizontal
  Coordinate   : 230
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : MX
  Sitesymmetry : 1
  SubrowOrigin : 93  NumSites : 182
End
CoreRow Horizontal
  Coordinate   : 235
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : 0
  Sitesymmetry : 1
  SubrowOrigin : 93  NumSites : 182
End
CoreRow Horizontal
  Coordinate   : 240
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : MX
  Sitesymmetry : 1
  SubrowOrigin : 93  NumSites : 182
End
CoreRow Horizontal
  Coordinate   : 245
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : 0
  Sitesymmetry : 1
  SubrowOrigin : 93  NumSites : 182
End
CoreRow Horizontal
  Coordinate   : 250
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : MX
  Sitesymmetry : 1
  SubrowOrigin : 93  NumSites : 182
End
CoreRow Horizontal
  Coordinate   : 255
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : 0
  Sitesymmetry : 1
  SubrowOrigin : 93  NumSites : 182
End
CoreRow Horizontal
  Coordinate   : 260
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : MX
  Sitesymmetry : 1
  SubrowOrigin : 93  NumSites : 182
End
CoreRow Horizontal
  Coordinate   : 265
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : 0
  Sitesymmetry : 1
  SubrowOrigin : 93  NumSites : 182
End
CoreRow Horizontal
  Coordinate   : 270
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : MX
  Sitesymmetry : 1
  SubrowOrigin : 93  NumSites : 182
End
