/* Generated by Yosys 0.54+29 (git sha1 7b0c1fe49, g++ 9.4.0-1ubuntu1~20.04.2 -fPIC -O3) */

module s400(GND, VDD, CK, CLR, FM, GRN1, GRN2, RED1, RED2, TEST, YLW1, YLW2);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire C3_Q0VD;
  wire C3_Q1VD;
  wire C3_Q2VD;
  wire C3_Q3VD;
  input CK;
  wire CK;
  input CLR;
  wire CLR;
  wire CLRB;
  wire \DFF_0.CK ;
  wire \DFF_0.D ;
  wire \DFF_1.CK ;
  wire \DFF_1.D ;
  wire \DFF_10.CK ;
  wire \DFF_10.D ;
  wire \DFF_11.CK ;
  wire \DFF_11.D ;
  wire \DFF_12.CK ;
  wire \DFF_12.D ;
  wire \DFF_13.CK ;
  wire \DFF_13.D ;
  wire \DFF_14.CK ;
  wire \DFF_14.D ;
  wire \DFF_15.CK ;
  wire \DFF_15.D ;
  wire \DFF_16.CK ;
  wire \DFF_16.D ;
  wire \DFF_17.CK ;
  wire \DFF_17.D ;
  wire \DFF_18.CK ;
  wire \DFF_18.D ;
  wire \DFF_19.CK ;
  wire \DFF_19.D ;
  wire \DFF_2.CK ;
  wire \DFF_2.D ;
  wire \DFF_2.Q ;
  wire \DFF_20.CK ;
  wire \DFF_20.D ;
  wire \DFF_3.CK ;
  wire \DFF_3.D ;
  wire \DFF_4.CK ;
  wire \DFF_4.D ;
  wire \DFF_5.CK ;
  wire \DFF_5.D ;
  wire \DFF_5.Q ;
  wire \DFF_6.CK ;
  wire \DFF_6.D ;
  wire \DFF_6.Q ;
  wire \DFF_7.CK ;
  wire \DFF_7.D ;
  wire \DFF_7.Q ;
  wire \DFF_8.CK ;
  wire \DFF_8.D ;
  wire \DFF_9.CK ;
  wire \DFF_9.D ;
  input FM;
  wire FM;
  wire FMB;
  wire FMLVIINLATCHVCDAD;
  input GND;
  wire GND;
  output GRN1;
  wire GRN1;
  output GRN2;
  wire GRN2;
  wire OLATCH_G1L;
  wire OLATCH_G2L;
  wire OLATCH_R1L;
  wire OLATCH_Y2L;
  wire R2C;
  output RED1;
  wire RED1;
  output RED2;
  wire RED2;
  wire TCOMB_FE;
  wire TCOMB_FE_BF;
  wire TCOMB_GA1;
  wire TCOMB_GA2;
  wire TCOMB_RA1;
  wire TCOMB_YA2;
  input TEST;
  wire TEST;
  wire TESTB;
  wire TESTLVIINLATCHVCDAD;
  wire UC_10VD;
  wire UC_11VD;
  wire UC_16VD;
  wire UC_17VD;
  wire UC_18VD;
  wire UC_19VD;
  wire UC_8VD;
  wire UC_9VD;
  input VDD;
  wire VDD;
  wire Y1C;
  output YLW1;
  wire YLW1;
  output YLW2;
  wire YLW2;
  INVx1_ASAP7_75t_L _065_ (
    .A(_001_),
    .Y(_028_)
  );
  INVx1_ASAP7_75t_L _066_ (
    .A(_003_),
    .Y(_029_)
  );
  INVx1_ASAP7_75t_L _067_ (
    .A(_005_),
    .Y(_030_)
  );
  INVx1_ASAP7_75t_L _068_ (
    .A(_008_),
    .Y(_031_)
  );
  INVx1_ASAP7_75t_L _069_ (
    .A(_009_),
    .Y(_032_)
  );
  INVx1_ASAP7_75t_L _070_ (
    .A(_010_),
    .Y(RED1)
  );
  INVx1_ASAP7_75t_L _071_ (
    .A(_011_),
    .Y(YLW2)
  );
  INVx1_ASAP7_75t_L _072_ (
    .A(_012_),
    .Y(GRN1)
  );
  INVx1_ASAP7_75t_L _073_ (
    .A(_013_),
    .Y(GRN2)
  );
  INVx1_ASAP7_75t_L _074_ (
    .A(_015_),
    .Y(_033_)
  );
  INVx1_ASAP7_75t_L _075_ (
    .A(_018_),
    .Y(_034_)
  );
  NOR2xp33_ASAP7_75t_L _076_ (
    .A(CLR),
    .B(_002_),
    .Y(_035_)
  );
  NAND2xp33_ASAP7_75t_L _077_ (
    .A(_001_),
    .B(_005_),
    .Y(_036_)
  );
  NOR4xp25_ASAP7_75t_L _078_ (
    .A(CLR),
    .B(_002_),
    .C(_018_),
    .D(_036_),
    .Y(_037_)
  );
  NAND4xp25_ASAP7_75t_L _079_ (
    .A(_028_),
    .B(_005_),
    .C(_004_),
    .D(_018_),
    .Y(_038_)
  );
  NOR2xp33_ASAP7_75t_L _080_ (
    .A(CLR),
    .B(_003_),
    .Y(_039_)
  );
  OA21x2_ASAP7_75t_L _081_ (
    .A1(_002_),
    .A2(_038_),
    .B(_039_),
    .Y(_040_)
  );
  O2A1O1Ixp33_ASAP7_75t_L _082_ (
    .A1(_002_),
    .A2(_038_),
    .B(_039_),
    .C(_037_),
    .Y(_041_)
  );
  INVx1_ASAP7_75t_L _083_ (
    .A(_041_),
    .Y(\DFF_8.D )
  );
  NOR2xp33_ASAP7_75t_L _084_ (
    .A(CLR),
    .B(_004_),
    .Y(_042_)
  );
  AOI21xp33_ASAP7_75t_L _085_ (
    .A1(_002_),
    .A2(_003_),
    .B(CLR),
    .Y(_043_)
  );
  O2A1O1Ixp33_ASAP7_75t_L _086_ (
    .A1(_001_),
    .A2(_030_),
    .B(_042_),
    .C(_043_),
    .Y(\DFF_5.D )
  );
  AOI31xp33_ASAP7_75t_L _087_ (
    .A1(_014_),
    .A2(_016_),
    .A3(_017_),
    .B(_007_),
    .Y(_044_)
  );
  NOR2xp33_ASAP7_75t_L _088_ (
    .A(_032_),
    .B(_044_),
    .Y(_045_)
  );
  AOI31xp33_ASAP7_75t_L _089_ (
    .A1(_000_),
    .A2(_008_),
    .A3(_015_),
    .B(_006_),
    .Y(_046_)
  );
  OAI21xp33_ASAP7_75t_L _090_ (
    .A1(_032_),
    .A2(_044_),
    .B(_046_),
    .Y(_047_)
  );
  OR4x1_ASAP7_75t_L _091_ (
    .A(_002_),
    .B(_001_),
    .C(_005_),
    .D(_047_),
    .Y(_048_)
  );
  O2A1O1Ixp33_ASAP7_75t_L _092_ (
    .A1(_032_),
    .A2(_044_),
    .B(_046_),
    .C(CLR),
    .Y(_049_)
  );
  INVx1_ASAP7_75t_L _093_ (
    .A(_049_),
    .Y(_050_)
  );
  AOI31xp33_ASAP7_75t_L _094_ (
    .A1(_002_),
    .A2(_001_),
    .A3(_005_),
    .B(_004_),
    .Y(_051_)
  );
  NOR2xp33_ASAP7_75t_L _095_ (
    .A(CLR),
    .B(_051_),
    .Y(_052_)
  );
  NOR2xp33_ASAP7_75t_L _096_ (
    .A(_049_),
    .B(_052_),
    .Y(_053_)
  );
  AOI21xp33_ASAP7_75t_L _097_ (
    .A1(_004_),
    .A2(_048_),
    .B(_053_),
    .Y(\DFF_9.D )
  );
  OAI31xp33_ASAP7_75t_L _098_ (
    .A1(_001_),
    .A2(_005_),
    .A3(_047_),
    .B(_002_),
    .Y(_054_)
  );
  OA211x2_ASAP7_75t_L _099_ (
    .A1(_049_),
    .A2(_052_),
    .B(_054_),
    .C(_048_),
    .Y(\DFF_10.D )
  );
  OAI32xp33_ASAP7_75t_L _100_ (
    .A1(_001_),
    .A2(_005_),
    .A3(_047_),
    .B1(_049_),
    .B2(_052_),
    .Y(_055_)
  );
  O2A1O1Ixp33_ASAP7_75t_L _101_ (
    .A1(_001_),
    .A2(_047_),
    .B(_005_),
    .C(_055_),
    .Y(\DFF_11.D )
  );
  OAI22xp33_ASAP7_75t_L _102_ (
    .A1(_001_),
    .A2(_047_),
    .B1(_049_),
    .B2(_052_),
    .Y(_056_)
  );
  AOI21xp33_ASAP7_75t_L _103_ (
    .A1(_001_),
    .A2(_047_),
    .B(_056_),
    .Y(\DFF_12.D )
  );
  OAI211xp5_ASAP7_75t_L _104_ (
    .A1(_032_),
    .A2(_044_),
    .B(_033_),
    .C(_031_),
    .Y(_057_)
  );
  O2A1O1Ixp33_ASAP7_75t_L _105_ (
    .A1(_000_),
    .A2(_057_),
    .B(_006_),
    .C(_050_),
    .Y(\DFF_13.D )
  );
  OAI21xp33_ASAP7_75t_L _106_ (
    .A1(_000_),
    .A2(_057_),
    .B(_049_),
    .Y(_058_)
  );
  AOI21xp33_ASAP7_75t_L _107_ (
    .A1(_000_),
    .A2(_057_),
    .B(_058_),
    .Y(\DFF_14.D )
  );
  NAND2xp33_ASAP7_75t_L _108_ (
    .A(_049_),
    .B(_057_),
    .Y(_059_)
  );
  O2A1O1Ixp33_ASAP7_75t_L _109_ (
    .A1(_015_),
    .A2(_045_),
    .B(_008_),
    .C(_059_),
    .Y(\DFF_15.D )
  );
  OAI21xp33_ASAP7_75t_L _110_ (
    .A1(_015_),
    .A2(_045_),
    .B(_049_),
    .Y(_060_)
  );
  AOI21xp33_ASAP7_75t_L _111_ (
    .A1(_015_),
    .A2(_045_),
    .B(_060_),
    .Y(\DFF_16.D )
  );
  NOR2xp33_ASAP7_75t_L _112_ (
    .A(CLR),
    .B(_044_),
    .Y(_061_)
  );
  NOR3xp33_ASAP7_75t_L _113_ (
    .A(_014_),
    .B(_016_),
    .C(_017_),
    .Y(_062_)
  );
  XOR2xp5_ASAP7_75t_L _114_ (
    .A(_007_),
    .B(_062_),
    .Y(_063_)
  );
  NOR3xp33_ASAP7_75t_L _115_ (
    .A(CLR),
    .B(_044_),
    .C(_063_),
    .Y(\DFF_17.D )
  );
  OA21x2_ASAP7_75t_L _116_ (
    .A1(_016_),
    .A2(_017_),
    .B(_014_),
    .Y(_064_)
  );
  NOR4xp25_ASAP7_75t_L _117_ (
    .A(CLR),
    .B(_044_),
    .C(_062_),
    .D(_064_),
    .Y(\DFF_18.D )
  );
  OAI21xp33_ASAP7_75t_L _118_ (
    .A1(_016_),
    .A2(_017_),
    .B(_061_),
    .Y(_019_)
  );
  AOI21xp33_ASAP7_75t_L _119_ (
    .A1(_016_),
    .A2(_017_),
    .B(_019_),
    .Y(\DFF_19.D )
  );
  AND2x2_ASAP7_75t_L _120_ (
    .A(_016_),
    .B(_061_),
    .Y(\DFF_20.D )
  );
  NOR3xp33_ASAP7_75t_L _121_ (
    .A(CLR),
    .B(_001_),
    .C(_005_),
    .Y(_020_)
  );
  AOI211xp5_ASAP7_75t_L _122_ (
    .A1(_001_),
    .A2(_042_),
    .B(_043_),
    .C(_020_),
    .Y(\DFF_6.D )
  );
  AND3x1_ASAP7_75t_L _123_ (
    .A(_002_),
    .B(_003_),
    .C(_020_),
    .Y(\DFF_2.D )
  );
  A2O1A1Ixp33_ASAP7_75t_L _124_ (
    .A1(_004_),
    .A2(_036_),
    .B(_018_),
    .C(_035_),
    .Y(_021_)
  );
  AOI21xp33_ASAP7_75t_L _125_ (
    .A1(_029_),
    .A2(_038_),
    .B(_021_),
    .Y(\DFF_7.D )
  );
  NOR2xp33_ASAP7_75t_L _126_ (
    .A(_035_),
    .B(_042_),
    .Y(_022_)
  );
  AOI21xp33_ASAP7_75t_L _127_ (
    .A1(_004_),
    .A2(_034_),
    .B(_002_),
    .Y(_023_)
  );
  NOR3xp33_ASAP7_75t_L _128_ (
    .A(_036_),
    .B(_022_),
    .C(_023_),
    .Y(_024_)
  );
  OAI22xp33_ASAP7_75t_L _129_ (
    .A1(_000_),
    .A2(_041_),
    .B1(_024_),
    .B2(_040_),
    .Y(\DFF_3.D )
  );
  AND3x1_ASAP7_75t_L _130_ (
    .A(_001_),
    .B(_005_),
    .C(_042_),
    .Y(_025_)
  );
  OAI22xp33_ASAP7_75t_L _131_ (
    .A1(_000_),
    .A2(_041_),
    .B1(_043_),
    .B2(_025_),
    .Y(\DFF_4.D )
  );
  AOI21xp33_ASAP7_75t_L _132_ (
    .A1(TEST),
    .A2(_032_),
    .B(CLR),
    .Y(_026_)
  );
  OA21x2_ASAP7_75t_L _133_ (
    .A1(TEST),
    .A2(_032_),
    .B(_026_),
    .Y(\DFF_0.D )
  );
  AOI21xp33_ASAP7_75t_L _134_ (
    .A1(FM),
    .A2(_034_),
    .B(CLR),
    .Y(_027_)
  );
  OA21x2_ASAP7_75t_L _135_ (
    .A1(FM),
    .A2(_034_),
    .B(_027_),
    .Y(\DFF_1.D )
  );
  DFFHQNx1_ASAP7_75t_R _136_ (
    .CLK(CK),
    .D(\DFF_3.D ),
    .QN(YLW1)
  );
  DFFHQNx1_ASAP7_75t_R _137_ (
    .CLK(CK),
    .D(\DFF_5.D ),
    .QN(_010_)
  );
  DFFHQNx1_ASAP7_75t_R _138_ (
    .CLK(CK),
    .D(\DFF_2.D ),
    .QN(_011_)
  );
  DFFHQNx1_ASAP7_75t_R _139_ (
    .CLK(CK),
    .D(\DFF_4.D ),
    .QN(RED2)
  );
  DFFHQNx1_ASAP7_75t_R _140_ (
    .CLK(CK),
    .D(\DFF_9.D ),
    .QN(_004_)
  );
  DFFHQNx1_ASAP7_75t_R _141_ (
    .CLK(CK),
    .D(\DFF_7.D ),
    .QN(_012_)
  );
  DFFHQNx1_ASAP7_75t_R _142_ (
    .CLK(CK),
    .D(\DFF_8.D ),
    .QN(_003_)
  );
  DFFHQNx1_ASAP7_75t_R _143_ (
    .CLK(CK),
    .D(\DFF_6.D ),
    .QN(_013_)
  );
  DFFHQNx1_ASAP7_75t_R _144_ (
    .CLK(CK),
    .D(\DFF_11.D ),
    .QN(_005_)
  );
  DFFHQNx1_ASAP7_75t_R _145_ (
    .CLK(CK),
    .D(\DFF_10.D ),
    .QN(_002_)
  );
  DFFHQNx1_ASAP7_75t_R _146_ (
    .CLK(CK),
    .D(\DFF_13.D ),
    .QN(_006_)
  );
  DFFHQNx1_ASAP7_75t_R _147_ (
    .CLK(CK),
    .D(\DFF_12.D ),
    .QN(_001_)
  );
  DFFHQNx1_ASAP7_75t_R _148_ (
    .CLK(CK),
    .D(\DFF_18.D ),
    .QN(_014_)
  );
  DFFHQNx1_ASAP7_75t_R _149_ (
    .CLK(CK),
    .D(\DFF_15.D ),
    .QN(_008_)
  );
  DFFHQNx1_ASAP7_75t_R _150_ (
    .CLK(CK),
    .D(\DFF_17.D ),
    .QN(_007_)
  );
  DFFHQNx1_ASAP7_75t_R _151_ (
    .CLK(CK),
    .D(\DFF_14.D ),
    .QN(_000_)
  );
  DFFHQNx1_ASAP7_75t_R _152_ (
    .CLK(CK),
    .D(\DFF_16.D ),
    .QN(_015_)
  );
  DFFHQNx1_ASAP7_75t_R _153_ (
    .CLK(CK),
    .D(\DFF_20.D ),
    .QN(_016_)
  );
  DFFHQNx1_ASAP7_75t_R _154_ (
    .CLK(CK),
    .D(\DFF_19.D ),
    .QN(_017_)
  );
  DFFHQNx1_ASAP7_75t_R _155_ (
    .CLK(CK),
    .D(\DFF_1.D ),
    .QN(_018_)
  );
  DFFHQNx1_ASAP7_75t_R _156_ (
    .CLK(CK),
    .D(\DFF_0.D ),
    .QN(_009_)
  );
  assign C3_Q0VD = \DFF_12.D ;
  assign C3_Q1VD = \DFF_11.D ;
  assign C3_Q2VD = \DFF_10.D ;
  assign C3_Q3VD = \DFF_9.D ;
  assign CLRB = CLR;
  assign \DFF_0.CK  = CK;
  assign \DFF_1.CK  = CK;
  assign \DFF_10.CK  = CK;
  assign \DFF_11.CK  = CK;
  assign \DFF_12.CK  = CK;
  assign \DFF_13.CK  = CK;
  assign \DFF_14.CK  = CK;
  assign \DFF_15.CK  = CK;
  assign \DFF_16.CK  = CK;
  assign \DFF_17.CK  = CK;
  assign \DFF_18.CK  = CK;
  assign \DFF_19.CK  = CK;
  assign \DFF_2.CK  = CK;
  assign \DFF_2.Q  = YLW2;
  assign \DFF_20.CK  = CK;
  assign \DFF_3.CK  = CK;
  assign \DFF_4.CK  = CK;
  assign \DFF_5.CK  = CK;
  assign \DFF_5.Q  = RED1;
  assign \DFF_6.CK  = CK;
  assign \DFF_6.Q  = GRN2;
  assign \DFF_7.CK  = CK;
  assign \DFF_7.Q  = GRN1;
  assign \DFF_8.CK  = CK;
  assign \DFF_9.CK  = CK;
  assign FMB = FM;
  assign FMLVIINLATCHVCDAD = \DFF_1.D ;
  assign OLATCH_G1L = GRN1;
  assign OLATCH_G2L = GRN2;
  assign OLATCH_R1L = RED1;
  assign OLATCH_Y2L = YLW2;
  assign R2C = \DFF_4.D ;
  assign TCOMB_FE = \DFF_8.D ;
  assign TCOMB_FE_BF = \DFF_8.D ;
  assign TCOMB_GA1 = \DFF_7.D ;
  assign TCOMB_GA2 = \DFF_6.D ;
  assign TCOMB_RA1 = \DFF_5.D ;
  assign TCOMB_YA2 = \DFF_2.D ;
  assign TESTB = TEST;
  assign TESTLVIINLATCHVCDAD = \DFF_0.D ;
  assign UC_10VD = \DFF_19.D ;
  assign UC_11VD = \DFF_20.D ;
  assign UC_16VD = \DFF_13.D ;
  assign UC_17VD = \DFF_14.D ;
  assign UC_18VD = \DFF_15.D ;
  assign UC_19VD = \DFF_16.D ;
  assign UC_8VD = \DFF_17.D ;
  assign UC_9VD = \DFF_18.D ;
  assign Y1C = \DFF_3.D ;
endmodule
