/* Generated by Yosys 0.54+29 (git sha1 7b0c1fe49, g++ 9.4.0-1ubuntu1~20.04.2 -fPIC -O3) */

module s953(GND, VDD, CK, ActBmHS1, ActRtHS1, DumpIIHS1, FullIIHS1, FullOHS1, GoBmHS1, GoRtHS1, IInDoneHS1, LdProgHS1, LoadIIHHS1, LoadOHHS1, LxHIInHS1, Mode0HS1, Mode1HS1, Mode2HS1, NewLineHS1, NewTrHS1, OutAvHS1
, OutputHS1, Prog_0, Prog_1, Prog_2, Rdy1BmHS1, Rdy1RtHS1, Rdy2BmHS1, Rdy2RtHS1, ReRtTSHS1, ReWhBufHS1, RtTSHS1, SeFullIIHS1, SeFullOHS1, SeOutAvHS1, ShftIIRHS1, ShftORHS1, TgWhBufHS1, TpArrayHS1, TxHIInHS1, WantBmHS1, WantRtHS1
);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  output ActBmHS1;
  wire ActBmHS1;
  output ActRtHS1;
  wire ActRtHS1;
  input CK;
  wire CK;
  wire \DFF_0.CK ;
  wire \DFF_0.D ;
  wire \DFF_1.CK ;
  wire \DFF_1.D ;
  wire \DFF_10.CK ;
  wire \DFF_10.D ;
  wire \DFF_10.Q ;
  wire \DFF_11.CK ;
  wire \DFF_11.D ;
  wire \DFF_11.Q ;
  wire \DFF_12.CK ;
  wire \DFF_12.D ;
  wire \DFF_12.Q ;
  wire \DFF_13.CK ;
  wire \DFF_13.D ;
  wire \DFF_13.Q ;
  wire \DFF_14.CK ;
  wire \DFF_14.D ;
  wire \DFF_14.Q ;
  wire \DFF_15.CK ;
  wire \DFF_15.D ;
  wire \DFF_15.Q ;
  wire \DFF_16.CK ;
  wire \DFF_16.D ;
  wire \DFF_16.Q ;
  wire \DFF_17.CK ;
  wire \DFF_17.D ;
  wire \DFF_17.Q ;
  wire \DFF_18.CK ;
  wire \DFF_18.D ;
  wire \DFF_18.Q ;
  wire \DFF_19.CK ;
  wire \DFF_19.D ;
  wire \DFF_19.Q ;
  wire \DFF_2.CK ;
  wire \DFF_2.D ;
  wire \DFF_20.CK ;
  wire \DFF_20.D ;
  wire \DFF_20.Q ;
  wire \DFF_21.CK ;
  wire \DFF_21.D ;
  wire \DFF_21.Q ;
  wire \DFF_22.CK ;
  wire \DFF_22.D ;
  wire \DFF_22.Q ;
  wire \DFF_23.CK ;
  wire \DFF_23.D ;
  wire \DFF_23.Q ;
  wire \DFF_24.CK ;
  wire \DFF_24.D ;
  wire \DFF_24.Q ;
  wire \DFF_25.CK ;
  wire \DFF_25.D ;
  wire \DFF_25.Q ;
  wire \DFF_26.CK ;
  wire \DFF_26.D ;
  wire \DFF_26.Q ;
  wire \DFF_27.CK ;
  wire \DFF_27.D ;
  wire \DFF_27.Q ;
  wire \DFF_28.CK ;
  wire \DFF_28.D ;
  wire \DFF_28.Q ;
  wire \DFF_3.CK ;
  wire \DFF_3.D ;
  wire \DFF_4.CK ;
  wire \DFF_4.D ;
  wire \DFF_5.CK ;
  wire \DFF_5.D ;
  wire \DFF_6.CK ;
  wire \DFF_6.D ;
  wire \DFF_6.Q ;
  wire \DFF_7.CK ;
  wire \DFF_7.D ;
  wire \DFF_7.Q ;
  wire \DFF_8.CK ;
  wire \DFF_8.D ;
  wire \DFF_8.Q ;
  wire \DFF_9.CK ;
  wire \DFF_9.D ;
  wire \DFF_9.Q ;
  output DumpIIHS1;
  wire DumpIIHS1;
  input FullIIHS1;
  wire FullIIHS1;
  input FullOHS1;
  wire FullOHS1;
  input GND;
  wire GND;
  output GoBmHS1;
  wire GoBmHS1;
  output GoRtHS1;
  wire GoRtHS1;
  wire II10;
  wire II11;
  wire II12;
  wire II13;
  wire II14;
  wire II15;
  wire II16;
  wire II17;
  wire II18;
  wire II19;
  wire II2;
  wire II20;
  wire II21;
  wire II22;
  wire II23;
  wire II24;
  wire II25;
  wire II26;
  wire II27;
  wire II28;
  wire II29;
  wire II3;
  wire II30;
  wire II322;
  wire II4;
  wire II414;
  wire II5;
  wire II6;
  wire II7;
  wire II8;
  wire II9;
  input IInDoneHS1;
  wire IInDoneHS1;
  output LdProgHS1;
  wire LdProgHS1;
  output LoadIIHHS1;
  wire LoadIIHHS1;
  output LoadOHHS1;
  wire LoadOHHS1;
  output LxHIInHS1;
  wire LxHIInHS1;
  output Mode0HS1;
  wire Mode0HS1;
  output Mode1HS1;
  wire Mode1HS1;
  output Mode2HS1;
  wire Mode2HS1;
  output NewLineHS1;
  wire NewLineHS1;
  output NewTrHS1;
  wire NewTrHS1;
  input OutAvHS1;
  wire OutAvHS1;
  input OutputHS1;
  wire OutputHS1;
  input Prog_0;
  wire Prog_0;
  input Prog_1;
  wire Prog_1;
  input Prog_2;
  wire Prog_2;
  input Rdy1BmHS1;
  wire Rdy1BmHS1;
  input Rdy1RtHS1;
  wire Rdy1RtHS1;
  input Rdy2BmHS1;
  wire Rdy2BmHS1;
  input Rdy2RtHS1;
  wire Rdy2RtHS1;
  output ReRtTSHS1;
  wire ReRtTSHS1;
  output ReWhBufHS1;
  wire ReWhBufHS1;
  input RtTSHS1;
  wire RtTSHS1;
  output SeFullIIHS1;
  wire SeFullIIHS1;
  output SeFullOHS1;
  wire SeFullOHS1;
  output SeOutAvHS1;
  wire SeOutAvHS1;
  output ShftIIRHS1;
  wire ShftIIRHS1;
  output ShftORHS1;
  wire ShftORHS1;
  output TgWhBufHS1;
  wire TgWhBufHS1;
  input TpArrayHS1;
  wire TpArrayHS1;
  output TxHIInHS1;
  wire TxHIInHS1;
  input VDD;
  wire VDD;
  input WantBmHS1;
  wire WantBmHS1;
  input WantRtHS1;
  wire WantRtHS1;
  INVx1_ASAP7_75t_L _203_ (
    .A(Prog_2),
    .Y(_201_)
  );
  INVx1_ASAP7_75t_L _204_ (
    .A(_001_),
    .Y(_202_)
  );
  INVx1_ASAP7_75t_L _205_ (
    .A(_000_),
    .Y(_029_)
  );
  INVx1_ASAP7_75t_L _206_ (
    .A(_003_),
    .Y(_030_)
  );
  INVx1_ASAP7_75t_L _207_ (
    .A(_002_),
    .Y(_031_)
  );
  INVx1_ASAP7_75t_L _208_ (
    .A(_004_),
    .Y(_032_)
  );
  INVx1_ASAP7_75t_L _209_ (
    .A(FullOHS1),
    .Y(_033_)
  );
  INVx1_ASAP7_75t_L _210_ (
    .A(FullIIHS1),
    .Y(_034_)
  );
  INVx1_ASAP7_75t_L _211_ (
    .A(Rdy2BmHS1),
    .Y(_035_)
  );
  INVx1_ASAP7_75t_L _212_ (
    .A(Rdy1BmHS1),
    .Y(_036_)
  );
  INVx1_ASAP7_75t_L _213_ (
    .A(IInDoneHS1),
    .Y(_037_)
  );
  INVx1_ASAP7_75t_L _214_ (
    .A(Rdy1RtHS1),
    .Y(_038_)
  );
  INVx1_ASAP7_75t_L _215_ (
    .A(Rdy2RtHS1),
    .Y(_039_)
  );
  INVx1_ASAP7_75t_L _216_ (
    .A(Prog_0),
    .Y(_040_)
  );
  INVx1_ASAP7_75t_L _217_ (
    .A(WantBmHS1),
    .Y(_041_)
  );
  INVx1_ASAP7_75t_L _218_ (
    .A(_005_),
    .Y(_042_)
  );
  INVx1_ASAP7_75t_L _219_ (
    .A(_006_),
    .Y(ReRtTSHS1)
  );
  INVx1_ASAP7_75t_L _220_ (
    .A(_007_),
    .Y(Mode1HS1)
  );
  INVx1_ASAP7_75t_L _221_ (
    .A(_008_),
    .Y(NewLineHS1)
  );
  INVx1_ASAP7_75t_L _222_ (
    .A(_009_),
    .Y(Mode0HS1)
  );
  INVx1_ASAP7_75t_L _223_ (
    .A(_010_),
    .Y(Mode2HS1)
  );
  INVx1_ASAP7_75t_L _224_ (
    .A(_011_),
    .Y(ShftIIRHS1)
  );
  INVx1_ASAP7_75t_L _225_ (
    .A(_012_),
    .Y(LxHIInHS1)
  );
  INVx1_ASAP7_75t_L _226_ (
    .A(_013_),
    .Y(ShftORHS1)
  );
  INVx1_ASAP7_75t_L _227_ (
    .A(_014_),
    .Y(TxHIInHS1)
  );
  INVx1_ASAP7_75t_L _228_ (
    .A(_015_),
    .Y(LoadIIHHS1)
  );
  INVx1_ASAP7_75t_L _229_ (
    .A(_016_),
    .Y(LoadOHHS1)
  );
  INVx1_ASAP7_75t_L _230_ (
    .A(_017_),
    .Y(SeOutAvHS1)
  );
  INVx1_ASAP7_75t_L _231_ (
    .A(_018_),
    .Y(TgWhBufHS1)
  );
  INVx1_ASAP7_75t_L _232_ (
    .A(_019_),
    .Y(LdProgHS1)
  );
  INVx1_ASAP7_75t_L _233_ (
    .A(_020_),
    .Y(SeFullIIHS1)
  );
  INVx1_ASAP7_75t_L _234_ (
    .A(_021_),
    .Y(ReWhBufHS1)
  );
  INVx1_ASAP7_75t_L _235_ (
    .A(_022_),
    .Y(SeFullOHS1)
  );
  INVx1_ASAP7_75t_L _236_ (
    .A(_023_),
    .Y(DumpIIHS1)
  );
  INVx1_ASAP7_75t_L _237_ (
    .A(_024_),
    .Y(NewTrHS1)
  );
  INVx1_ASAP7_75t_L _238_ (
    .A(_025_),
    .Y(ActBmHS1)
  );
  INVx1_ASAP7_75t_L _239_ (
    .A(_026_),
    .Y(GoBmHS1)
  );
  INVx1_ASAP7_75t_L _240_ (
    .A(_027_),
    .Y(GoRtHS1)
  );
  INVx1_ASAP7_75t_L _241_ (
    .A(_028_),
    .Y(ActRtHS1)
  );
  NOR2xp33_ASAP7_75t_L _242_ (
    .A(_202_),
    .B(_005_),
    .Y(_043_)
  );
  NAND2xp33_ASAP7_75t_L _243_ (
    .A(_001_),
    .B(_042_),
    .Y(_044_)
  );
  AND2x2_ASAP7_75t_L _244_ (
    .A(_001_),
    .B(_003_),
    .Y(_045_)
  );
  NAND2xp33_ASAP7_75t_L _245_ (
    .A(_001_),
    .B(_003_),
    .Y(_046_)
  );
  NAND2xp33_ASAP7_75t_L _246_ (
    .A(_042_),
    .B(_045_),
    .Y(_047_)
  );
  NAND3xp33_ASAP7_75t_L _247_ (
    .A(_004_),
    .B(_042_),
    .C(_045_),
    .Y(_048_)
  );
  NAND2xp33_ASAP7_75t_L _248_ (
    .A(_000_),
    .B(_004_),
    .Y(_049_)
  );
  NOR3xp33_ASAP7_75t_L _249_ (
    .A(_005_),
    .B(_046_),
    .C(_049_),
    .Y(_050_)
  );
  OR3x1_ASAP7_75t_L _250_ (
    .A(_005_),
    .B(_046_),
    .C(_049_),
    .Y(_051_)
  );
  NAND2xp33_ASAP7_75t_L _251_ (
    .A(_031_),
    .B(_050_),
    .Y(_052_)
  );
  INVx1_ASAP7_75t_L _252_ (
    .A(_052_),
    .Y(\DFF_14.D )
  );
  NOR2xp33_ASAP7_75t_L _253_ (
    .A(Prog_2),
    .B(_031_),
    .Y(_053_)
  );
  NAND2xp33_ASAP7_75t_L _254_ (
    .A(_201_),
    .B(_002_),
    .Y(_054_)
  );
  NAND2xp33_ASAP7_75t_L _255_ (
    .A(_000_),
    .B(_032_),
    .Y(_055_)
  );
  INVx1_ASAP7_75t_L _256_ (
    .A(_055_),
    .Y(_056_)
  );
  NAND3xp33_ASAP7_75t_L _257_ (
    .A(_001_),
    .B(_000_),
    .C(_032_),
    .Y(_057_)
  );
  NOR4xp25_ASAP7_75t_L _258_ (
    .A(_202_),
    .B(_029_),
    .C(_004_),
    .D(_005_),
    .Y(_058_)
  );
  NAND3xp33_ASAP7_75t_L _259_ (
    .A(_003_),
    .B(_053_),
    .C(_058_),
    .Y(_059_)
  );
  NAND2xp33_ASAP7_75t_L _260_ (
    .A(_052_),
    .B(_059_),
    .Y(\DFF_17.D )
  );
  NOR2xp33_ASAP7_75t_L _261_ (
    .A(_003_),
    .B(_031_),
    .Y(_060_)
  );
  NAND2xp33_ASAP7_75t_L _262_ (
    .A(_002_),
    .B(_005_),
    .Y(_061_)
  );
  OR3x1_ASAP7_75t_L _263_ (
    .A(_029_),
    .B(_003_),
    .C(_061_),
    .Y(_062_)
  );
  OR3x1_ASAP7_75t_L _264_ (
    .A(_001_),
    .B(_030_),
    .C(_061_),
    .Y(_063_)
  );
  NAND2xp33_ASAP7_75t_L _265_ (
    .A(_002_),
    .B(_004_),
    .Y(_064_)
  );
  OA22x2_ASAP7_75t_L _266_ (
    .A1(_049_),
    .A2(_061_),
    .B1(_063_),
    .B2(_000_),
    .Y(_065_)
  );
  AOI21xp33_ASAP7_75t_L _267_ (
    .A1(_062_),
    .A2(_065_),
    .B(_001_),
    .Y(\DFF_10.D )
  );
  NAND2xp33_ASAP7_75t_L _268_ (
    .A(_029_),
    .B(_004_),
    .Y(_066_)
  );
  NOR2xp33_ASAP7_75t_L _269_ (
    .A(_000_),
    .B(_004_),
    .Y(_067_)
  );
  XNOR2xp5_ASAP7_75t_L _270_ (
    .A(_000_),
    .B(_004_),
    .Y(_068_)
  );
  NOR5xp2_ASAP7_75t_L _271_ (
    .A(Prog_2),
    .B(_202_),
    .C(_031_),
    .D(_005_),
    .E(_068_),
    .Y(_069_)
  );
  AOI21xp33_ASAP7_75t_L _272_ (
    .A1(_000_),
    .A2(_004_),
    .B(_003_),
    .Y(_070_)
  );
  OAI21xp33_ASAP7_75t_L _273_ (
    .A1(_000_),
    .A2(_004_),
    .B(_070_),
    .Y(_071_)
  );
  NOR2xp33_ASAP7_75t_L _274_ (
    .A(_044_),
    .B(_071_),
    .Y(_072_)
  );
  OR2x2_ASAP7_75t_L _275_ (
    .A(_044_),
    .B(_071_),
    .Y(_073_)
  );
  AO221x1_ASAP7_75t_L _276_ (
    .A1(Prog_1),
    .A2(\DFF_14.D ),
    .B1(_072_),
    .B2(_002_),
    .C(_069_),
    .Y(\DFF_13.D )
  );
  NAND2xp33_ASAP7_75t_L _277_ (
    .A(Rdy2BmHS1),
    .B(Rdy1BmHS1),
    .Y(_074_)
  );
  NOR2xp33_ASAP7_75t_L _278_ (
    .A(FullOHS1),
    .B(FullIIHS1),
    .Y(_075_)
  );
  NOR4xp25_ASAP7_75t_L _279_ (
    .A(_029_),
    .B(FullOHS1),
    .C(FullIIHS1),
    .D(_074_),
    .Y(_076_)
  );
  NOR3xp33_ASAP7_75t_L _280_ (
    .A(_030_),
    .B(_042_),
    .C(_064_),
    .Y(_077_)
  );
  OA21x2_ASAP7_75t_L _281_ (
    .A1(_202_),
    .A2(_076_),
    .B(_077_),
    .Y(_078_)
  );
  NOR3xp33_ASAP7_75t_L _282_ (
    .A(_001_),
    .B(_061_),
    .C(_066_),
    .Y(_079_)
  );
  NOR3xp33_ASAP7_75t_L _283_ (
    .A(_001_),
    .B(_004_),
    .C(_062_),
    .Y(_080_)
  );
  NOR3xp33_ASAP7_75t_L _284_ (
    .A(_078_),
    .B(_079_),
    .C(_080_),
    .Y(_081_)
  );
  OAI31xp33_ASAP7_75t_L _285_ (
    .A1(_000_),
    .A2(TpArrayHS1),
    .A3(_063_),
    .B(_081_),
    .Y(\DFF_2.D )
  );
  AOI21xp33_ASAP7_75t_L _286_ (
    .A1(Prog_2),
    .A2(_075_),
    .B(_031_),
    .Y(_082_)
  );
  NAND2xp33_ASAP7_75t_L _287_ (
    .A(Rdy1RtHS1),
    .B(_039_),
    .Y(_083_)
  );
  NOR4xp25_ASAP7_75t_L _288_ (
    .A(_047_),
    .B(_055_),
    .C(_082_),
    .D(_083_),
    .Y(_084_)
  );
  NAND3xp33_ASAP7_75t_L _289_ (
    .A(_001_),
    .B(_004_),
    .C(RtTSHS1),
    .Y(_085_)
  );
  AOI31xp33_ASAP7_75t_L _290_ (
    .A1(_001_),
    .A2(_004_),
    .A3(RtTSHS1),
    .B(_062_),
    .Y(_086_)
  );
  AND3x1_ASAP7_75t_L _291_ (
    .A(_001_),
    .B(_076_),
    .C(_077_),
    .Y(_087_)
  );
  NOR2xp33_ASAP7_75t_L _292_ (
    .A(_044_),
    .B(_066_),
    .Y(_088_)
  );
  NAND3xp33_ASAP7_75t_L _293_ (
    .A(_029_),
    .B(_004_),
    .C(_043_),
    .Y(_089_)
  );
  NOR2xp33_ASAP7_75t_L _294_ (
    .A(Rdy2BmHS1),
    .B(_036_),
    .Y(_090_)
  );
  NOR5xp2_ASAP7_75t_L _295_ (
    .A(Rdy2BmHS1),
    .B(_036_),
    .C(_047_),
    .D(_066_),
    .E(_082_),
    .Y(_091_)
  );
  OAI32xp33_ASAP7_75t_L _296_ (
    .A1(_000_),
    .A2(_004_),
    .A3(_063_),
    .B1(_073_),
    .B2(IInDoneHS1),
    .Y(_092_)
  );
  OR3x1_ASAP7_75t_L _297_ (
    .A(_084_),
    .B(_086_),
    .C(_087_),
    .Y(_093_)
  );
  OR3x1_ASAP7_75t_L _298_ (
    .A(_091_),
    .B(_092_),
    .C(_093_),
    .Y(\DFF_3.D )
  );
  A2O1A1Ixp33_ASAP7_75t_L _299_ (
    .A1(Prog_0),
    .A2(_053_),
    .B(_030_),
    .C(_058_),
    .Y(_094_)
  );
  NOR3xp33_ASAP7_75t_L _300_ (
    .A(_044_),
    .B(_054_),
    .C(_066_),
    .Y(_095_)
  );
  NAND3xp33_ASAP7_75t_L _301_ (
    .A(_003_),
    .B(Prog_0),
    .C(_095_),
    .Y(_096_)
  );
  NAND3xp33_ASAP7_75t_L _302_ (
    .A(_052_),
    .B(_094_),
    .C(_096_),
    .Y(\DFF_6.D )
  );
  A2O1A1Ixp33_ASAP7_75t_L _303_ (
    .A1(_040_),
    .A2(_053_),
    .B(_060_),
    .C(_058_),
    .Y(_097_)
  );
  OAI211xp5_ASAP7_75t_L _304_ (
    .A1(_040_),
    .A2(_052_),
    .B(_096_),
    .C(_097_),
    .Y(\DFF_12.D )
  );
  NOR3xp33_ASAP7_75t_L _305_ (
    .A(_031_),
    .B(_005_),
    .C(_046_),
    .Y(_098_)
  );
  NAND3xp33_ASAP7_75t_L _306_ (
    .A(_029_),
    .B(_036_),
    .C(_098_),
    .Y(_099_)
  );
  NOR2xp33_ASAP7_75t_L _307_ (
    .A(_029_),
    .B(_047_),
    .Y(_100_)
  );
  NAND3xp33_ASAP7_75t_L _308_ (
    .A(_000_),
    .B(_042_),
    .C(_045_),
    .Y(_101_)
  );
  NOR2xp33_ASAP7_75t_L _309_ (
    .A(FullIIHS1),
    .B(Rdy1BmHS1),
    .Y(_102_)
  );
  AOI21xp33_ASAP7_75t_L _310_ (
    .A1(_033_),
    .A2(Rdy2BmHS1),
    .B(_102_),
    .Y(_103_)
  );
  NOR2xp33_ASAP7_75t_L _311_ (
    .A(FullOHS1),
    .B(Rdy1RtHS1),
    .Y(_104_)
  );
  A2O1A1Ixp33_ASAP7_75t_L _312_ (
    .A1(_034_),
    .A2(Rdy2RtHS1),
    .B(_104_),
    .C(Prog_0),
    .Y(_105_)
  );
  OAI21xp33_ASAP7_75t_L _313_ (
    .A1(Prog_0),
    .A2(_103_),
    .B(_105_),
    .Y(_106_)
  );
  NAND3xp33_ASAP7_75t_L _314_ (
    .A(_201_),
    .B(_100_),
    .C(_106_),
    .Y(_107_)
  );
  NAND3xp33_ASAP7_75t_L _315_ (
    .A(_065_),
    .B(_099_),
    .C(_107_),
    .Y(\DFF_19.D )
  );
  NOR4xp25_ASAP7_75t_L _316_ (
    .A(_031_),
    .B(_005_),
    .C(_046_),
    .D(_075_),
    .Y(_108_)
  );
  NOR2xp33_ASAP7_75t_L _317_ (
    .A(Prog_0),
    .B(_048_),
    .Y(_109_)
  );
  OAI21xp33_ASAP7_75t_L _318_ (
    .A1(_088_),
    .A2(_109_),
    .B(_074_),
    .Y(_110_)
  );
  NAND2xp33_ASAP7_75t_L _319_ (
    .A(Rdy1RtHS1),
    .B(Rdy2RtHS1),
    .Y(_111_)
  );
  A2O1A1Ixp33_ASAP7_75t_L _320_ (
    .A1(Prog_0),
    .A2(_100_),
    .B(_058_),
    .C(_111_),
    .Y(_112_)
  );
  NOR4xp25_ASAP7_75t_L _321_ (
    .A(_029_),
    .B(_003_),
    .C(_061_),
    .D(_085_),
    .Y(\DFF_11.D )
  );
  NAND2xp33_ASAP7_75t_L _322_ (
    .A(Prog_1),
    .B(\DFF_11.D ),
    .Y(_113_)
  );
  OAI31xp33_ASAP7_75t_L _323_ (
    .A1(_050_),
    .A2(_108_),
    .A3(\DFF_11.D ),
    .B(Prog_2),
    .Y(_114_)
  );
  NAND2xp33_ASAP7_75t_L _324_ (
    .A(_029_),
    .B(_108_),
    .Y(_115_)
  );
  AOI311xp33_ASAP7_75t_L _325_ (
    .A1(_036_),
    .A2(_038_),
    .A3(_098_),
    .B(_069_),
    .C(\DFF_14.D ),
    .Y(_116_)
  );
  AND5x1_ASAP7_75t_L _326_ (
    .A(_073_),
    .B(_113_),
    .C(_114_),
    .D(_115_),
    .E(_116_),
    .Y(_117_)
  );
  NAND3xp33_ASAP7_75t_L _327_ (
    .A(_110_),
    .B(_112_),
    .C(_117_),
    .Y(\DFF_0.D )
  );
  O2A1O1Ixp33_ASAP7_75t_L _328_ (
    .A1(_054_),
    .A2(_089_),
    .B(_059_),
    .C(Prog_0),
    .Y(_118_)
  );
  OAI21xp33_ASAP7_75t_L _329_ (
    .A1(_003_),
    .A2(_089_),
    .B(_052_),
    .Y(_119_)
  );
  OR3x1_ASAP7_75t_L _330_ (
    .A(\DFF_10.D ),
    .B(_118_),
    .C(_119_),
    .Y(\DFF_7.D )
  );
  NAND2xp33_ASAP7_75t_L _331_ (
    .A(FullOHS1),
    .B(FullIIHS1),
    .Y(_120_)
  );
  NOR2xp33_ASAP7_75t_L _332_ (
    .A(_035_),
    .B(Rdy1BmHS1),
    .Y(_121_)
  );
  NAND2xp33_ASAP7_75t_L _333_ (
    .A(Rdy2BmHS1),
    .B(_036_),
    .Y(_122_)
  );
  XNOR2xp5_ASAP7_75t_L _334_ (
    .A(Rdy2BmHS1),
    .B(Rdy1BmHS1),
    .Y(_123_)
  );
  OR4x1_ASAP7_75t_L _335_ (
    .A(Prog_0),
    .B(_051_),
    .C(_054_),
    .D(_123_),
    .Y(_124_)
  );
  AOI21xp33_ASAP7_75t_L _336_ (
    .A1(FullOHS1),
    .A2(FullIIHS1),
    .B(_124_),
    .Y(_125_)
  );
  NOR4xp25_ASAP7_75t_L _337_ (
    .A(_201_),
    .B(_032_),
    .C(_005_),
    .D(_046_),
    .Y(_126_)
  );
  OAI21xp33_ASAP7_75t_L _338_ (
    .A1(_038_),
    .A2(Rdy2RtHS1),
    .B(WantRtHS1),
    .Y(_127_)
  );
  AND4x1_ASAP7_75t_L _339_ (
    .A(_067_),
    .B(_098_),
    .C(_102_),
    .D(_104_),
    .Y(_128_)
  );
  AND5x1_ASAP7_75t_L _340_ (
    .A(_002_),
    .B(_075_),
    .C(_090_),
    .D(_126_),
    .E(_127_),
    .Y(_129_)
  );
  AO21x1_ASAP7_75t_L _341_ (
    .A1(WantBmHS1),
    .A2(_129_),
    .B(_087_),
    .Y(_130_)
  );
  NAND4xp25_ASAP7_75t_L _342_ (
    .A(_002_),
    .B(_034_),
    .C(_042_),
    .D(_045_),
    .Y(_131_)
  );
  OR4x1_ASAP7_75t_L _343_ (
    .A(_091_),
    .B(_125_),
    .C(_128_),
    .D(_130_),
    .Y(\DFF_9.D )
  );
  OAI21xp33_ASAP7_75t_L _344_ (
    .A1(Rdy2BmHS1),
    .A2(_036_),
    .B(WantBmHS1),
    .Y(_132_)
  );
  XOR2xp5_ASAP7_75t_L _345_ (
    .A(Prog_1),
    .B(Prog_0),
    .Y(_133_)
  );
  AOI21xp33_ASAP7_75t_L _346_ (
    .A1(Rdy2BmHS1),
    .A2(_133_),
    .B(_132_),
    .Y(_134_)
  );
  NAND4xp25_ASAP7_75t_L _347_ (
    .A(Prog_2),
    .B(_000_),
    .C(_002_),
    .D(_075_),
    .Y(_135_)
  );
  AOI31xp33_ASAP7_75t_L _348_ (
    .A1(Rdy2RtHS1),
    .A2(Prog_0),
    .A3(_132_),
    .B(_127_),
    .Y(_136_)
  );
  OR4x1_ASAP7_75t_L _349_ (
    .A(_048_),
    .B(_134_),
    .C(_135_),
    .D(_136_),
    .Y(_137_)
  );
  OAI221xp5_ASAP7_75t_L _350_ (
    .A1(Rdy2RtHS1),
    .A2(_055_),
    .B1(_066_),
    .B2(Rdy2BmHS1),
    .C(_071_),
    .Y(_138_)
  );
  NAND3xp33_ASAP7_75t_L _351_ (
    .A(_031_),
    .B(_043_),
    .C(_138_),
    .Y(_139_)
  );
  OAI211xp5_ASAP7_75t_L _352_ (
    .A1(IInDoneHS1),
    .A2(_052_),
    .B(_137_),
    .C(_139_),
    .Y(\DFF_1.D )
  );
  NOR3xp33_ASAP7_75t_L _353_ (
    .A(Prog_2),
    .B(_064_),
    .C(_101_),
    .Y(_140_)
  );
  NOR4xp25_ASAP7_75t_L _354_ (
    .A(Prog_2),
    .B(FullOHS1),
    .C(_064_),
    .D(_101_),
    .Y(_141_)
  );
  NAND2xp33_ASAP7_75t_L _355_ (
    .A(_038_),
    .B(Rdy2RtHS1),
    .Y(_142_)
  );
  NAND2xp33_ASAP7_75t_L _356_ (
    .A(_083_),
    .B(_142_),
    .Y(_143_)
  );
  NOR4xp25_ASAP7_75t_L _357_ (
    .A(_038_),
    .B(Rdy2RtHS1),
    .C(_047_),
    .D(_135_),
    .Y(_144_)
  );
  NOR3xp33_ASAP7_75t_L _358_ (
    .A(WantRtHS1),
    .B(_048_),
    .C(_135_),
    .Y(_145_)
  );
  INVx1_ASAP7_75t_L _359_ (
    .A(_145_),
    .Y(_146_)
  );
  OAI21xp33_ASAP7_75t_L _360_ (
    .A1(_144_),
    .A2(_145_),
    .B(_041_),
    .Y(_147_)
  );
  NAND2xp33_ASAP7_75t_L _361_ (
    .A(Prog_2),
    .B(_033_),
    .Y(_148_)
  );
  NAND4xp25_ASAP7_75t_L _362_ (
    .A(_029_),
    .B(_004_),
    .C(_035_),
    .D(Rdy1BmHS1),
    .Y(_149_)
  );
  NAND4xp25_ASAP7_75t_L _363_ (
    .A(_000_),
    .B(_032_),
    .C(Rdy1RtHS1),
    .D(_039_),
    .Y(_150_)
  );
  AOI211xp5_ASAP7_75t_L _364_ (
    .A1(_149_),
    .A2(_150_),
    .B(_131_),
    .C(_148_),
    .Y(_151_)
  );
  AOI21xp33_ASAP7_75t_L _365_ (
    .A1(TpArrayHS1),
    .A2(_067_),
    .B(_030_),
    .Y(_152_)
  );
  NOR4xp25_ASAP7_75t_L _366_ (
    .A(_001_),
    .B(_061_),
    .C(_070_),
    .D(_152_),
    .Y(_153_)
  );
  NOR4xp25_ASAP7_75t_L _367_ (
    .A(_128_),
    .B(_129_),
    .C(_151_),
    .D(_153_),
    .Y(_154_)
  );
  NOR5xp2_ASAP7_75t_L _368_ (
    .A(FullOHS1),
    .B(Prog_0),
    .C(_051_),
    .D(_054_),
    .E(_123_),
    .Y(_155_)
  );
  AOI31xp33_ASAP7_75t_L _369_ (
    .A1(Prog_0),
    .A2(_141_),
    .A3(_143_),
    .B(_155_),
    .Y(_156_)
  );
  NAND3xp33_ASAP7_75t_L _370_ (
    .A(_147_),
    .B(_154_),
    .C(_156_),
    .Y(\DFF_20.D )
  );
  NAND2xp33_ASAP7_75t_L _371_ (
    .A(Rdy2BmHS1),
    .B(WantBmHS1),
    .Y(_157_)
  );
  NOR5xp2_ASAP7_75t_L _372_ (
    .A(WantRtHS1),
    .B(_048_),
    .C(_133_),
    .D(_135_),
    .E(_157_),
    .Y(_158_)
  );
  NOR3xp33_ASAP7_75t_L _373_ (
    .A(_039_),
    .B(_048_),
    .C(_135_),
    .Y(_159_)
  );
  NAND2xp33_ASAP7_75t_L _374_ (
    .A(WantRtHS1),
    .B(_159_),
    .Y(_160_)
  );
  OAI33xp33_ASAP7_75t_L _375_ (
    .A1(_133_),
    .A2(_146_),
    .A3(_157_),
    .B1(_160_),
    .B2(Prog_0),
    .B3(WantBmHS1),
    .Y(\DFF_28.D )
  );
  NOR4xp25_ASAP7_75t_L _376_ (
    .A(_032_),
    .B(_038_),
    .C(_047_),
    .D(_135_),
    .Y(_161_)
  );
  OAI311xp33_ASAP7_75t_L _377_ (
    .A1(_145_),
    .A2(_159_),
    .A3(_161_),
    .B1(WantBmHS1),
    .C1(Rdy2BmHS1),
    .Y(_162_)
  );
  OAI21xp33_ASAP7_75t_L _378_ (
    .A1(_038_),
    .A2(Rdy2RtHS1),
    .B(Prog_0),
    .Y(_163_)
  );
  OA21x2_ASAP7_75t_L _379_ (
    .A1(Prog_0),
    .A2(_090_),
    .B(_163_),
    .Y(_164_)
  );
  NOR2xp33_ASAP7_75t_L _380_ (
    .A(_033_),
    .B(FullIIHS1),
    .Y(_165_)
  );
  NAND3xp33_ASAP7_75t_L _381_ (
    .A(_140_),
    .B(_164_),
    .C(_165_),
    .Y(_166_)
  );
  NAND2xp33_ASAP7_75t_L _382_ (
    .A(_201_),
    .B(IInDoneHS1),
    .Y(_167_)
  );
  AO21x1_ASAP7_75t_L _383_ (
    .A1(_082_),
    .A2(_167_),
    .B(_030_),
    .Y(_168_)
  );
  A2O1A1Ixp33_ASAP7_75t_L _384_ (
    .A1(_054_),
    .A2(_111_),
    .B(_168_),
    .C(_058_),
    .Y(_169_)
  );
  NOR4xp25_ASAP7_75t_L _385_ (
    .A(_047_),
    .B(_066_),
    .C(_082_),
    .D(_122_),
    .Y(_170_)
  );
  NAND3xp33_ASAP7_75t_L _386_ (
    .A(_030_),
    .B(_002_),
    .C(_111_),
    .Y(_171_)
  );
  OAI22xp33_ASAP7_75t_L _387_ (
    .A1(_000_),
    .A2(_063_),
    .B1(_171_),
    .B2(_057_),
    .Y(_172_)
  );
  AND2x2_ASAP7_75t_L _388_ (
    .A(_067_),
    .B(_108_),
    .Y(_173_)
  );
  NOR4xp25_ASAP7_75t_L _389_ (
    .A(_001_),
    .B(_004_),
    .C(IInDoneHS1),
    .D(_062_),
    .Y(_174_)
  );
  NOR4xp25_ASAP7_75t_L _390_ (
    .A(_170_),
    .B(_172_),
    .C(_173_),
    .D(_174_),
    .Y(_175_)
  );
  NAND4xp25_ASAP7_75t_L _391_ (
    .A(_162_),
    .B(_166_),
    .C(_169_),
    .D(_175_),
    .Y(\DFF_4.D )
  );
  AOI221xp5_ASAP7_75t_L _392_ (
    .A1(OutputHS1),
    .A2(\DFF_14.D ),
    .B1(_072_),
    .B2(_002_),
    .C(_095_),
    .Y(_176_)
  );
  NOR5xp2_ASAP7_75t_L _393_ (
    .A(FullOHS1),
    .B(Prog_0),
    .C(_051_),
    .D(_054_),
    .E(_122_),
    .Y(_177_)
  );
  NOR3xp33_ASAP7_75t_L _394_ (
    .A(_128_),
    .B(_153_),
    .C(_177_),
    .Y(_178_)
  );
  NAND4xp25_ASAP7_75t_L _395_ (
    .A(_038_),
    .B(Rdy2RtHS1),
    .C(Prog_0),
    .D(_141_),
    .Y(_179_)
  );
  OAI211xp5_ASAP7_75t_L _396_ (
    .A1(_037_),
    .A2(_176_),
    .B(_178_),
    .C(_179_),
    .Y(\DFF_23.D )
  );
  NOR2xp33_ASAP7_75t_L _397_ (
    .A(FullIIHS1),
    .B(OutAvHS1),
    .Y(\DFF_26.D )
  );
  NOR2xp33_ASAP7_75t_L _398_ (
    .A(_034_),
    .B(OutAvHS1),
    .Y(\DFF_25.D )
  );
  NOR2xp33_ASAP7_75t_L _399_ (
    .A(OutAvHS1),
    .B(_075_),
    .Y(\DFF_22.D )
  );
  NOR2xp33_ASAP7_75t_L _400_ (
    .A(_049_),
    .B(_063_),
    .Y(\DFF_27.D )
  );
  AOI211xp5_ASAP7_75t_L _401_ (
    .A1(_002_),
    .A2(_072_),
    .B(_080_),
    .C(_095_),
    .Y(_180_)
  );
  OAI211xp5_ASAP7_75t_L _402_ (
    .A1(_056_),
    .A2(_063_),
    .B(_180_),
    .C(_052_),
    .Y(\DFF_16.D )
  );
  A2O1A1Ixp33_ASAP7_75t_L _403_ (
    .A1(_109_),
    .A2(_120_),
    .B(_126_),
    .C(_035_),
    .Y(_181_)
  );
  NOR2xp33_ASAP7_75t_L _404_ (
    .A(Rdy2RtHS1),
    .B(_101_),
    .Y(_182_)
  );
  A2O1A1Ixp33_ASAP7_75t_L _405_ (
    .A1(Prog_0),
    .A2(_120_),
    .B(Prog_2),
    .C(_182_),
    .Y(_183_)
  );
  OR4x1_ASAP7_75t_L _406_ (
    .A(_201_),
    .B(_029_),
    .C(_046_),
    .D(_064_),
    .Y(_184_)
  );
  NAND4xp25_ASAP7_75t_L _407_ (
    .A(_065_),
    .B(_181_),
    .C(_183_),
    .D(_184_),
    .Y(\DFF_18.D )
  );
  AO21x1_ASAP7_75t_L _408_ (
    .A1(Prog_2),
    .A2(\DFF_11.D ),
    .B(_128_),
    .Y(_185_)
  );
  OR4x1_ASAP7_75t_L _409_ (
    .A(_087_),
    .B(_140_),
    .C(_151_),
    .D(_185_),
    .Y(\DFF_15.D )
  );
  A2O1A1Ixp33_ASAP7_75t_L _410_ (
    .A1(_054_),
    .A2(_074_),
    .B(_168_),
    .C(_088_),
    .Y(_186_)
  );
  NOR4xp25_ASAP7_75t_L _411_ (
    .A(_047_),
    .B(_055_),
    .C(_082_),
    .D(_142_),
    .Y(_187_)
  );
  NOR3xp33_ASAP7_75t_L _412_ (
    .A(_078_),
    .B(_173_),
    .C(_187_),
    .Y(_188_)
  );
  NAND2xp33_ASAP7_75t_L _413_ (
    .A(_141_),
    .B(_164_),
    .Y(_189_)
  );
  OAI311xp33_ASAP7_75t_L _414_ (
    .A1(Rdy2BmHS1),
    .A2(Rdy1BmHS1),
    .A3(_041_),
    .B1(WantRtHS1),
    .C1(_159_),
    .Y(_190_)
  );
  NAND4xp25_ASAP7_75t_L _415_ (
    .A(_186_),
    .B(_188_),
    .C(_189_),
    .D(_190_),
    .Y(\DFF_5.D )
  );
  NOR3xp33_ASAP7_75t_L _416_ (
    .A(_004_),
    .B(_062_),
    .C(_111_),
    .Y(_191_)
  );
  AOI211xp5_ASAP7_75t_L _417_ (
    .A1(_001_),
    .A2(_191_),
    .B(_128_),
    .C(_084_),
    .Y(_192_)
  );
  NAND4xp25_ASAP7_75t_L _418_ (
    .A(Prog_0),
    .B(_120_),
    .C(_140_),
    .D(_143_),
    .Y(_193_)
  );
  NAND3xp33_ASAP7_75t_L _419_ (
    .A(WantRtHS1),
    .B(_132_),
    .C(_144_),
    .Y(_194_)
  );
  NAND3xp33_ASAP7_75t_L _420_ (
    .A(_192_),
    .B(_193_),
    .C(_194_),
    .Y(\DFF_8.D )
  );
  NAND4xp25_ASAP7_75t_L _421_ (
    .A(_121_),
    .B(_140_),
    .C(_163_),
    .D(_165_),
    .Y(_195_)
  );
  NOR4xp25_ASAP7_75t_L _422_ (
    .A(Prog_2),
    .B(_033_),
    .C(Rdy1RtHS1),
    .D(_040_),
    .Y(_196_)
  );
  NOR3xp33_ASAP7_75t_L _423_ (
    .A(Prog_0),
    .B(WantBmHS1),
    .C(_148_),
    .Y(_197_)
  );
  NOR3xp33_ASAP7_75t_L _424_ (
    .A(_039_),
    .B(_049_),
    .C(_131_),
    .Y(_198_)
  );
  A2O1A1O1Ixp25_ASAP7_75t_L _425_ (
    .A1(WantRtHS1),
    .A2(_197_),
    .B(_196_),
    .C(_198_),
    .D(_158_),
    .Y(_199_)
  );
  NAND3xp33_ASAP7_75t_L _426_ (
    .A(_166_),
    .B(_195_),
    .C(_199_),
    .Y(\DFF_21.D )
  );
  NAND5xp2_ASAP7_75t_L _427_ (
    .A(_040_),
    .B(_050_),
    .C(_053_),
    .D(_121_),
    .E(_165_),
    .Y(_200_)
  );
  OAI211xp5_ASAP7_75t_L _428_ (
    .A1(_037_),
    .A2(_059_),
    .B(_199_),
    .C(_200_),
    .Y(\DFF_24.D )
  );
  DFFHQNx1_ASAP7_75t_R _429_ (
    .CLK(CK),
    .D(\DFF_11.D ),
    .QN(_006_)
  );
  DFFHQNx1_ASAP7_75t_R _430_ (
    .CLK(CK),
    .D(\DFF_13.D ),
    .QN(_007_)
  );
  DFFHQNx1_ASAP7_75t_R _431_ (
    .CLK(CK),
    .D(\DFF_15.D ),
    .QN(_008_)
  );
  DFFHQNx1_ASAP7_75t_R _432_ (
    .CLK(CK),
    .D(\DFF_12.D ),
    .QN(_009_)
  );
  DFFHQNx1_ASAP7_75t_R _433_ (
    .CLK(CK),
    .D(\DFF_14.D ),
    .QN(_010_)
  );
  DFFHQNx1_ASAP7_75t_R _434_ (
    .CLK(CK),
    .D(\DFF_17.D ),
    .QN(_011_)
  );
  DFFHQNx1_ASAP7_75t_R _435_ (
    .CLK(CK),
    .D(\DFF_18.D ),
    .QN(_012_)
  );
  DFFHQNx1_ASAP7_75t_R _436_ (
    .CLK(CK),
    .D(\DFF_16.D ),
    .QN(_013_)
  );
  DFFHQNx1_ASAP7_75t_R _437_ (
    .CLK(CK),
    .D(\DFF_19.D ),
    .QN(_014_)
  );
  DFFHQNx1_ASAP7_75t_R _438_ (
    .CLK(CK),
    .D(\DFF_21.D ),
    .QN(_015_)
  );
  DFFHQNx1_ASAP7_75t_R _439_ (
    .CLK(CK),
    .D(\DFF_20.D ),
    .QN(_016_)
  );
  DFFHQNx1_ASAP7_75t_R _440_ (
    .CLK(CK),
    .D(\DFF_22.D ),
    .QN(_017_)
  );
  DFFHQNx1_ASAP7_75t_R _441_ (
    .CLK(CK),
    .D(\DFF_25.D ),
    .QN(_018_)
  );
  DFFHQNx1_ASAP7_75t_R _442_ (
    .CLK(CK),
    .D(\DFF_27.D ),
    .QN(_019_)
  );
  DFFHQNx1_ASAP7_75t_R _443_ (
    .CLK(CK),
    .D(\DFF_24.D ),
    .QN(_020_)
  );
  DFFHQNx1_ASAP7_75t_R _444_ (
    .CLK(CK),
    .D(\DFF_26.D ),
    .QN(_021_)
  );
  DFFHQNx1_ASAP7_75t_R _445_ (
    .CLK(CK),
    .D(\DFF_23.D ),
    .QN(_022_)
  );
  DFFHQNx1_ASAP7_75t_R _446_ (
    .CLK(CK),
    .D(\DFF_28.D ),
    .QN(_023_)
  );
  DFFHQNx1_ASAP7_75t_R _447_ (
    .CLK(CK),
    .D(\DFF_5.D ),
    .QN(_000_)
  );
  DFFHQNx1_ASAP7_75t_R _448_ (
    .CLK(CK),
    .D(\DFF_3.D ),
    .QN(_003_)
  );
  DFFHQNx1_ASAP7_75t_R _449_ (
    .CLK(CK),
    .D(\DFF_10.D ),
    .QN(_024_)
  );
  DFFHQNx1_ASAP7_75t_R _450_ (
    .CLK(CK),
    .D(\DFF_7.D ),
    .QN(_025_)
  );
  DFFHQNx1_ASAP7_75t_R _451_ (
    .CLK(CK),
    .D(\DFF_4.D ),
    .QN(_004_)
  );
  DFFHQNx1_ASAP7_75t_R _452_ (
    .CLK(CK),
    .D(\DFF_9.D ),
    .QN(_026_)
  );
  DFFHQNx1_ASAP7_75t_R _453_ (
    .CLK(CK),
    .D(\DFF_8.D ),
    .QN(_027_)
  );
  DFFHQNx1_ASAP7_75t_R _454_ (
    .CLK(CK),
    .D(\DFF_6.D ),
    .QN(_028_)
  );
  DFFHQNx1_ASAP7_75t_R _455_ (
    .CLK(CK),
    .D(\DFF_2.D ),
    .QN(_001_)
  );
  DFFHQNx1_ASAP7_75t_R _456_ (
    .CLK(CK),
    .D(\DFF_1.D ),
    .QN(_002_)
  );
  DFFHQNx1_ASAP7_75t_R _457_ (
    .CLK(CK),
    .D(\DFF_0.D ),
    .QN(_005_)
  );
  assign \DFF_0.CK  = CK;
  assign \DFF_1.CK  = CK;
  assign \DFF_10.CK  = CK;
  assign \DFF_10.Q  = NewTrHS1;
  assign \DFF_11.CK  = CK;
  assign \DFF_11.Q  = ReRtTSHS1;
  assign \DFF_12.CK  = CK;
  assign \DFF_12.Q  = Mode0HS1;
  assign \DFF_13.CK  = CK;
  assign \DFF_13.Q  = Mode1HS1;
  assign \DFF_14.CK  = CK;
  assign \DFF_14.Q  = Mode2HS1;
  assign \DFF_15.CK  = CK;
  assign \DFF_15.Q  = NewLineHS1;
  assign \DFF_16.CK  = CK;
  assign \DFF_16.Q  = ShftORHS1;
  assign \DFF_17.CK  = CK;
  assign \DFF_17.Q  = ShftIIRHS1;
  assign \DFF_18.CK  = CK;
  assign \DFF_18.Q  = LxHIInHS1;
  assign \DFF_19.CK  = CK;
  assign \DFF_19.Q  = TxHIInHS1;
  assign \DFF_2.CK  = CK;
  assign \DFF_20.CK  = CK;
  assign \DFF_20.Q  = LoadOHHS1;
  assign \DFF_21.CK  = CK;
  assign \DFF_21.Q  = LoadIIHHS1;
  assign \DFF_22.CK  = CK;
  assign \DFF_22.Q  = SeOutAvHS1;
  assign \DFF_23.CK  = CK;
  assign \DFF_23.Q  = SeFullOHS1;
  assign \DFF_24.CK  = CK;
  assign \DFF_24.Q  = SeFullIIHS1;
  assign \DFF_25.CK  = CK;
  assign \DFF_25.Q  = TgWhBufHS1;
  assign \DFF_26.CK  = CK;
  assign \DFF_26.Q  = ReWhBufHS1;
  assign \DFF_27.CK  = CK;
  assign \DFF_27.Q  = LdProgHS1;
  assign \DFF_28.CK  = CK;
  assign \DFF_28.Q  = DumpIIHS1;
  assign \DFF_3.CK  = CK;
  assign \DFF_4.CK  = CK;
  assign \DFF_5.CK  = CK;
  assign \DFF_6.CK  = CK;
  assign \DFF_6.Q  = ActRtHS1;
  assign \DFF_7.CK  = CK;
  assign \DFF_7.Q  = ActBmHS1;
  assign \DFF_8.CK  = CK;
  assign \DFF_8.Q  = GoRtHS1;
  assign \DFF_9.CK  = CK;
  assign \DFF_9.Q  = GoBmHS1;
  assign II10 = \DFF_8.D ;
  assign II11 = \DFF_9.D ;
  assign II12 = \DFF_10.D ;
  assign II13 = \DFF_11.D ;
  assign II14 = \DFF_12.D ;
  assign II15 = \DFF_13.D ;
  assign II16 = \DFF_14.D ;
  assign II17 = \DFF_15.D ;
  assign II18 = \DFF_16.D ;
  assign II19 = \DFF_17.D ;
  assign II2 = \DFF_0.D ;
  assign II20 = \DFF_18.D ;
  assign II21 = \DFF_19.D ;
  assign II22 = \DFF_20.D ;
  assign II23 = \DFF_21.D ;
  assign II24 = \DFF_22.D ;
  assign II25 = \DFF_23.D ;
  assign II26 = \DFF_24.D ;
  assign II27 = \DFF_25.D ;
  assign II28 = \DFF_26.D ;
  assign II29 = \DFF_27.D ;
  assign II3 = \DFF_1.D ;
  assign II30 = \DFF_28.D ;
  assign II322 = \DFF_14.D ;
  assign II4 = \DFF_2.D ;
  assign II414 = \DFF_11.D ;
  assign II5 = \DFF_3.D ;
  assign II6 = \DFF_4.D ;
  assign II7 = \DFF_5.D ;
  assign II8 = \DFF_6.D ;
  assign II9 = \DFF_7.D ;
endmodule
