/* Generated by Yosys 0.54+29 (git sha1 7b0c1fe49, g++ 9.4.0-1ubuntu1~20.04.2 -fPIC -O3) */

module s444(GND, VDD, CK, G0, G1, G107, G108, G118, G119, G167, G168, G2);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  input CK;
  wire CK;
  wire \DFF_0.CK ;
  wire \DFF_0.D ;
  wire \DFF_1.CK ;
  wire \DFF_1.D ;
  wire \DFF_10.CK ;
  wire \DFF_10.D ;
  wire \DFF_11.CK ;
  wire \DFF_11.D ;
  wire \DFF_12.CK ;
  wire \DFF_12.D ;
  wire \DFF_13.CK ;
  wire \DFF_13.D ;
  wire \DFF_14.CK ;
  wire \DFF_14.D ;
  wire \DFF_14.Q ;
  wire \DFF_15.CK ;
  wire \DFF_15.D ;
  wire \DFF_15.Q ;
  wire \DFF_16.CK ;
  wire \DFF_16.D ;
  wire \DFF_16.Q ;
  wire \DFF_17.CK ;
  wire \DFF_17.D ;
  wire \DFF_18.CK ;
  wire \DFF_18.D ;
  wire \DFF_19.CK ;
  wire \DFF_19.D ;
  wire \DFF_19.Q ;
  wire \DFF_2.CK ;
  wire \DFF_2.D ;
  wire \DFF_20.CK ;
  wire \DFF_20.D ;
  wire \DFF_3.CK ;
  wire \DFF_3.D ;
  wire \DFF_4.CK ;
  wire \DFF_4.D ;
  wire \DFF_5.CK ;
  wire \DFF_5.D ;
  wire \DFF_6.CK ;
  wire \DFF_6.D ;
  wire \DFF_7.CK ;
  wire \DFF_7.D ;
  wire \DFF_8.CK ;
  wire \DFF_8.D ;
  wire \DFF_9.CK ;
  wire \DFF_9.D ;
  input G0;
  wire G0;
  input G1;
  wire G1;
  wire G101;
  wire G106;
  output G107;
  wire G107;
  output G108;
  wire G108;
  wire G109;
  wire G110;
  wire G111;
  wire G112;
  wire G113;
  wire G114;
  output G118;
  wire G118;
  output G119;
  wire G119;
  wire G152;
  wire G155;
  wire G160;
  wire G162;
  wire G162BF;
  output G167;
  wire G167;
  output G168;
  wire G168;
  input G2;
  wire G2;
  wire G25;
  wire G26;
  wire G27;
  wire G30;
  wire G37;
  wire G41;
  wire G45;
  wire G49;
  wire G58;
  wire G62;
  wire G66;
  wire G70;
  wire G80;
  wire G84;
  wire G88;
  wire G92;
  input GND;
  wire GND;
  wire IIII181;
  input VDD;
  wire VDD;
  INVx1_ASAP7_75t_L _065_ (
    .A(G0),
    .Y(_030_)
  );
  INVx1_ASAP7_75t_L _066_ (
    .A(_003_),
    .Y(_031_)
  );
  INVx1_ASAP7_75t_L _067_ (
    .A(G2),
    .Y(_032_)
  );
  INVx1_ASAP7_75t_L _068_ (
    .A(_006_),
    .Y(_033_)
  );
  INVx1_ASAP7_75t_L _069_ (
    .A(_008_),
    .Y(_034_)
  );
  INVx1_ASAP7_75t_L _070_ (
    .A(_010_),
    .Y(_035_)
  );
  INVx1_ASAP7_75t_L _071_ (
    .A(_012_),
    .Y(G107)
  );
  INVx1_ASAP7_75t_L _072_ (
    .A(_013_),
    .Y(G108)
  );
  INVx1_ASAP7_75t_L _073_ (
    .A(_014_),
    .Y(_036_)
  );
  INVx1_ASAP7_75t_L _074_ (
    .A(_015_),
    .Y(G168)
  );
  INVx1_ASAP7_75t_L _075_ (
    .A(_016_),
    .Y(G118)
  );
  NAND2xp33_ASAP7_75t_L _076_ (
    .A(_031_),
    .B(_009_),
    .Y(_037_)
  );
  NOR2xp33_ASAP7_75t_L _077_ (
    .A(G0),
    .B(_001_),
    .Y(_038_)
  );
  NOR2xp33_ASAP7_75t_L _078_ (
    .A(_002_),
    .B(G0),
    .Y(_039_)
  );
  NOR2xp33_ASAP7_75t_L _079_ (
    .A(G0),
    .B(_010_),
    .Y(_040_)
  );
  AOI21xp33_ASAP7_75t_L _080_ (
    .A1(_002_),
    .A2(_010_),
    .B(G0),
    .Y(_041_)
  );
  AOI21xp33_ASAP7_75t_L _081_ (
    .A1(_037_),
    .A2(_038_),
    .B(_041_),
    .Y(\DFF_16.D )
  );
  NAND2xp33_ASAP7_75t_L _082_ (
    .A(_003_),
    .B(_009_),
    .Y(_042_)
  );
  NOR4xp25_ASAP7_75t_L _083_ (
    .A(_002_),
    .B(G0),
    .C(_011_),
    .D(_042_),
    .Y(_043_)
  );
  NAND4xp25_ASAP7_75t_L _084_ (
    .A(_031_),
    .B(_001_),
    .C(_009_),
    .D(_011_),
    .Y(_044_)
  );
  OA21x2_ASAP7_75t_L _085_ (
    .A1(_002_),
    .A2(_044_),
    .B(_040_),
    .Y(_045_)
  );
  O2A1O1Ixp33_ASAP7_75t_L _086_ (
    .A1(_002_),
    .A2(_044_),
    .B(_040_),
    .C(_043_),
    .Y(_046_)
  );
  INVx1_ASAP7_75t_L _087_ (
    .A(_046_),
    .Y(\DFF_13.D )
  );
  A2O1A1Ixp33_ASAP7_75t_L _088_ (
    .A1(_001_),
    .A2(_042_),
    .B(_011_),
    .C(_039_),
    .Y(_047_)
  );
  AOI21xp33_ASAP7_75t_L _089_ (
    .A1(_035_),
    .A2(_044_),
    .B(_047_),
    .Y(\DFF_14.D )
  );
  NOR3xp33_ASAP7_75t_L _090_ (
    .A(G0),
    .B(_003_),
    .C(_009_),
    .Y(_048_)
  );
  AOI211xp5_ASAP7_75t_L _091_ (
    .A1(_037_),
    .A2(_038_),
    .B(_041_),
    .C(_048_),
    .Y(\DFF_15.D )
  );
  AND3x1_ASAP7_75t_L _092_ (
    .A(_002_),
    .B(_010_),
    .C(_048_),
    .Y(\DFF_19.D )
  );
  AOI31xp33_ASAP7_75t_L _093_ (
    .A1(_004_),
    .A2(_005_),
    .A3(_018_),
    .B(_017_),
    .Y(_049_)
  );
  NOR2xp33_ASAP7_75t_L _094_ (
    .A(G0),
    .B(_049_),
    .Y(_050_)
  );
  AND2x2_ASAP7_75t_L _095_ (
    .A(_005_),
    .B(_050_),
    .Y(\DFF_0.D )
  );
  AOI211xp5_ASAP7_75t_L _096_ (
    .A1(_005_),
    .A2(_018_),
    .B(_049_),
    .C(G0),
    .Y(_051_)
  );
  OA21x2_ASAP7_75t_L _097_ (
    .A1(_005_),
    .A2(_018_),
    .B(_051_),
    .Y(\DFF_1.D )
  );
  OAI31xp33_ASAP7_75t_L _098_ (
    .A1(_004_),
    .A2(_005_),
    .A3(_018_),
    .B(_017_),
    .Y(_052_)
  );
  OA21x2_ASAP7_75t_L _099_ (
    .A1(_005_),
    .A2(_018_),
    .B(_004_),
    .Y(_053_)
  );
  NOR3xp33_ASAP7_75t_L _100_ (
    .A(G0),
    .B(_052_),
    .C(_053_),
    .Y(\DFF_2.D )
  );
  AND2x2_ASAP7_75t_L _101_ (
    .A(_050_),
    .B(_052_),
    .Y(\DFF_3.D )
  );
  NOR3xp33_ASAP7_75t_L _102_ (
    .A(G0),
    .B(_001_),
    .C(_042_),
    .Y(_054_)
  );
  OAI22xp33_ASAP7_75t_L _103_ (
    .A1(_000_),
    .A2(_046_),
    .B1(_054_),
    .B2(_041_),
    .Y(\DFF_17.D )
  );
  AND3x1_ASAP7_75t_L _104_ (
    .A(_002_),
    .B(_003_),
    .C(_009_),
    .Y(_055_)
  );
  AO22x1_ASAP7_75t_L _105_ (
    .A1(_001_),
    .A2(_043_),
    .B1(_055_),
    .B2(_038_),
    .Y(_056_)
  );
  OAI22xp33_ASAP7_75t_L _106_ (
    .A1(_000_),
    .A2(_046_),
    .B1(_056_),
    .B2(_045_),
    .Y(\DFF_18.D )
  );
  NOR2xp33_ASAP7_75t_L _107_ (
    .A(_036_),
    .B(_049_),
    .Y(_057_)
  );
  AOI31xp33_ASAP7_75t_L _108_ (
    .A1(_000_),
    .A2(_006_),
    .A3(_008_),
    .B(_007_),
    .Y(_058_)
  );
  OAI21xp33_ASAP7_75t_L _109_ (
    .A1(_036_),
    .A2(_049_),
    .B(_058_),
    .Y(_059_)
  );
  O2A1O1Ixp33_ASAP7_75t_L _110_ (
    .A1(_036_),
    .A2(_049_),
    .B(_058_),
    .C(G0),
    .Y(_060_)
  );
  OAI21xp33_ASAP7_75t_L _111_ (
    .A1(_008_),
    .A2(_057_),
    .B(_060_),
    .Y(_061_)
  );
  AOI21xp33_ASAP7_75t_L _112_ (
    .A1(_008_),
    .A2(_057_),
    .B(_061_),
    .Y(\DFF_4.D )
  );
  OAI211xp5_ASAP7_75t_L _113_ (
    .A1(_036_),
    .A2(_049_),
    .B(_033_),
    .C(_034_),
    .Y(_062_)
  );
  NAND2xp33_ASAP7_75t_L _114_ (
    .A(_060_),
    .B(_062_),
    .Y(_063_)
  );
  O2A1O1Ixp33_ASAP7_75t_L _115_ (
    .A1(_008_),
    .A2(_057_),
    .B(_006_),
    .C(_063_),
    .Y(\DFF_5.D )
  );
  OR2x2_ASAP7_75t_L _116_ (
    .A(_000_),
    .B(_062_),
    .Y(_064_)
  );
  NAND2xp33_ASAP7_75t_L _117_ (
    .A(_000_),
    .B(_062_),
    .Y(_019_)
  );
  AND3x1_ASAP7_75t_L _118_ (
    .A(_060_),
    .B(_064_),
    .C(_019_),
    .Y(\DFF_6.D )
  );
  OAI21xp33_ASAP7_75t_L _119_ (
    .A1(_000_),
    .A2(_062_),
    .B(_007_),
    .Y(_020_)
  );
  AND2x2_ASAP7_75t_L _120_ (
    .A(_060_),
    .B(_020_),
    .Y(\DFF_7.D )
  );
  OAI31xp33_ASAP7_75t_L _121_ (
    .A1(_001_),
    .A2(_055_),
    .A3(_059_),
    .B(_030_),
    .Y(_021_)
  );
  OAI211xp5_ASAP7_75t_L _122_ (
    .A1(_036_),
    .A2(_049_),
    .B(_058_),
    .C(_031_),
    .Y(_022_)
  );
  XNOR2xp5_ASAP7_75t_L _123_ (
    .A(_003_),
    .B(_059_),
    .Y(_023_)
  );
  NOR2xp33_ASAP7_75t_L _124_ (
    .A(_021_),
    .B(_023_),
    .Y(\DFF_8.D )
  );
  XNOR2xp5_ASAP7_75t_L _125_ (
    .A(_009_),
    .B(_022_),
    .Y(_024_)
  );
  NOR2xp33_ASAP7_75t_L _126_ (
    .A(_021_),
    .B(_024_),
    .Y(\DFF_9.D )
  );
  NOR3xp33_ASAP7_75t_L _127_ (
    .A(_002_),
    .B(_009_),
    .C(_022_),
    .Y(_025_)
  );
  OR3x1_ASAP7_75t_L _128_ (
    .A(_002_),
    .B(_009_),
    .C(_022_),
    .Y(_026_)
  );
  OA21x2_ASAP7_75t_L _129_ (
    .A1(_009_),
    .A2(_022_),
    .B(_002_),
    .Y(_027_)
  );
  NOR3xp33_ASAP7_75t_L _130_ (
    .A(_021_),
    .B(_025_),
    .C(_027_),
    .Y(\DFF_10.D )
  );
  AOI21xp33_ASAP7_75t_L _131_ (
    .A1(_001_),
    .A2(_026_),
    .B(_021_),
    .Y(\DFF_11.D )
  );
  AOI21xp33_ASAP7_75t_L _132_ (
    .A1(G1),
    .A2(_036_),
    .B(G0),
    .Y(_028_)
  );
  OA21x2_ASAP7_75t_L _133_ (
    .A1(G1),
    .A2(_036_),
    .B(_028_),
    .Y(\DFF_20.D )
  );
  OAI21xp33_ASAP7_75t_L _134_ (
    .A1(_032_),
    .A2(_011_),
    .B(_030_),
    .Y(_029_)
  );
  AOI21xp33_ASAP7_75t_L _135_ (
    .A1(_032_),
    .A2(_011_),
    .B(_029_),
    .Y(\DFF_12.D )
  );
  DFFHQNx1_ASAP7_75t_R _136_ (
    .CLK(CK),
    .D(\DFF_6.D ),
    .QN(_000_)
  );
  DFFHQNx1_ASAP7_75t_R _137_ (
    .CLK(CK),
    .D(\DFF_5.D ),
    .QN(_006_)
  );
  DFFHQNx1_ASAP7_75t_R _138_ (
    .CLK(CK),
    .D(\DFF_7.D ),
    .QN(_007_)
  );
  DFFHQNx1_ASAP7_75t_R _139_ (
    .CLK(CK),
    .D(\DFF_4.D ),
    .QN(_008_)
  );
  DFFHQNx1_ASAP7_75t_R _140_ (
    .CLK(CK),
    .D(\DFF_8.D ),
    .QN(_003_)
  );
  DFFHQNx1_ASAP7_75t_R _141_ (
    .CLK(CK),
    .D(\DFF_11.D ),
    .QN(_001_)
  );
  DFFHQNx1_ASAP7_75t_R _142_ (
    .CLK(CK),
    .D(\DFF_9.D ),
    .QN(_009_)
  );
  DFFHQNx1_ASAP7_75t_R _143_ (
    .CLK(CK),
    .D(\DFF_10.D ),
    .QN(_002_)
  );
  DFFHQNx1_ASAP7_75t_R _144_ (
    .CLK(CK),
    .D(\DFF_13.D ),
    .QN(_010_)
  );
  DFFHQNx1_ASAP7_75t_R _145_ (
    .CLK(CK),
    .D(\DFF_12.D ),
    .QN(_011_)
  );
  DFFHQNx1_ASAP7_75t_R _146_ (
    .CLK(CK),
    .D(\DFF_14.D ),
    .QN(_012_)
  );
  DFFHQNx1_ASAP7_75t_R _147_ (
    .CLK(CK),
    .D(\DFF_15.D ),
    .QN(_013_)
  );
  DFFHQNx1_ASAP7_75t_R _148_ (
    .CLK(CK),
    .D(\DFF_18.D ),
    .QN(G167)
  );
  DFFHQNx1_ASAP7_75t_R _149_ (
    .CLK(CK),
    .D(\DFF_20.D ),
    .QN(_014_)
  );
  DFFHQNx1_ASAP7_75t_R _150_ (
    .CLK(CK),
    .D(\DFF_17.D ),
    .QN(G119)
  );
  DFFHQNx1_ASAP7_75t_R _151_ (
    .CLK(CK),
    .D(\DFF_19.D ),
    .QN(_015_)
  );
  DFFHQNx1_ASAP7_75t_R _152_ (
    .CLK(CK),
    .D(\DFF_16.D ),
    .QN(_016_)
  );
  DFFHQNx1_ASAP7_75t_R _153_ (
    .CLK(CK),
    .D(\DFF_2.D ),
    .QN(_004_)
  );
  DFFHQNx1_ASAP7_75t_R _154_ (
    .CLK(CK),
    .D(\DFF_3.D ),
    .QN(_017_)
  );
  DFFHQNx1_ASAP7_75t_R _155_ (
    .CLK(CK),
    .D(\DFF_1.D ),
    .QN(_018_)
  );
  DFFHQNx1_ASAP7_75t_R _156_ (
    .CLK(CK),
    .D(\DFF_0.D ),
    .QN(_005_)
  );
  assign \DFF_0.CK  = CK;
  assign \DFF_1.CK  = CK;
  assign \DFF_10.CK  = CK;
  assign \DFF_11.CK  = CK;
  assign \DFF_12.CK  = CK;
  assign \DFF_13.CK  = CK;
  assign \DFF_14.CK  = CK;
  assign \DFF_14.Q  = G107;
  assign \DFF_15.CK  = CK;
  assign \DFF_15.Q  = G108;
  assign \DFF_16.CK  = CK;
  assign \DFF_16.Q  = G118;
  assign \DFF_17.CK  = CK;
  assign \DFF_18.CK  = CK;
  assign \DFF_19.CK  = CK;
  assign \DFF_19.Q  = G168;
  assign \DFF_2.CK  = CK;
  assign \DFF_20.CK  = CK;
  assign \DFF_3.CK  = CK;
  assign \DFF_4.CK  = CK;
  assign \DFF_5.CK  = CK;
  assign \DFF_6.CK  = CK;
  assign \DFF_7.CK  = CK;
  assign \DFF_8.CK  = CK;
  assign \DFF_9.CK  = CK;
  assign G101 = \DFF_12.D ;
  assign G106 = G2;
  assign G109 = \DFF_14.D ;
  assign G110 = \DFF_15.D ;
  assign G111 = \DFF_16.D ;
  assign G112 = \DFF_17.D ;
  assign G113 = \DFF_18.D ;
  assign G114 = \DFF_19.D ;
  assign G152 = G0;
  assign G155 = \DFF_20.D ;
  assign G160 = G1;
  assign G162 = \DFF_13.D ;
  assign G162BF = \DFF_13.D ;
  assign G25 = G107;
  assign G26 = G108;
  assign G27 = G118;
  assign G30 = G168;
  assign G37 = \DFF_0.D ;
  assign G41 = \DFF_1.D ;
  assign G45 = \DFF_2.D ;
  assign G49 = \DFF_3.D ;
  assign G58 = \DFF_4.D ;
  assign G62 = \DFF_5.D ;
  assign G66 = \DFF_6.D ;
  assign G70 = \DFF_7.D ;
  assign G80 = \DFF_8.D ;
  assign G84 = \DFF_9.D ;
  assign G88 = \DFF_10.D ;
  assign G92 = \DFF_11.D ;
  assign IIII181 = 1'h1;
endmodule
