###############################################################
#  Generated by:      gen_sdc.py
#  Generated on:      Mon Jul 21 16:10:09 2025
#  Design:            aes_cipher_top
###############################################################
current_design aes_cipher_top
create_clock [get_ports {clk}] -name clk -period 260.0 -waveform {0.0 130.0}
set_input_transition -min 2.6  [get_ports {clk}]
set_input_transition -max 13  [get_ports {clk}]
set_input_transition -min 2.6  [get_ports {ld}]
set_input_transition -max 13  [get_ports {ld}]
set_input_delay -add_delay 13 -min -clock [get_clocks {clk}] [get_ports {ld}]
set_input_delay -add_delay 26 -max -clock [get_clocks {clk}] [get_ports {ld}]
set_input_transition -min 2.6  [get_ports {rst}]
set_input_transition -max 13  [get_ports {rst}]
set_input_delay -add_delay 13 -min -clock [get_clocks {clk}] [get_ports {rst}]
set_input_delay -add_delay 26 -max -clock [get_clocks {clk}] [get_ports {rst}]
set_max_transition 2.6  [get_ports {done}]
set_output_delay -add_delay 13 -min -clock [get_clocks {clk}] [get_ports {done}]
set_output_delay -add_delay 26 -max -clock [get_clocks {clk}] [get_ports {done}]
