/* Generated by Yosys 0.54+29 (git sha1 7b0c1fe49, g++ 9.4.0-1ubuntu1~20.04.2 -fPIC -O3) */

module s27(GND, VDD, CK, G0, G1, G17, G2, G3);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  input CK;
  wire CK;
  wire \DFF_0.CK ;
  wire \DFF_0.D ;
  wire \DFF_1.CK ;
  wire \DFF_1.D ;
  wire \DFF_2.CK ;
  wire \DFF_2.D ;
  input G0;
  wire G0;
  input G1;
  wire G1;
  wire G10;
  wire G11;
  wire G13;
  output G17;
  wire G17;
  input G2;
  wire G2;
  input G3;
  wire G3;
  input GND;
  wire GND;
  input VDD;
  wire VDD;
  INVx1_ASAP7_75t_L _08_ (
    .A(G1),
    .Y(_03_)
  );
  INVx1_ASAP7_75t_L _09_ (
    .A(_02_),
    .Y(_04_)
  );
  NOR2xp33_ASAP7_75t_L _10_ (
    .A(G0),
    .B(_00_),
    .Y(_05_)
  );
  AND2x2_ASAP7_75t_L _11_ (
    .A(_03_),
    .B(_01_),
    .Y(_06_)
  );
  NAND3xp33_ASAP7_75t_L _12_ (
    .A(G3),
    .B(_03_),
    .C(_01_),
    .Y(_07_)
  );
  O2A1O1Ixp33_ASAP7_75t_L _13_ (
    .A1(G0),
    .A2(_00_),
    .B(_07_),
    .C(_04_),
    .Y(\DFF_1.D )
  );
  A2O1A1Ixp33_ASAP7_75t_L _14_ (
    .A1(G3),
    .A2(_06_),
    .B(_05_),
    .C(_02_),
    .Y(G17)
  );
  OA21x2_ASAP7_75t_L _15_ (
    .A1(_04_),
    .A2(_07_),
    .B(G0),
    .Y(\DFF_0.D )
  );
  NOR2xp33_ASAP7_75t_L _16_ (
    .A(G2),
    .B(_06_),
    .Y(\DFF_2.D )
  );
  DFFHQNx1_ASAP7_75t_R _17_ (
    .CLK(CK),
    .D(\DFF_2.D ),
    .QN(_01_)
  );
  DFFHQNx1_ASAP7_75t_R _18_ (
    .CLK(CK),
    .D(\DFF_0.D ),
    .QN(_02_)
  );
  DFFHQNx1_ASAP7_75t_R _19_ (
    .CLK(CK),
    .D(\DFF_1.D ),
    .QN(_00_)
  );
  assign \DFF_0.CK  = CK;
  assign \DFF_1.CK  = CK;
  assign \DFF_2.CK  = CK;
  assign G10 = \DFF_0.D ;
  assign G11 = \DFF_1.D ;
  assign G13 = \DFF_2.D ;
endmodule
