/* Generated by Yosys 0.54+29 (git sha1 7b0c1fe49, g++ 9.4.0-1ubuntu1~20.04.2 -fPIC -O3) */

module s386(GND, VDD, CK, v0, v1, v13_D_10, v13_D_11, v13_D_12, v13_D_6, v13_D_7, v13_D_8, v13_D_9, v2, v3, v4, v5, v6);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  input CK;
  wire CK;
  wire \DFF_0.CK ;
  wire \DFF_0.D ;
  wire \DFF_1.CK ;
  wire \DFF_1.D ;
  wire \DFF_2.CK ;
  wire \DFF_2.D ;
  wire \DFF_3.CK ;
  wire \DFF_3.D ;
  wire \DFF_4.CK ;
  wire \DFF_4.D ;
  wire \DFF_5.CK ;
  wire \DFF_5.D ;
  input GND;
  wire GND;
  wire Lv13_D_0;
  wire Lv13_D_1;
  wire Lv13_D_10;
  wire Lv13_D_11;
  wire Lv13_D_12;
  wire Lv13_D_2;
  wire Lv13_D_3;
  wire Lv13_D_4;
  wire Lv13_D_5;
  wire Lv13_D_6;
  wire Lv13_D_7;
  wire Lv13_D_8;
  wire Lv13_D_9;
  input VDD;
  wire VDD;
  input v0;
  wire v0;
  input v1;
  wire v1;
  wire v13_D_0;
  wire v13_D_1;
  output v13_D_10;
  wire v13_D_10;
  output v13_D_11;
  wire v13_D_11;
  output v13_D_12;
  wire v13_D_12;
  wire v13_D_2;
  wire v13_D_3;
  wire v13_D_4;
  wire v13_D_5;
  output v13_D_6;
  wire v13_D_6;
  output v13_D_7;
  wire v13_D_7;
  output v13_D_8;
  wire v13_D_8;
  output v13_D_9;
  wire v13_D_9;
  input v2;
  wire v2;
  input v3;
  wire v3;
  input v4;
  wire v4;
  input v5;
  wire v5;
  input v6;
  wire v6;
  INVx1_ASAP7_75t_L _060_ (
    .A(v5),
    .Y(_006_)
  );
  INVx1_ASAP7_75t_L _061_ (
    .A(_000_),
    .Y(_007_)
  );
  INVx1_ASAP7_75t_L _062_ (
    .A(_001_),
    .Y(_008_)
  );
  INVx1_ASAP7_75t_L _063_ (
    .A(v1),
    .Y(_009_)
  );
  INVx1_ASAP7_75t_L _064_ (
    .A(v4),
    .Y(_010_)
  );
  INVx1_ASAP7_75t_L _065_ (
    .A(_002_),
    .Y(_011_)
  );
  INVx1_ASAP7_75t_L _066_ (
    .A(_003_),
    .Y(_012_)
  );
  INVx1_ASAP7_75t_L _067_ (
    .A(_004_),
    .Y(_013_)
  );
  INVx1_ASAP7_75t_L _068_ (
    .A(_005_),
    .Y(_014_)
  );
  NAND3xp33_ASAP7_75t_L _069_ (
    .A(v5),
    .B(_000_),
    .C(_003_),
    .Y(_015_)
  );
  AND2x2_ASAP7_75t_L _070_ (
    .A(_001_),
    .B(_002_),
    .Y(_016_)
  );
  NAND2xp33_ASAP7_75t_L _071_ (
    .A(_001_),
    .B(_002_),
    .Y(_017_)
  );
  NOR5xp2_ASAP7_75t_L _072_ (
    .A(v0),
    .B(_004_),
    .C(_005_),
    .D(_015_),
    .E(_017_),
    .Y(v13_D_12)
  );
  AND4x1_ASAP7_75t_L _073_ (
    .A(v0),
    .B(_000_),
    .C(_003_),
    .D(_016_),
    .Y(_018_)
  );
  NAND3xp33_ASAP7_75t_L _074_ (
    .A(_004_),
    .B(_014_),
    .C(_018_),
    .Y(_019_)
  );
  NOR2xp33_ASAP7_75t_L _075_ (
    .A(v6),
    .B(_019_),
    .Y(v13_D_8)
  );
  NAND3xp33_ASAP7_75t_L _076_ (
    .A(_000_),
    .B(v1),
    .C(_003_),
    .Y(_020_)
  );
  AOI21xp33_ASAP7_75t_L _077_ (
    .A1(v0),
    .A2(v5),
    .B(_005_),
    .Y(_021_)
  );
  NOR4xp25_ASAP7_75t_L _078_ (
    .A(_004_),
    .B(_017_),
    .C(_020_),
    .D(_021_),
    .Y(v13_D_10)
  );
  NOR2xp33_ASAP7_75t_L _079_ (
    .A(_000_),
    .B(v3),
    .Y(_022_)
  );
  NAND3xp33_ASAP7_75t_L _080_ (
    .A(_010_),
    .B(_002_),
    .C(_022_),
    .Y(_023_)
  );
  NAND2xp33_ASAP7_75t_L _081_ (
    .A(_000_),
    .B(_011_),
    .Y(_024_)
  );
  NOR2xp33_ASAP7_75t_L _082_ (
    .A(_003_),
    .B(_024_),
    .Y(_025_)
  );
  AND4x1_ASAP7_75t_L _083_ (
    .A(v0),
    .B(_009_),
    .C(_004_),
    .D(_005_),
    .Y(_026_)
  );
  NAND4xp25_ASAP7_75t_L _084_ (
    .A(v0),
    .B(_009_),
    .C(_004_),
    .D(_005_),
    .Y(_027_)
  );
  NAND2xp33_ASAP7_75t_L _085_ (
    .A(_001_),
    .B(_026_),
    .Y(_028_)
  );
  O2A1O1Ixp33_ASAP7_75t_L _086_ (
    .A1(_003_),
    .A2(_024_),
    .B(_023_),
    .C(_028_),
    .Y(v13_D_7)
  );
  AOI31xp33_ASAP7_75t_L _087_ (
    .A1(_009_),
    .A2(v4),
    .A3(_022_),
    .B(_014_),
    .Y(_029_)
  );
  AOI21xp33_ASAP7_75t_L _088_ (
    .A1(v0),
    .A2(_000_),
    .B(_005_),
    .Y(_030_)
  );
  NOR5xp2_ASAP7_75t_L _089_ (
    .A(_012_),
    .B(_013_),
    .C(_017_),
    .D(_029_),
    .E(_030_),
    .Y(v13_D_9)
  );
  A2O1A1O1Ixp25_ASAP7_75t_L _090_ (
    .A1(_007_),
    .A2(_012_),
    .B(_002_),
    .C(_023_),
    .D(_028_),
    .Y(\DFF_5.D )
  );
  NOR3xp33_ASAP7_75t_L _091_ (
    .A(_000_),
    .B(_002_),
    .C(_003_),
    .Y(_031_)
  );
  NAND2xp33_ASAP7_75t_L _092_ (
    .A(_007_),
    .B(v3),
    .Y(_032_)
  );
  NAND2xp33_ASAP7_75t_L _093_ (
    .A(v2),
    .B(_016_),
    .Y(_033_)
  );
  OAI22xp33_ASAP7_75t_L _094_ (
    .A1(_001_),
    .A2(_024_),
    .B1(_032_),
    .B2(_033_),
    .Y(_034_)
  );
  AOI22xp33_ASAP7_75t_L _095_ (
    .A1(_001_),
    .A2(_031_),
    .B1(_034_),
    .B2(_003_),
    .Y(_035_)
  );
  NOR2xp33_ASAP7_75t_L _096_ (
    .A(_027_),
    .B(_035_),
    .Y(\DFF_0.D )
  );
  NAND2xp33_ASAP7_75t_L _097_ (
    .A(_008_),
    .B(_011_),
    .Y(_036_)
  );
  OAI31xp33_ASAP7_75t_L _098_ (
    .A1(v5),
    .A2(_012_),
    .A3(_036_),
    .B(_033_),
    .Y(_037_)
  );
  NAND3xp33_ASAP7_75t_L _099_ (
    .A(_000_),
    .B(_026_),
    .C(_037_),
    .Y(_038_)
  );
  A2O1A1Ixp33_ASAP7_75t_L _100_ (
    .A1(_003_),
    .A2(_023_),
    .B(_028_),
    .C(_038_),
    .Y(\DFF_1.D )
  );
  OAI21xp33_ASAP7_75t_L _101_ (
    .A1(_010_),
    .A2(_003_),
    .B(_022_),
    .Y(_039_)
  );
  OR2x2_ASAP7_75t_L _102_ (
    .A(v2),
    .B(_012_),
    .Y(_040_)
  );
  NAND3xp33_ASAP7_75t_L _103_ (
    .A(_016_),
    .B(_039_),
    .C(_040_),
    .Y(_041_)
  );
  O2A1O1Ixp33_ASAP7_75t_L _104_ (
    .A1(_015_),
    .A2(_036_),
    .B(_041_),
    .C(_027_),
    .Y(v13_D_6)
  );
  OAI21xp33_ASAP7_75t_L _105_ (
    .A1(v2),
    .A2(_012_),
    .B(v4),
    .Y(_042_)
  );
  A2O1A1Ixp33_ASAP7_75t_L _106_ (
    .A1(_000_),
    .A2(v4),
    .B(_012_),
    .C(_002_),
    .Y(_043_)
  );
  AOI22xp33_ASAP7_75t_L _107_ (
    .A1(_032_),
    .A2(_042_),
    .B1(_043_),
    .B2(_040_),
    .Y(_044_)
  );
  AOI21xp33_ASAP7_75t_L _108_ (
    .A1(_007_),
    .A2(_002_),
    .B(_012_),
    .Y(_045_)
  );
  OAI211xp5_ASAP7_75t_L _109_ (
    .A1(_007_),
    .A2(_008_),
    .B(_036_),
    .C(_045_),
    .Y(_046_)
  );
  A2O1A1Ixp33_ASAP7_75t_L _110_ (
    .A1(v5),
    .A2(_025_),
    .B(_044_),
    .C(_001_),
    .Y(_047_)
  );
  AOI21xp33_ASAP7_75t_L _111_ (
    .A1(_046_),
    .A2(_047_),
    .B(_027_),
    .Y(\DFF_4.D )
  );
  AOI32xp33_ASAP7_75t_L _112_ (
    .A1(_001_),
    .A2(_004_),
    .A3(_005_),
    .B1(_003_),
    .B2(_000_),
    .Y(_048_)
  );
  OAI21xp33_ASAP7_75t_L _113_ (
    .A1(_009_),
    .A2(_013_),
    .B(v0),
    .Y(_049_)
  );
  OAI21xp33_ASAP7_75t_L _114_ (
    .A1(_005_),
    .A2(_016_),
    .B(_049_),
    .Y(_050_)
  );
  NAND3xp33_ASAP7_75t_L _115_ (
    .A(_006_),
    .B(_014_),
    .C(_016_),
    .Y(_051_)
  );
  OAI22xp33_ASAP7_75t_L _116_ (
    .A1(_048_),
    .A2(_050_),
    .B1(_051_),
    .B2(_020_),
    .Y(\DFF_2.D )
  );
  OAI21xp33_ASAP7_75t_L _117_ (
    .A1(_007_),
    .A2(_012_),
    .B(_008_),
    .Y(_052_)
  );
  AOI31xp33_ASAP7_75t_L _118_ (
    .A1(_004_),
    .A2(_005_),
    .A3(_052_),
    .B(_018_),
    .Y(_053_)
  );
  AOI31xp33_ASAP7_75t_L _119_ (
    .A1(_006_),
    .A2(_013_),
    .A3(_016_),
    .B(_005_),
    .Y(_054_)
  );
  OAI32xp33_ASAP7_75t_L _120_ (
    .A1(v0),
    .A2(_048_),
    .A3(_054_),
    .B1(_053_),
    .B2(_009_),
    .Y(\DFF_3.D )
  );
  AOI21xp33_ASAP7_75t_L _121_ (
    .A1(_004_),
    .A2(_018_),
    .B(_005_),
    .Y(_055_)
  );
  AOI22xp33_ASAP7_75t_L _122_ (
    .A1(_000_),
    .A2(_003_),
    .B1(_004_),
    .B2(_001_),
    .Y(_056_)
  );
  AOI311xp33_ASAP7_75t_L _123_ (
    .A1(_010_),
    .A2(_002_),
    .A3(_022_),
    .B(_031_),
    .C(v1),
    .Y(_057_)
  );
  A2O1A1Ixp33_ASAP7_75t_L _124_ (
    .A1(_008_),
    .A2(_020_),
    .B(_057_),
    .C(_005_),
    .Y(_058_)
  );
  NAND2xp33_ASAP7_75t_L _125_ (
    .A(_004_),
    .B(_058_),
    .Y(_059_)
  );
  O2A1O1Ixp33_ASAP7_75t_L _126_ (
    .A1(v0),
    .A2(_056_),
    .B(_059_),
    .C(_055_),
    .Y(v13_D_11)
  );
  DFFHQNx1_ASAP7_75t_R _127_ (
    .CLK(CK),
    .D(\DFF_3.D ),
    .QN(_004_)
  );
  DFFHQNx1_ASAP7_75t_R _128_ (
    .CLK(CK),
    .D(\DFF_2.D ),
    .QN(_005_)
  );
  DFFHQNx1_ASAP7_75t_R _129_ (
    .CLK(CK),
    .D(\DFF_4.D ),
    .QN(_000_)
  );
  DFFHQNx1_ASAP7_75t_R _130_ (
    .CLK(CK),
    .D(\DFF_1.D ),
    .QN(_002_)
  );
  DFFHQNx1_ASAP7_75t_R _131_ (
    .CLK(CK),
    .D(\DFF_5.D ),
    .QN(_003_)
  );
  DFFHQNx1_ASAP7_75t_R _132_ (
    .CLK(CK),
    .D(\DFF_0.D ),
    .QN(_001_)
  );
  assign \DFF_0.CK  = CK;
  assign \DFF_1.CK  = CK;
  assign \DFF_2.CK  = CK;
  assign \DFF_3.CK  = CK;
  assign \DFF_4.CK  = CK;
  assign \DFF_5.CK  = CK;
  assign Lv13_D_0 = \DFF_5.D ;
  assign Lv13_D_1 = \DFF_4.D ;
  assign Lv13_D_10 = v13_D_10;
  assign Lv13_D_11 = v13_D_11;
  assign Lv13_D_12 = v13_D_12;
  assign Lv13_D_2 = \DFF_3.D ;
  assign Lv13_D_3 = \DFF_2.D ;
  assign Lv13_D_4 = \DFF_1.D ;
  assign Lv13_D_5 = \DFF_0.D ;
  assign Lv13_D_6 = v13_D_6;
  assign Lv13_D_7 = v13_D_7;
  assign Lv13_D_8 = v13_D_8;
  assign Lv13_D_9 = v13_D_9;
  assign v13_D_0 = \DFF_5.D ;
  assign v13_D_1 = \DFF_4.D ;
  assign v13_D_2 = \DFF_3.D ;
  assign v13_D_3 = \DFF_2.D ;
  assign v13_D_4 = \DFF_1.D ;
  assign v13_D_5 = \DFF_0.D ;
endmodule
