UCLA scl 1.0

NumRows : 333

CoreRow Horizontal
  Coordinate   : 560
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : 0
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 565
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : MX
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 570
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : 0
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 575
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : MX
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 580
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : 0
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 585
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : MX
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 590
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : 0
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 595
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : MX
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 600
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : 0
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 605
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : MX
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 610
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : 0
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 615
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : MX
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 620
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : 0
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 625
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : MX
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 630
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : 0
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 635
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : MX
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 640
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : 0
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 645
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : MX
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 650
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : 0
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 655
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : MX
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 660
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : 0
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 665
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : MX
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 670
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : 0
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 675
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : MX
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 680
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : 0
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 685
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : MX
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 690
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : 0
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 695
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : MX
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 700
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : 0
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 705
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : MX
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 710
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : 0
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 715
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : MX
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 720
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : 0
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 725
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : MX
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 730
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : 0
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 735
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : MX
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 740
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : 0
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 745
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : MX
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 750
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : 0
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 755
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : MX
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 760
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : 0
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 765
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : MX
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 770
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : 0
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 775
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : MX
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 780
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : 0
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 785
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : MX
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 790
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : 0
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 795
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : MX
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 800
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : 0
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 805
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : MX
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 810
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : 0
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 815
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : MX
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 820
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : 0
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 825
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : MX
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 830
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : 0
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 835
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : MX
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 840
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : 0
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 845
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : MX
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 850
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : 0
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 855
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : MX
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 860
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : 0
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 865
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : MX
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 870
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : 0
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 875
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : MX
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 880
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : 0
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 885
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : MX
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 890
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : 0
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 895
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : MX
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 900
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : 0
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 905
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : MX
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 910
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : 0
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 915
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : MX
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 920
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : 0
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 925
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : MX
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 930
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : 0
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 935
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : MX
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 940
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : 0
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 945
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : MX
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 950
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : 0
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 955
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : MX
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 960
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : 0
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 965
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : MX
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 970
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : 0
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 975
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : MX
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 980
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : 0
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 985
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : MX
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 990
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : 0
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 995
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : MX
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 1000
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : 0
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 1005
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : MX
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 1010
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : 0
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 1015
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : MX
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 1020
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : 0
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 1025
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : MX
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 1030
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : 0
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 1035
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : MX
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 1040
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : 0
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 1045
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : MX
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 1050
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : 0
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 1055
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : MX
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 1060
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : 0
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 1065
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : MX
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 1070
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : 0
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 1075
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : MX
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 1080
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : 0
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 1085
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : MX
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 1090
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : 0
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 1095
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : MX
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 1100
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : 0
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 1105
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : MX
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 1110
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : 0
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 1115
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : MX
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 1120
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : 0
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 1125
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : MX
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 1130
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : 0
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 1135
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : MX
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 1140
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : 0
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 1145
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : MX
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 1150
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : 0
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 1155
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : MX
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 1160
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : 0
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 1165
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : MX
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 1170
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : 0
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 1175
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : MX
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 1180
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : 0
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 1185
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : MX
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 1190
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : 0
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 1195
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : MX
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 1200
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : 0
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 1205
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : MX
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 1210
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : 0
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 1215
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : MX
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 1220
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : 0
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 1225
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : MX
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 1230
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : 0
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 1235
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : MX
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 1240
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : 0
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 1245
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : MX
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 1250
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : 0
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 1255
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : MX
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 1260
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : 0
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 1265
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : MX
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 1270
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : 0
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 1275
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : MX
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 1280
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : 0
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 1285
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : MX
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 1290
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : 0
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 1295
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : MX
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 1300
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : 0
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 1305
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : MX
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 1310
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : 0
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 1315
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : MX
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 1320
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : 0
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 1325
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : MX
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 1330
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : 0
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 1335
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : MX
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 1340
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : 0
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 1345
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : MX
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 1350
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : 0
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 1355
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : MX
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 1360
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : 0
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 1365
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : MX
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 1370
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : 0
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 1375
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : MX
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 1380
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : 0
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 1385
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : MX
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 1390
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : 0
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 1395
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : MX
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 1400
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : 0
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 1405
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : MX
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 1410
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : 0
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 1415
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : MX
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 1420
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : 0
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 1425
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : MX
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 1430
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : 0
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 1435
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : MX
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 1440
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : 0
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 1445
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : MX
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 1450
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : 0
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 1455
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : MX
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 1460
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : 0
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 1465
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : MX
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 1470
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : 0
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 1475
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : MX
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 1480
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : 0
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 1485
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : MX
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 1490
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : 0
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 1495
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : MX
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 1500
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : 0
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 1505
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : MX
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 1510
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : 0
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 1515
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : MX
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 1520
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : 0
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 1525
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : MX
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 1530
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : 0
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 1535
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : MX
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 1540
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : 0
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 1545
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : MX
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 1550
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : 0
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 1555
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : MX
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 1560
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : 0
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 1565
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : MX
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 1570
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : 0
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 1575
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : MX
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 1580
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : 0
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 1585
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : MX
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 1590
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : 0
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 1595
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : MX
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 1600
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : 0
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 1605
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : MX
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 1610
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : 0
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 1615
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : MX
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 1620
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : 0
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 1625
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : MX
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 1630
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : 0
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 1635
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : MX
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 1640
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : 0
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 1645
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : MX
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 1650
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : 0
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 1655
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : MX
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 1660
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : 0
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 1665
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : MX
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 1670
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : 0
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 1675
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : MX
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 1680
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : 0
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 1685
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : MX
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 1690
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : 0
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 1695
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : MX
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 1700
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : 0
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 1705
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : MX
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 1710
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : 0
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 1715
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : MX
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 1720
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : 0
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 1725
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : MX
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 1730
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : 0
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 1735
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : MX
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 1740
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : 0
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 1745
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : MX
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 1750
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : 0
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 1755
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : MX
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 1760
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : 0
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 1765
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : MX
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 1770
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : 0
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 1775
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : MX
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 1780
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : 0
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 1785
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : MX
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 1790
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : 0
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 1795
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : MX
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 1800
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : 0
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 1805
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : MX
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 1810
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : 0
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 1815
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : MX
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 1820
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : 0
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 1825
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : MX
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 1830
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : 0
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 1835
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : MX
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 1840
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : 0
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 1845
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : MX
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 1850
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : 0
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 1855
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : MX
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 1860
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : 0
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 1865
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : MX
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 1870
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : 0
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 1875
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : MX
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 1880
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : 0
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 1885
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : MX
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 1890
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : 0
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 1895
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : MX
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 1900
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : 0
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 1905
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : MX
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 1910
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : 0
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 1915
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : MX
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 1920
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : 0
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 1925
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : MX
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 1930
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : 0
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 1935
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : MX
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 1940
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : 0
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 1945
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : MX
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 1950
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : 0
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 1955
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : MX
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 1960
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : 0
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 1965
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : MX
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 1970
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : 0
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 1975
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : MX
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 1980
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : 0
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 1985
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : MX
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 1990
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : 0
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 1995
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : MX
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 2000
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : 0
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 2005
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : MX
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 2010
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : 0
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 2015
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : MX
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 2020
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : 0
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 2025
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : MX
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 2030
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : 0
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 2035
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : MX
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 2040
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : 0
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 2045
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : MX
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 2050
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : 0
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 2055
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : MX
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 2060
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : 0
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 2065
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : MX
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 2070
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : 0
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 2075
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : MX
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 2080
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : 0
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 2085
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : MX
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 2090
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : 0
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 2095
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : MX
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 2100
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : 0
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 2105
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : MX
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 2110
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : 0
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 2115
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : MX
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 2120
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : 0
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 2125
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : MX
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 2130
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : 0
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 2135
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : MX
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 2140
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : 0
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 2145
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : MX
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 2150
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : 0
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 2155
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : MX
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 2160
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : 0
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 2165
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : MX
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 2170
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : 0
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 2175
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : MX
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 2180
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : 0
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 2185
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : MX
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 2190
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : 0
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 2195
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : MX
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 2200
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : 0
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 2205
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : MX
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 2210
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : 0
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 2215
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : MX
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
CoreRow Horizontal
  Coordinate   : 2220
  Height       : 5
  Sitewidth    : 1
  Sitespacing  : 1
  Siteorient   : 0
  Sitesymmetry : 1
  SubrowOrigin : 556  NumSites : 1669
End
