#!/usr/bin/env python3
"""
Generate an SDC file that mimics the style of the official contest reference.

Usage:
    python sdc.py <input_verilog_file> <output_sdc_file> [--clock CLK] [--period 260]

The script will:
  * 解析頂層模組名稱與所有 ports（含 bus 位元展開）。
  * 依照以下固定參數自動產生約束：
        - clock period          : --period (default 260)
        - input transition (min): 2.6
        - input transition (max): 13
        - input  delay (min)    : 13
        - input  delay (max)    : 26
        - output delay (min)    : 13
        - output delay (max)    : 26
        - max transition (out)  : 2.6
  * 對 clock port 亦自動套用 transition。
  * clock port 由 --clock 指定（預設 clk）。

產生的 <output_sdc_file> 內容格式與比賽提供的 aes_cipher_top.sdc 幾乎相同，可直接丟給
OpenROAD/Innovus 等 PnR 工具。
"""
import re, argparse, datetime, sys

TRANS_MIN = 2.6
TRANS_MAX = 13
IN_DELAY_MIN = 13
IN_DELAY_MAX = 26
OUT_DELAY_MIN = 13
OUT_DELAY_MAX = 26
MAX_TRANSITION = 2.6

PORT_RE = re.compile(r"^\s*(input|output)\s+(?:\[\s*(\d+)\s*:\s*(\d+)\s*\]\s*)?([\w$]+)")
MODULE_RE = re.compile(r"^\s*module\s+(\w+)\s*\(", re.MULTILINE)

def extract_ports(text):
    """Return lists of (inputs, outputs) with bus bits expanded."""
    inputs, outputs = [], []
    for line in text.splitlines():
        m = PORT_RE.match(line)
        if not m:
            continue
        direction, msb, lsb, name = m.groups()
        if msb and lsb:
            msb, lsb = int(msb), int(lsb)
            rng = range(msb, lsb-1, -1) if msb >= lsb else range(msb, lsb+1)
            ports = [f"{name}[{i}]" for i in rng]
        else:
            ports = [name]
        (inputs if direction == "input" else outputs).extend(ports)
    return inputs, outputs

def write_sdc(f, top, clk, per, inputs, outputs):
    now = datetime.datetime.now().strftime("%a %b %d %H:%M:%S %Y")
    f.write("#" * 63 + "\n")
    f.write(f"#  Generated by:      gen_sdc.py\n")
    f.write(f"#  Generated on:      {now}\n")
    f.write(f"#  Design:            {top}\n")
    f.write("#" * 63 + "\n")
    f.write(f"current_design {top}\n")
    f.write(f"create_clock [get_ports {{{clk}}}] -name {clk} -period {per} -waveform {{0.0 {per/2}}}\n")
    f.write(f"set_input_transition -min {TRANS_MIN}  [get_ports {{{clk}}}]\n")
    f.write(f"set_input_transition -max {TRANS_MAX}  [get_ports {{{clk}}}]\n")
    for p in inputs:
        if p == clk:
            continue
        f.write(f"set_input_transition -min {TRANS_MIN}  [get_ports {{{p}}}]\n")
        f.write(f"set_input_transition -max {TRANS_MAX}  [get_ports {{{p}}}]\n")
        f.write(f"set_input_delay -add_delay {IN_DELAY_MIN} -min -clock [get_clocks {{{clk}}}] [get_ports {{{p}}}]\n")
        f.write(f"set_input_delay -add_delay {IN_DELAY_MAX} -max -clock [get_clocks {{{clk}}}] [get_ports {{{p}}}]\n")
    for p in outputs:
        f.write(f"set_max_transition {MAX_TRANSITION}  [get_ports {{{p}}}]\n")
        f.write(f"set_output_delay -add_delay {OUT_DELAY_MIN} -min -clock [get_clocks {{{clk}}}] [get_ports {{{p}}}]\n")
        f.write(f"set_output_delay -add_delay {OUT_DELAY_MAX} -max -clock [get_clocks {{{clk}}}] [get_ports {{{p}}}]\n")

def main():
    ap = argparse.ArgumentParser(description="Auto‑generate SDC from Verilog top‑level module")
    ap.add_argument("input_file", help="Input Verilog netlist file path (*.v)")
    ap.add_argument("output_file", help="Output SDC file path (*.sdc)")
    ap.add_argument("--clock", default="clk", help="Clock port name (default: clk)")
    ap.add_argument("--period", type=float, default=260.0, help="Clock period (default: 260)")
    args = ap.parse_args()

    text = open(args.input_file).read()
    m = MODULE_RE.search(text)
    if not m:
        sys.exit("[ERROR] Top module not found.")
    top = m.group(1)
    inputs, outputs = extract_ports(text)

    if args.clock not in inputs and args.clock not in outputs:
        print(f"[WARN] Clock '{args.clock}' not found in port list; continuing anyway.")

    with open(args.output_file, "w") as f:
        write_sdc(f, top, args.clock, args.period, inputs, outputs)
    print(f"[INFO] SDC written to {args.output_file}")

if __name__ == "__main__":
    main()
